'use strict';
const SCHEMA='alpha-proof-accountant/1';
const RIYADH_OFFSET=3*3600000;
function n(v,d=0){v=Number(v);return Number.isFinite(v)?v:d}
function dayKey(t=Date.now()){return new Date(t+RIYADH_OFFSET).toISOString().slice(0,10)}
function initialState(){return {schema:SCHEMA,goalUsd:1000,positionNotionalUsd:0,reviews:[],daily:{},openIssues:[],cortexAccountability:[],lastReviewAt:null}}
function normalizeState(raw={}){let s={...initialState(),...(raw&&typeof raw==='object'?raw:{})};s.schema=SCHEMA;s.goalUsd=Math.max(0,n(s.goalUsd,1000));s.positionNotionalUsd=Math.max(0,n(s.positionNotionalUsd,0));for(const k of ['reviews','openIssues','cortexAccountability'])s[k]=Array.isArray(s[k])?s[k]:[];s.daily=s.daily&&typeof s.daily==='object'?s.daily:{};return s}
function moneyFromPct(pct,notional){return notional>0&&Number.isFinite(Number(pct))?notional*Number(pct)/100:null}
function auditTrade(raw,closed,journey=[],notional=0,now=Date.now()){
 let s=normalizeState(raw),id=closed?.cycleId;if(!id||s.reviews.some(x=>x.cycleId===id))return {state:s,created:false};
 let ai=closed.ai||{},out=ai.outcome||{},net=Number(closed.shadowNetPnlPct??out.netPnlPct),entry=n(closed.entryPrice),exit=n(closed.exitPrice),dir=closed.dir||'LONG';
 let pts=(journey||[]).filter(p=>p&&Number.isFinite(Number(p.price))).sort((a,b)=>n(a.t)-n(b.t));
 let risk=pts.find(p=>p.kind==='RISK'||p.flags?.risk===true),alternative=null;
 if(risk&&entry>0){let rp=n(risk.price),rawMove=(rp/entry-1)*100,signed=dir==='SHORT'?-rawMove:rawMove,fee=n(closed.shadowFeesPct,.2),altNet=signed-fee;if(Number.isFinite(net)&&altNet>net+.05)alternative={at:risk.t,price:rp,netPnlPct:altNet,improvementPct:altNet-net,reason:risk.riskReason||risk.flags?.riskReason||'ظهرت إشارة خطر مسجلة أثناء الصفقة'}}
 let classification=!Number.isFinite(net)?'UNVERIFIED':net>=0?'PROFIT':alternative?'AVOIDABLE_OR_REDUCIBLE_LOSS':'UNAVOIDED_LOSS_NO_PROVEN_ACTION';
 let review={id:`ACC-${id}`,cycleId:id,day:dayKey(closed.exitAt||now),symbol:closed.symbol,tf:closed.tf,dir,entryAt:closed.entryAt,exitAt:closed.exitAt,entryPrice:entry,exitPrice:exit,assetPriceMoveUsd:entry>0&&exit>0?(dir==='SHORT'?entry-exit:exit-entry):null,netPnlPct:Number.isFinite(net)?net:null,netUsd:moneyFromPct(net,notional),notionalUsd:notional||null,classification,alternative,alternativeUsd:alternative?moneyFromPct(alternative.netPnlPct,notional):null,improvementUsd:alternative?moneyFromPct(alternative.improvementPct,notional):null,reason:closed.result||null,reviewedAt:now};
 s.reviews.push(review);s.reviews=s.reviews.slice(-1000);s.lastReviewAt=now;
 let d=s.daily[review.day]||{day:review.day,trades:0,netUsd:0,knownUsdTrades:0,profitsUsd:0,lossesUsd:0,avoidableLosses:0,avoidableLossUsd:0,unresolvedLosses:0};d.trades++;if(review.netUsd!=null){d.knownUsdTrades++;d.netUsd+=review.netUsd;if(review.netUsd>=0)d.profitsUsd+=review.netUsd;else d.lossesUsd+=review.netUsd}if(classification==='AVOIDABLE_OR_REDUCIBLE_LOSS'){d.avoidableLosses++;if(review.improvementUsd!=null)d.avoidableLossUsd+=review.improvementUsd}else if(classification==='UNAVOIDED_LOSS_NO_PROVEN_ACTION')d.unresolvedLosses++;s.daily[review.day]=d;
 if(net<0)s.openIssues.push({id:`ISS-${id}`,cycleId:id,day:review.day,symbol:closed.symbol,tf:closed.tf,type:alternative?'TRADE_AI_ACTIONABLE_LOSS':'TRADE_AI_UNEXPLAINED_LOSS',status:'OPEN',lossUsd:review.netUsd,lossPct:net,summary:alternative?`الخسارة كان يمكن تخفيفها عند ${new Date(alternative.at).toISOString()} وفق إشارة خطر كانت متاحة وقتها.`:'خسارة لم يثبت المحاسب حتى الآن إجراءً متاحًا وقتها كان سيمنعها.',createdAt:now});s.openIssues=s.openIssues.slice(-500);
 return {state:s,created:true,review}
}
function auditCortex(raw,problems=[],now=Date.now()){let s=normalizeState(raw),map=new Map((problems||[]).map(p=>[p.id,p]));for(const p of problems||[]){let x=s.cortexAccountability.find(a=>a.problemId===p.id);if(!x){x={id:`CTXACC-${p.id}`,problemId:p.id,createdAt:now,status:'AWAITING_ACTION',summary:''};s.cortexAccountability.push(x)}x.updatedAt=now;if(p.status==='SOLVED'){x.status='RESOLVED_PROVEN';x.summary=`CORTEX أغلق ${p.id} بعد أن تحول الحل إلى ${p.hypothesisId||'فرضية'} وثبت.`}else if(p.status==='HYPOTHESIS_TESTING'){x.status='HYPOTHESIS_TESTING';x.summary=`CORTEX حوّل حل ${p.id} إلى ${p.hypothesisId||'فرضية جديدة'} وهي الآن تحت الإثبات.`}else if(p.status==='SOLVING'||p.status==='NEEDS_SOLVER'){x.status='ACTION_IN_PROGRESS';x.summary=`CORTEX يتابع ${p.id} مع عامل الحلول؛ المشكلة تكررت ${p.recurrences||1} مرة.`}else{x.status='AWAITING_ACTION';x.summary=`CORTEX مطالب بإجراء واضح تجاه ${p.id}: ${p.title||p.summary||'مشكلة'}`}}s.cortexAccountability=s.cortexAccountability.slice(-500);return s}
function publicState(raw,now=Date.now()){let s=normalizeState(raw),today=dayKey(now),d=s.daily[today]||{day:today,trades:0,netUsd:0,knownUsdTrades:0,profitsUsd:0,lossesUsd:0,avoidableLosses:0,avoidableLossUsd:0,unresolvedLosses:0};let carry=s.openIssues.filter(x=>x.status==='OPEN'),todayReviews=s.reviews.filter(r=>r.day===today);return {schema:SCHEMA,goalUsd:s.goalUsd,positionNotionalUsd:s.positionNotionalUsd,today:{...d,remainingUsd:d.knownUsdTrades?Math.max(0,s.goalUsd-d.netUsd):null,reviewedTrades:todayReviews.length,openAccountability:carry.length},openIssues:s.openIssues.filter(x=>x.status==='OPEN').slice(-20).reverse(),recentReviews:s.reviews.slice(-20).reverse(),cortexAccountability:s.cortexAccountability.slice(-20).reverse(),lastReviewAt:s.lastReviewAt,principles:{moneyFirst:true,percentSecondary:true,noLookahead:true,lossesCarryAccountabilityAcrossDays:true}}}
module.exports={SCHEMA,initialState,normalizeState,auditTrade,auditCortex,publicState,dayKey};
