'use strict';
const fs=require('fs'),path=require('path');

const SCHEMA='alpha-proof-accountability/2';
const VERSION='2.0.0';
const MAX_AUDITS=160,MAX_GAPS=320,MAX_HYPOTHESES=240,MAX_ESCALATIONS=160,MAX_CORTEX_REVIEWS=160;
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const firstNum=(...xs)=>{for(const x of xs)if(x!==null&&x!==undefined&&x!==''&&Number.isFinite(Number(x)))return Number(x);return 0};
const round=(v,d=4)=>Number.isFinite(Number(v))?Number(Number(v).toFixed(d)):null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,n(v)));
const id=(prefix,seed,now)=>`${prefix}-${String(seed||'NA').replace(/[^A-Za-z0-9_.-]/g,'_')}-${Math.max(0,Math.round(n(now,Date.now()))).toString(36).toUpperCase()}`;

function initialState(){return{
 schema:SCHEMA,version:VERSION,
 accountant:{status:'READY',audits:0,enteredWins:0,enteredLosses:0,missedWins:0,avoidedLosses:0,lastAuditAt:null,tradeAudits:[],cortexAudits:[],openGaps:[],closedGaps:[]},
 solutionFinder:{status:'READY',processed:0,solved:0,escalated:0,lastRunAt:null,hypotheses:[],escalations:[]},
 cortexInbox:{status:'READY',received:0,acceptedForResearch:0,linkedToExistingEvidence:0,lastRunAt:null,pending:[],responses:[]}
}}
function normalize(raw){let b=initialState(),x=raw&&typeof raw==='object'?raw:{};let a=x.accountant&&typeof x.accountant==='object'?x.accountant:{},s=x.solutionFinder&&typeof x.solutionFinder==='object'?x.solutionFinder:{},c=x.cortexInbox&&typeof x.cortexInbox==='object'?x.cortexInbox:{};return{
 ...b,...x,schema:SCHEMA,version:VERSION,
 accountant:{...b.accountant,...a,tradeAudits:Array.isArray(a.tradeAudits)?a.tradeAudits.slice(-MAX_AUDITS):[],cortexAudits:Array.isArray(a.cortexAudits)?a.cortexAudits.slice(-MAX_CORTEX_REVIEWS):[],openGaps:Array.isArray(a.openGaps)?a.openGaps.slice(-MAX_GAPS):[],closedGaps:Array.isArray(a.closedGaps)?a.closedGaps.slice(-MAX_GAPS):[]},
 solutionFinder:{...b.solutionFinder,...s,hypotheses:Array.isArray(s.hypotheses)?s.hypotheses.slice(-MAX_HYPOTHESES):[],escalations:Array.isArray(s.escalations)?s.escalations.slice(-MAX_ESCALATIONS):[]},
 cortexInbox:{...b.cortexInbox,...c,pending:Array.isArray(c.pending)?c.pending.slice(-MAX_ESCALATIONS):[],responses:Array.isArray(c.responses)?c.responses.slice(-MAX_ESCALATIONS):[]}
}}

function journeyStats(points=[]){let rows=(Array.isArray(points)?points:[]).filter(p=>p&&Number.isFinite(Number(p.t))).sort((a,b)=>n(a.t)-n(b.t));let moves=rows.map(p=>n(p.movePct,NaN)).filter(Number.isFinite),mfe=moves.length?Math.max(...moves):null,mae=moves.length?Math.min(...moves):null,best=mfe==null?null:rows.find(p=>n(p.movePct,NaN)===mfe)||null,worst=mae==null?null:rows.find(p=>n(p.movePct,NaN)===mae)||null;
 let deterioration=rows.find((p,i)=>i>0&&(p?.flags?.risk===true||p?.flow?.eligible===false||n(p?.activity?.radarScore,100)<=45||n(p?.flow?.pressurePct,100)<=50))||null;
 let recovery=rows.find((p,i)=>i>0&&n(p.movePct,0)<0&&(p?.flow?.eligible===true&&n(p?.flow?.pressurePct,0)>=58&&n(p?.activity?.radarScore,0)>=60))||null;
 return{points:rows.length,mfePct:round(mfe,5),maePct:round(mae,5),bestAt:best?.t||null,bestMovePct:round(best?.movePct,5),worstAt:worst?.t||null,worstMovePct:round(worst?.movePct,5),deterioration:deterioration?{at:deterioration.t,movePct:round(deterioration.movePct,5),risk:!!deterioration?.flags?.risk,riskReason:deterioration?.flags?.riskReason||null,flowEligible:deterioration?.flow?.eligible??null,pressurePct:round(deterioration?.flow?.pressurePct,2),radarScore:round(deterioration?.activity?.radarScore,2)}:null,recovery:recovery?{at:recovery.t,movePct:round(recovery.movePct,5),pressurePct:round(recovery?.flow?.pressurePct,2),radarScore:round(recovery?.activity?.radarScore,2)}:null}
}
function allocationStats(input={},ai={}){let pos=input.portfolioPosition||null,portfolio=input.portfolio||{},capital=firstNum(portfolio.initialCapitalUSDT,0),hasAllocation=!!pos||input.allocatedUSDT!==undefined&&input.allocatedUSDT!==null,cost=pos?firstNum(pos.costUSDT,0)+firstNum(pos.entryFeeUSDT,0):hasAllocation?firstNum(input.allocatedUSDT,0):null,pct=hasAllocation&&capital>0?cost/capital*100:null,confidence=clamp(firstNum(ai.confidence,.5),0,1),targetNet=n(ai?.execution?.targetNetPct,NaN),positiveEdge=Number.isFinite(targetNet)&&targetNet>0;let status='UNKNOWN',note='لا توجد بيانات كافية عن حجم الدخول الفعلي.';
 if(pct!=null){status='BALANCED';note=`حجم الدخول ${round(pct,2)}% من رأس المال المرجعي.`;if(confidence<.58&&pct>5){status='TOO_LARGE_FOR_EVIDENCE';note=`الثقة ${round(confidence*100,1)}% بينما حجم الدخول ${round(pct,2)}%؛ يلزم اختبار خفض التعرض.`}else if(confidence>=.80&&positiveEdge&&pct<3){status='POSSIBLY_TOO_SMALL';note=`الثقة ${round(confidence*100,1)}% مع عائد صافي مستهدف موجب، لكن الدخول ${round(pct,2)}% فقط؛ لا تُزاد المخاطرة إلا بعد إثبات edge والمعايرة معًا.`}}
 return{capitalUSDT:round(capital,2),allocatedUSDT:round(cost,2),allocationPct:round(pct,3),confidence:round(confidence,5),targetNetPct:round(targetNet,5),positiveEdge,status,note}}
function cortexImpact(ai={},net=0){let decision=String(ai.decision||ai.finalDecision||'UNKNOWN'),base=String(ai.baselineModelDecision||decision),mentor=ai.mentor||{},baseConf=firstNum(ai.baseConfidence,ai.confidence,.5),finalConf=firstNum(ai.confidence,baseConf),delta=finalConf-baseConf,changed=base!==decision,active=!!(mentor&&((mentor.active===true)||mentor.hypothesisId||mentor.id||Math.abs(delta)>1e-9));let outcome=net>0?'WIN':'LOSS',effect='NO_CAUSAL_CHANGE',help='UNPROVEN',explain='لم يغيّر CORTEX القرار النهائي؛ لا يجوز نسب الربح أو الخسارة له سببيًا.';
 if(changed){if(base==='SKIP'&&decision==='ENTER'){help=net>0?'HELPED':'HARMED';effect='SKIP_TO_ENTER';explain=net>0?'CORTEX حوّل التجنب إلى دخول وكان صافي النتيجة موجبًا.':'CORTEX حوّل التجنب إلى دخول وانتهت النتيجة صافي خسارة.'}else if(base==='ENTER'&&decision==='SKIP'){help=net<=0?'HELPED':'HARMED';effect='ENTER_TO_SKIP';explain=net<=0?'CORTEX ساعد على تجنب خسارة افتراضية.':'CORTEX ساهم في تفويت فرصة كان صافيها موجبًا.'}}
 else if(active&&Math.abs(delta)>=.005){help=(decision==='ENTER'&&net<0&&delta>0)||(decision==='SKIP'&&net>0&&delta<0)?'CONFIDENCE_HARM':'NO_DECISION_CHANGE';explain=`CORTEX غيّر الثقة بمقدار ${round(delta*100,2)} نقطة مئوية دون تغيير القرار؛ يُحاسب أثر الثقة منفصلًا عن النتيجة.`}
 return{active,decision,baselineDecision:base,decisionChanged:changed,baseConfidence:round(baseConf,5),finalConfidence:round(finalConf,5),confidenceDelta:round(delta,5),mentorPhase:mentor?.phase||null,hypothesisId:mentor?.hypothesisId||mentor?.id||null,effect,help,outcome,explain}}
function answer(key,question,status,text,evidence=null,gapType=null,priority='MEDIUM'){return{key,question,status,text,evidence,gapType,priority}}
function gap(audit,type,question,evidence,priority='MEDIUM',requirements=[]){return{id:`GAP-${audit.id}-${type}`,auditId:audit.id,type,question,evidence:evidence||null,priority,status:'OPEN',owner:'SOLUTION_FINDER',createdAt:audit.at,requirements:Array.isArray(requirements)?requirements:[]}}

function reviewClosed(rawState,input={},now=Date.now()){
 let state=normalize(rawState),closed=input.closed||{},ai=closed.ai||input.ai||{},decision=String(ai.decision||ai.finalDecision||'UNKNOWN'),net=firstNum(closed.shadowNetPnlPct,ai?.outcome?.netPnlPct,0),gross=firstNum(closed.shadowGrossMovePct,ai?.outcome?.grossMovePct,closed.signedMovePct,0),fees=firstNum(closed.shadowFeesPct,ai?.outcome?.totalFeesPct,.2),js=journeyStats(input.journey||[]),allocation=allocationStats(input,ai),cid=String(closed.cycleId||closed.caseId||now),auditId=id('AUD',cid,now),entered=decision==='ENTER',isWin=net>0,missed=decision==='SKIP'&&net>0,avoided=decision==='SKIP'&&net<=0,profitLeft=js.mfePct==null?null:round(js.mfePct-gross,5),lossRecoverable=js.deterioration?round(n(js.deterioration.movePct)-net,5):null;
 let answers=[];
 if(entered&&!isWin){
  answers.push(answer('avoid_loss','هل كان بالإمكان تفادي الخسارة؟',js.deterioration?'EVIDENCE_FOUND':'UNRESOLVED',js.deterioration?`ظهر تدهور قابل للقياس قبل الإغلاق عند حركة ${js.deterioration.movePct}%، بينما انتهت الصفقة بصافي ${round(net,3)}%. هذا لا يثبت الفلتر بعد، لكنه يستحق اختبارًا مضادًا.`:'لا يوجد في المسار الحالي تحذير مبكر كافٍ لإثبات أن الخسارة كانت قابلة للتفادي؛ يلزم البحث في حالات مشابهة.',js.deterioration,'LOSS_AVOIDANCE','HIGH'));
  answers.push(answer('reduce_loss','هل كان بالإمكان تقليل الخسارة؟',lossRecoverable!=null&&lossRecoverable>.15?'EVIDENCE_FOUND':'UNRESOLVED',lossRecoverable!=null&&lossRecoverable>.15?`لو استُخدم التدهور المبكر كنقطة تجريبية للخروج، فالفرق النظري يقارب ${round(lossRecoverable,3)} نقطة مئوية قبل تكاليف تنفيذ إضافية. يجب اختباره مستقبلًا.`:'لم يظهر فرق قابل للقياس يكفي لاقتراح خروج أبكر بأمان.',{deterioration:js.deterioration,finalNetPct:round(net,5)},'LOSS_REDUCTION','HIGH'));
 }else if(entered&&isWin){
  answers.push(answer('avoid_loss','هل كان بالإمكان تفادي الخسارة؟','NOT_APPLICABLE','الصفقة رابحة؛ لا توجد خسارة فعلية لمحاسبة تجنبها.',null,null,'LOW'));
  answers.push(answer('reduce_loss','هل كان بالإمكان تقليل الخسارة؟','NOT_APPLICABLE','الصفقة رابحة؛ تتم المحاسبة هنا على جودة الاحتفاظ والخروج.',null,null,'LOW'));
 }
 answers.push(answer('increase_profit','هل كان بالإمكان زيادة الربح؟',profitLeft!=null&&profitLeft>.25?'EVIDENCE_FOUND':entered&&isWin?'NO_MEASURABLE_GAP':'NOT_APPLICABLE',profitLeft!=null&&profitLeft>.25?`المسار بلغ MFE ${js.mfePct}% مقابل خروج إجمالي ${round(gross,3)}%؛ توجد فجوة التقاط تقارب ${round(profitLeft,3)} نقطة مئوية تستحق اختبار سياسة خروج أفضل.`:entered&&isWin?'لم تظهر فجوة التقاط كبيرة داخل المسار المسجل؛ لا نختلق تمديد ربح بلا دليل.':'السؤال لا يطبق على دخول غير منفذ.',{mfePct:js.mfePct,exitGrossPct:round(gross,5)},profitLeft!=null&&profitLeft>.25?'PROFIT_CAPTURE':null,'MEDIUM'));
 answers.push(answer('missed_profit','هل كان بالإمكان الحصول على الربح بدلًا من تجنب الصفقة؟',missed?'MISSED_WIN':avoided?'AVOIDED_LOSS':'NOT_APPLICABLE',missed?`Trade AI اختار SKIP لكن النتيجة المقابلة بعد الرسوم كانت +${round(net,3)}%. هذه فرصة فائتة حقيقية للمراجعة، وليست دعوة لخفض العتبة مباشرة.`:avoided?`قرار SKIP تجنب نتيجة مقابلة صافيها ${round(net,3)}%؛ لا توجد فرصة ربح فائتة في هذه الحالة.`:'Trade AI دخل الصفقة؛ لا يوجد تجنب للصفقة هنا.',{decision,netPct:round(net,5),challengers:ai.challengers||null},missed?'MISSED_WIN':null,missed?'HIGH':'LOW'));
 let sizeGap=allocation.status==='TOO_LARGE_FOR_EVIDENCE'?'SIZE_TOO_LARGE':allocation.status==='POSSIBLY_TOO_SMALL'?'SIZE_TOO_SMALL':null;
 answers.push(answer('sizing','هل كان مبلغ الدخول مناسبًا للثقة؟',sizeGap?'REVIEW_REQUIRED':allocation.status==='BALANCED'?'NO_FLAG':'UNKNOWN',allocation.note,allocation,sizeGap,sizeGap?'MEDIUM':'LOW'));
 let cortex=cortexImpact(ai,net),related=(state.solutionFinder.hypotheses||[]).filter(h=>h.status!=='REJECTED'&&(h.symbol===closed.symbol||h.tf===closed.tf)).slice(-3),cortexAudit={id:id('CTX',cid,now),at:now,caseId:cid,symbol:closed.symbol||null,tf:closed.tf||null,dir:closed.dir||null,tradeNetPct:round(net,5),...cortex,whatAction:cortex.active?(cortex.decisionChanged?`تدخل CORTEX غيّر القرار: ${cortex.baselineDecision} ← ${cortex.decision}.`:`تدخل CORTEX أثّر في الثقة فقط (${round(cortex.confidenceDelta*100,2)} نقطة مئوية) دون تغيير القرار.`):'لا يوجد تدخل CORTEX نشط موثق لهذه الحالة.',didItHelp:cortex.explain,roleInConfidence:`الثقة الأساسية ${round(cortex.baseConfidence*100,1)}%، النهائية ${round(cortex.finalConfidence*100,1)}%، مساهمة CORTEX ${round(cortex.confidenceDelta*100,2)} نقطة مئوية.`,nextAction:(entered&&!isWin)?'لا تُرفع الثقة أو المخاطرة. ابحث عن إشارة سابقة للخسارة ثم اختبرها مستقبلًا قبل أي اعتماد.':missed?'افحص لماذا حُجبت الفرصة الرابحة، وقارنها بصفقات SKIP الخاسرة قبل تعديل أي عتبة.':profitLeft!=null&&profitLeft>.25?'اختبر سياسة خروج/احتفاظ تلتقط جزءًا أكبر من MFE بدون زيادة الخسائر.':'لا تغيير تلقائي؛ استمر في جمع الدليل.',solutionFinderFollowup:related.length?`يوجد ${related.length} حل/فرضية سابقة مرتبطة؛ تبقى تحت الاختبار ولا تُعتمد آليًا.`:'لا توجد فرضية سابقة مرتبطة يمكن القول إن CORTEX اتخذ إجراءً بناءً عليها بعد.'};
 let audit={id:auditId,at:now,caseId:cid,symbol:closed.symbol||null,tf:closed.tf||null,dir:closed.dir||null,result:closed.result||null,decision,classification:entered?(isWin?'ENTERED_WIN':'ENTERED_LOSS'):(decision==='SKIP'?(missed?'SKIPPED_MISSED_WIN':'SKIPPED_AVOIDED_LOSS'):'NO_AI_DECISION'),economics:{netPnlPct:round(net,5),grossMovePct:round(gross,5),feesPct:round(fees,5),mfePct:js.mfePct,maePct:js.maePct,profitCaptureGapPct:profitLeft},journey:js,allocation,answers,cortexAuditId:cortexAudit.id};
 let gaps=[];for(const a of answers)if(a.gapType&&['EVIDENCE_FOUND','UNRESOLVED','MISSED_WIN','REVIEW_REQUIRED'].includes(a.status))gaps.push(gap(audit,a.gapType,a.question,a.evidence,a.priority,['NO_LOOKAHEAD','PROSPECTIVE_PROOF','NET_AFTER_FEES']));if(['HARMED','CONFIDENCE_HARM'].includes(cortex.help))gaps.push(gap(audit,'CORTEX_HARM','ما الذي يجب أن يغيّره CORTEX بعد أن كان تدخله ضارًا؟',cortex,'HIGH',['SEPARATE_CONFIDENCE_FROM_EDGE','NO_AUTO_PROMOTION']));else if((entered&&!isWin||missed)&&!cortex.active)gaps.push(gap(audit,'CORTEX_NO_ASSIST','ما المعلومة أو الإجراء الذي كان يمكن للعقل الرئيسي تقديمه دون خداع رجعي؟',{decision,netPct:round(net,5),cortexActive:false},'MEDIUM',['COUNTERFACTUAL_ONLY','NO_LOOKAHEAD']));
 state.accountant.tradeAudits.push(audit);state.accountant.tradeAudits=state.accountant.tradeAudits.slice(-MAX_AUDITS);state.accountant.cortexAudits.push(cortexAudit);state.accountant.cortexAudits=state.accountant.cortexAudits.slice(-MAX_CORTEX_REVIEWS);let known=new Set(state.accountant.openGaps.concat(state.accountant.closedGaps).map(g=>g.id));for(const g of gaps)if(!known.has(g.id))state.accountant.openGaps.push(g);state.accountant.openGaps=state.accountant.openGaps.slice(-MAX_GAPS);state.accountant.audits++;if(entered&&isWin)state.accountant.enteredWins++;if(entered&&!isWin)state.accountant.enteredLosses++;if(missed)state.accountant.missedWins++;if(avoided)state.accountant.avoidedLosses++;state.accountant.lastAuditAt=now;state.accountant.status='ACTIVE';return{state,audit,cortexAudit,gaps};
}

function hypothesisFromGap(g,audit,now){let e=g.evidence||{},base={id:id('HYP',`${g.type}-${audit?.caseId||g.auditId}`,now),sourceGapId:g.id,sourceAuditId:g.auditId,type:g.type,symbol:audit?.symbol||null,tf:audit?.tf||null,dir:audit?.dir||null,createdAt:now,status:'CANDIDATE_FOR_CORTEX_REVIEW',kind:'POSITIVE_IMPROVEMENT',prospectiveOnly:true,autoAdopt:false,proofPolicy:'DISCOVERY_EVIDENCE_ONLY_THEN_INDEPENDENT_FUTURE_TEST',guardrails:['لا اعتماد تلقائي','لا Lookahead','تقييم صافي بعد الرسوم','لا ترفع الثقة من المعايرة وحدها']};
 if(g.type==='LOSS_AVOIDANCE'&&e?.at)return{...base,title:'بوابة تدهور قبل الاستمرار في الخسارة',hypothesis:`عندما يظهر تدهور مشابه قبل توسع الخسارة، فإن منع/تعليق الدخول أو إعادة التحقق قد يحسن صافي النتائج مقارنة بالأساس.`,evidence:[`تدهور عند حركة ${e.movePct}%`,e.riskReason?`سبب الخطر: ${e.riskReason}`:`ضغط ${e.pressurePct}% / Radar ${e.radarScore}`],experiment:'جمّد تعريف التدهور من هذه الحالة، ثم اختبره على حالات مستقبلية مستقلة وقارن صافي PnL ومعدل الفرص المقتولة.'};
 if(g.type==='LOSS_REDUCTION'&&e?.deterioration?.at)return{...base,title:'خروج/خفض تعرض عند تدهور مثبت',hypothesis:'إذا تدهورت أدلة التدفق أثناء صفقة خاسرة قبل اتساع الخسارة، فقد يقلل خفض التعرض أو الخروج المبكر متوسط الخسارة دون تدمير متوسط الربح.',evidence:[`نقطة التدهور ${e.deterioration.movePct}%`,`النهاية ${e.finalNetPct}%`],experiment:'اختبار مضاد baseline مقابل early-reduction على المستقبل؛ النجاح يتطلب تحسن expectancy وصافي PnL بعد الرسوم لا مجرد تقليل الخسارة.'};
 if(g.type==='PROFIT_CAPTURE'&&Number.isFinite(Number(e?.mfePct)))return{...base,title:'تحسين التقاط الحركة الرابحة',hypothesis:'عندما تستمر الأدلة الإيجابية بعد تحقيق ربح، قد يؤدي تأخير جزء من الخروج حتى أول تدهور موثق إلى رفع نسبة التقاط MFE مع إبقاء downside مضبوطًا.',evidence:[`MFE ${e.mfePct}%`,`الخروج الإجمالي ${e.exitGrossPct}%`],experiment:'قارن الخروج الحالي مع trailing evidence exit على عينات مستقبلية؛ راقب capture ratio، net expectancy، وtail loss.'};
 if(g.type==='MISSED_WIN'&&Number(e?.netPct)>0)return{...base,title:'استرجاع فرص SKIP الرابحة دون خفض أعمى للعتبة',hypothesis:'قد توجد شريحة من قرارات SKIP ذات edge موجب يمكن تمييزها بواسطة سياق/ميزات محددة بدل خفض عتبة Trade AI للجميع.',evidence:[`النتيجة المقابلة +${e.netPct}% بعد الرسوم`],experiment:'قارن ميزات missed-wins مع avoided-losses، استخرج قاعدة فصل صغيرة، ثم اختبرها مستقبلًا فقط.'};
 if(g.type==='SIZE_TOO_LARGE')return{...base,title:'خفض المخاطرة عندما الدليل ضعيف',hypothesis:'ربط التعرض بدليل edge الموجب + جودة المعايرة + حدود drawdown، بدل الثقة الخام وحدها، قد يخفض أثر أخطاء الثقة المنخفضة.',evidence:[`الثقة ${round(n(e.confidence)*100,1)}%`,`التعرض ${e.allocationPct}%`],experiment:'اختبار sizing policy في Shadow فقط؛ قارن max drawdown وnet expectancy مع الحجم الحالي.'};
 if(g.type==='SIZE_TOO_SMALL')return{...base,title:'اختبار زيادة التعرض المشروطة بالـedge',hypothesis:'في الحالات ذات edge موجب مثبت ومعايرة جيدة وثقة عالية، قد يرفع تعرض أكبر قليلًا العائد المعدل بالمخاطر مقارنة بالحجم الثابت.',evidence:[`الثقة ${round(n(e.confidence)*100,1)}%`,`التعرض ${e.allocationPct}%`,`target net ${e.targetNetPct}%`],experiment:'لا زيادة فعلية. شغّل محفظة Shadow موازية بأحجام طبقية ومقارنة drawdown/expectancy قبل أي اعتماد.'};
 if(g.type==='CORTEX_HARM')return{...base,title:'حجر تدخل CORTEX الضار',hypothesis:'عندما لا يملك CORTEX فرضية مثبتة لنفس السياق، فإن إبقاء تأثيره Shadow-only قد يحسن السلامة مقارنة بتعديل قرار Trade AI.',evidence:[`الأثر ${e.effect||'غير معروف'}`,`مساعدة ${e.help||'غير مثبتة'}`],experiment:'Arena زوجية: baseline vs CORTEX intervention على المستقبل، مع شرط فائدة اقتصادية لا calibration فقط.'};
 return null;
}
function solveOpen(rawState,now=Date.now()){
 let state=normalize(rawState),audits=new Map(state.accountant.tradeAudits.map(a=>[a.id,a])),processed=[];
 for(const g of [...state.accountant.openGaps]){
  if(g.status!=='OPEN')continue;
  let audit=audits.get(g.auditId),hyp=hypothesisFromGap(g,audit,now);
  if(hyp){
   let request={id:id('CTXREQ',hyp.id,now),kind:'SOLUTION_HYPOTHESIS',sourceHypothesisId:hyp.id,sourceGapId:g.id,sourceAuditId:g.auditId,type:g.type,symbol:hyp.symbol,tf:hyp.tf,dir:hyp.dir,createdAt:now,status:'PENDING_CORTEX_REVIEW',assignedTo:'OMEGA_CORTEX',title:hyp.title,hypothesis:hyp.hypothesis,evidence:hyp.evidence||[],experiment:hyp.experiment,prospectiveOnly:true,autoAdopt:false,proofPolicy:hyp.proofPolicy};
   hyp.cortexRequestId=request.id;hyp.cortexReviewStatus=request.status;
   state.solutionFinder.hypotheses.push(hyp);state.cortexInbox.pending.push(request);state.solutionFinder.solved++;state.cortexInbox.received++;
   g.status='SOLVED_AS_CANDIDATE';g.resolutionId=hyp.id;g.resolvedAt=now;processed.push({gap:g,hypothesis:hyp,cortexRequest:request});
  }else{
   let esc={id:id('ESC',g.id,now),kind:'UNRESOLVED_ESCALATION',sourceGapId:g.id,sourceAuditId:g.auditId,type:g.type,symbol:audit?.symbol||null,tf:audit?.tf||null,dir:audit?.dir||null,createdAt:now,status:'PENDING_CORTEX',assignedTo:'OMEGA_CORTEX',question:g.question,whyEscalated:'عامل إيجاد الحلول لم يجد دليلاً كافيًا لصياغة فرضية قابلة للاختبار دون اختلاق.',missingEvidence:g.requirements||[],context:g.evidence||null,prospectiveOnly:true,autoAdopt:false};
   state.solutionFinder.escalations.push(esc);state.cortexInbox.pending.push(esc);state.solutionFinder.escalated++;state.cortexInbox.received++;
   g.status='ESCALATED_TO_CORTEX';g.resolutionId=esc.id;g.resolvedAt=now;processed.push({gap:g,escalation:esc});
  }
  state.solutionFinder.processed++;
 }
 let done=state.accountant.openGaps.filter(g=>g.status!=='OPEN'),open=state.accountant.openGaps.filter(g=>g.status==='OPEN');
 state.accountant.closedGaps=state.accountant.closedGaps.concat(done).slice(-MAX_GAPS);state.accountant.openGaps=open.slice(-MAX_GAPS);state.solutionFinder.hypotheses=state.solutionFinder.hypotheses.slice(-MAX_HYPOTHESES);state.solutionFinder.escalations=state.solutionFinder.escalations.slice(-MAX_ESCALATIONS);state.cortexInbox.pending=state.cortexInbox.pending.slice(-MAX_ESCALATIONS);state.solutionFinder.lastRunAt=now;state.solutionFinder.status=processed.length?'ACTIVE':'READY';return{state,processed};
}
function contextMatchEdge(edge,request){let c=String(edge?.context||'').toUpperCase(),dir=String(request?.dir||'').toUpperCase(),tf=String(request?.tf||'').toUpperCase();if(!c)return false;return(!dir||c.includes(dir)||c.includes('ALL')||c.includes('GLOBAL'))&&(!tf||c.includes(tf)||c.includes('ALL')||c.includes('GLOBAL'))}
function runCortexInbox(rawState,cortexPublic={},now=Date.now()){
 let state=normalize(rawState),responses=[];
 for(const request of [...state.cortexInbox.pending]){
  if(!['PENDING_CORTEX','PENDING_CORTEX_REVIEW'].includes(request.status))continue;
  let pool=[...(cortexPublic.validated||[]),...(cortexPublic.candidates||[])],edge=pool.find(x=>contextMatchEdge(x,request))||null,isHyp=request.kind==='SOLUTION_HYPOTHESIS';
  let status=edge?'LINKED_TO_EXISTING_EVIDENCE':isHyp?'ACCEPTED_FOR_PROSPECTIVE_STUDY':'ACCEPTED_FOR_RESEARCH';
  let response={id:id('CTXRESP',request.id,now),requestId:request.id,escalationId:isHyp?null:request.id,hypothesisId:isHyp?request.sourceHypothesisId:null,kind:request.kind||'UNRESOLVED_ESCALATION',at:now,assignedTo:'OMEGA_CORTEX',status,sourceEdgeId:edge?.id||null,
   answer:edge?(isHyp?`استلم Ω CORTEX الفرضية المرشحة وربطها بدليل بحثي قريب (${edge.id}). هذا الربط لا يثبتها ولا يعتمدها؛ تبدأ مراجعة مستقلة على المستقبل.`:`وجد Ω CORTEX دليلاً بحثيًا ذا سياق قريب (${edge.id}). لا يعتمد كحل؛ يُحوّل إلى اختبار ربط مستقل مع مشكلة ${request.type}.`):(isHyp?`استلم Ω CORTEX الفرضية «${request.title||request.type}» كطلب دراسة وتدقيق. لا يوجد دليل مثبت يجيز اعتمادها الآن؛ تبقى Prospective-only حتى تنجح باختبار مستقل.`:`استلم Ω CORTEX المشكلة ${request.type}. لا يوجد حاليًا دليل مثبت كافٍ لإجابة آمنة؛ تُسجل كمسألة بحث بدل اختراع حل رجعي.`),
   next:edge?'اختبار ما إذا كان الدليل الحالي يفسر الفجوة اقتصاديًا على المستقبل المستقل، مع مقارنة baseline مضبوطة.':isHyp?'تجميد الفرضية وتجربتها عبر المقارنة بين الحالات + العزل + التجربة المضادة ثم Statistical Firewall قبل أي ترقية.':'استخدام المقارنة بين الحالات + العزل + التجربة المضادة لاشتقاق فرضية إيجابية قابلة للاختبار.',autoAdopt:false,prospectiveOnly:true};
  state.cortexInbox.responses.push(response);responses.push(response);request.status=response.status;request.respondedAt=now;request.responseId=response.id;if(edge)state.cortexInbox.linkedToExistingEvidence++;else state.cortexInbox.acceptedForResearch++;
 }
 let handled=new Set(responses.map(r=>r.requestId));state.cortexInbox.pending=state.cortexInbox.pending.filter(x=>!handled.has(x.id));
 for(const e of state.solutionFinder.escalations){let r=responses.find(x=>x.requestId===e.id);if(r){e.status=r.status;e.respondedAt=r.at;e.responseId=r.id;e.sourceEdgeId=r.sourceEdgeId||null;}}
 for(const h of state.solutionFinder.hypotheses){let r=responses.find(x=>x.hypothesisId===h.id);if(r){h.cortexReviewStatus=r.status;h.cortexRespondedAt=r.at;h.cortexResponseId=r.id;h.sourceEdgeId=r.sourceEdgeId||null;}}
 state.cortexInbox.responses=state.cortexInbox.responses.slice(-MAX_ESCALATIONS);state.cortexInbox.lastRunAt=now;state.cortexInbox.status=responses.length?'ACTIVE':'READY';return{state,responses};
}

function createLedger({dataDir}){let dir=path.join(dataDir,'accountability'),events=path.join(dir,'events.jsonl');fs.mkdirSync(dir,{recursive:true});return{dir,events,append(rows){try{for(const r of (Array.isArray(rows)?rows:[rows]).filter(Boolean))fs.appendFileSync(events,JSON.stringify(r)+'\n');return true}catch(e){console.error('accountability ledger',e.message);return false}},status(){let bytes=0;try{bytes=fs.statSync(events).size}catch{}return{schema:'alpha-proof-accountability-ledger/1',appendOnly:true,file:path.basename(events),bytes}}}}
function publicState(rawState){let s=normalize(rawState);return{schema:SCHEMA,version:VERSION,principles:{noAutoAdoption:true,prospectiveProof:true,noLookahead:true,netAfterFees:true,confidenceNotEdge:true},accountant:{status:s.accountant.status,audits:s.accountant.audits,enteredWins:s.accountant.enteredWins,enteredLosses:s.accountant.enteredLosses,missedWins:s.accountant.missedWins,avoidedLosses:s.accountant.avoidedLosses,lastAuditAt:s.accountant.lastAuditAt,openGaps:s.accountant.openGaps.length,recentTradeAudits:s.accountant.tradeAudits.slice(-24).reverse(),recentCortexAudits:s.accountant.cortexAudits.slice(-24).reverse()},solutionFinder:{status:s.solutionFinder.status,processed:s.solutionFinder.processed,solved:s.solutionFinder.solved,escalated:s.solutionFinder.escalated,lastRunAt:s.solutionFinder.lastRunAt,recentHypotheses:s.solutionFinder.hypotheses.slice(-24).reverse(),recentEscalations:s.solutionFinder.escalations.slice(-24).reverse()},cortexInbox:{status:s.cortexInbox.status,received:s.cortexInbox.received,acceptedForResearch:s.cortexInbox.acceptedForResearch,linkedToExistingEvidence:s.cortexInbox.linkedToExistingEvidence,lastRunAt:s.cortexInbox.lastRunAt,pending:s.cortexInbox.pending.slice(-20).reverse(),recentResponses:s.cortexInbox.responses.slice(-20).reverse()}}}
module.exports={SCHEMA,VERSION,initialState,normalize,journeyStats,allocationStats,cortexImpact,reviewClosed,solveOpen,runCortexInbox,createLedger,publicState};
