'use strict';
// Shadow-only adaptive trade manager. No fixed TP/SL and no real orders.
const SCHEMA='alpha-proof-adaptive-manager/1',MODEL_VERSION='ADAPTIVE-MANAGER-001',FEATURE_SCHEMA='MANAGEMENT-V1';
const FEATURES=['net','giveback','flowRelative','pressure','persistence','speed','acceleration','radar','age','entryConfidence'];
const OBS_RAM_MAX=20,DECISION_RAM_MAX=24,CLOSED_RAM_MAX=120,RECENT_RAM_MAX=120;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,Number.isFinite(Number(x))?Number(x):0));
const sigmoid=z=>1/(1+Math.exp(-clamp(z,-12,12)));
const round=(x,d=5)=>Number.isFinite(Number(x))?Number(Number(x).toFixed(d)):null;
function initialState(now=Date.now()){return {schema:SCHEMA,modelVersion:MODEL_VERSION,featureSchema:FEATURE_SCHEMA,startedAt:now,samples:0,bias:0,weights:Object.fromEntries(FEATURES.map(k=>[k,0])),positions:{},closed:[],recent:[],lastTrainedAt:null}}
function normalizeState(raw={},now=Date.now()){let b=initialState(now),s={...b,...(raw||{})};s.schema=SCHEMA;s.modelVersion=MODEL_VERSION;s.featureSchema=FEATURE_SCHEMA;s.samples=Math.max(0,Number(s.samples)||0);s.bias=Number(s.bias)||0;s.weights={...b.weights,...(s.weights||{})};s.positions=s.positions&&typeof s.positions==='object'?s.positions:{};s.closed=Array.isArray(s.closed)?s.closed.slice(-CLOSED_RAM_MAX):[];s.recent=Array.isArray(s.recent)?s.recent.slice(-RECENT_RAM_MAX):[];for(const p of Object.values(s.positions)){if(!p||typeof p!=='object')continue;p.observations=Array.isArray(p.observations)?p.observations.slice(-OBS_RAM_MAX):[];p.pending=Array.isArray(p.pending)?p.pending.slice(-13):[];p.decisions=Array.isArray(p.decisions)?p.decisions.slice(-DECISION_RAM_MAX):[]}return s}
function gross(dir,entry,price){return (dir==='SHORT'?-1:1)*(Number(price)/Number(entry)-1)*100}
function features(pos,w,price,now){let g=gross(pos.dir,pos.entryPrice,price),net=g-.20,peak=Math.max(Number(pos.peakNetPct??net),net),f=w?.flow||{};return {net:clamp(net/5,-1,1),giveback:clamp((peak-net)/5,0,1),flowRelative:clamp((Number(f.relative)||0)/5,0,1),pressure:clamp(((Number(f.pressure)||50)-50)/50,-1,1),persistence:clamp((Number(f.persistence)||0)/100,0,1),speed:clamp((Number(f.speed)||0)/2,-1,1),acceleration:clamp((Number(f.acceleration)||0)/.5,-1,1),radar:clamp((Number(w?.radarScore)||0)/100,0,1),age:clamp((now-pos.entryAt)/(24*3600000),0,1),entryConfidence:clamp(Number(pos.entryConfidence)||0,0,1)}}
function probability(s,x){let z=s.bias;for(const k of FEATURES)z+=(Number(s.weights[k])||0)*(Number(x[k])||0);return sigmoid(z)}
function train(s,x,y,weight=1){let p=probability(s,x),err=(y-p)*clamp(weight,.25,4),lr=.035/Math.sqrt(1+s.samples/250);s.bias=clamp(s.bias+lr*err,-6,6);for(const k of FEATURES)s.weights[k]=clamp((Number(s.weights[k])||0)+lr*err*(Number(x[k])||0),-6,6);s.samples++;s.lastTrainedAt=Date.now();return p}
function open(state,shadow,w,now=Date.now()){state=normalizeState(state,now);let freeDecision=shadow?.modelDecision||shadow?.finalDecision,entry=Number(shadow?.fillPrice??w?.livePrice??w?.lastPrice??w?.entryPrice);if(!shadow||freeDecision!=='ENTER'||!w?.cycleId||state.positions[w.cycleId]||!Number.isFinite(entry)||entry<=0)return state;state.positions[w.cycleId]={id:w.cycleId,symbol:w.symbol,dir:w.dir,tf:w.tf,entryAt:now,entryPrice:entry,entryConfidence:Number(shadow.confidence??shadow.baseConfidence)||0,entryMode:'FREE_MODEL',baselineDecision:shadow.finalDecision||null,baselineDecisionReason:shadow.decisionReason||null,status:'OPEN',peakNetPct:-Infinity,lastPrice:entry,observations:[],pending:[],decisions:[]};return state}
function observe(state,w,price,now=Date.now()){state=normalizeState(state,now);let id=w?.cycleId,pos=state.positions[id];if(!pos||pos.status!=='OPEN'||!Number.isFinite(Number(price)))return {state,action:null};let g=gross(pos.dir,pos.entryPrice,price),net=g-.20;pos.peakNetPct=Math.max(Number.isFinite(pos.peakNetPct)?pos.peakNetPct:net,net);let x=features(pos,w,price,now),pExit=probability(state,x),action=state.samples>=40&&pExit>=.62?'EXIT':'HOLD';let obs={t:now,price:Number(price),netPct:round(net),x,pExit:round(pExit),action};pos.observations.push(obs);pos.observations=pos.observations.slice(-OBS_RAM_MAX);pos.pending.push(obs);
 // Prospective decisions; labels mature only after 12 later observations. No future data enters the original decision.
 while(pos.pending.length>12){let old=pos.pending.shift(),future=pos.observations.filter(z=>z.t>old.t).slice(0,12);if(future.length<12){pos.pending.unshift(old);break}let bestFuture=Math.max(...future.map(z=>Number(z.netPct))),y=Number(old.netPct)>=bestFuture?1:0;train(state,old.x,y,Math.min(3,.5+Math.abs(Number(old.netPct)-bestFuture)));}
 pos.lastPrice=Number(price);pos.lastAt=now;pos.lastContext={radarScore:Number(w?.radarScore)||0,flow:w?.flow?{relative:Number(w.flow.relative)||0,pressure:Number(w.flow.pressure)||50,persistence:Number(w.flow.persistence)||0,speed:Number(w.flow.speed)||0,acceleration:Number(w.flow.acceleration)||0}:null};pos.decisions.push({t:now,action,pExit:round(pExit),price:Number(price),netPct:round(net)});pos.decisions=pos.decisions.slice(-DECISION_RAM_MAX);state.recent.push({t:now,id,symbol:pos.symbol,action,pExit:round(pExit),price:Number(price),netPct:round(net),samples:state.samples});state.recent=state.recent.slice(-RECENT_RAM_MAX);
 if(action==='EXIT'){pos.status='CLOSED';pos.exitAt=now;pos.exitPrice=Number(price);pos.netPnlPct=round(net);pos.reason='AI_EXIT';state.closed.push({...pos,observations:undefined,pending:undefined});state.closed=state.closed.slice(-CLOSED_RAM_MAX);delete state.positions[id];return {state,action:'EXIT',position:pos}}
 return {state,action:'HOLD',position:pos}}
function noteBaseline(state,id,reason,price,now=Date.now()){state=normalizeState(state,now);let p=state.positions[id];if(p){p.baseline=p.baseline||{at:now,reason,price:Number(price),netPnlPct:round(gross(p.dir,p.entryPrice,price)-.20)}}return state}

function compactForPersistence(state){
 state=normalizeState(state);
 let positions={};
 for(const [id,p] of Object.entries(state.positions||{}))positions[id]={...p,observations:(p.observations||[]).slice(-OBS_RAM_MAX),pending:(p.pending||[]).slice(-13),decisions:(p.decisions||[]).slice(-DECISION_RAM_MAX)};
 return {...state,positions,closed:(state.closed||[]).slice(-CLOSED_RAM_MAX).map(p=>({...p,observations:undefined,pending:undefined,decisions:Array.isArray(p.decisions)?p.decisions.slice(-12):[]})),recent:(state.recent||[]).slice(-RECENT_RAM_MAX)}
}
function publicState(state){state=normalizeState(state);return {schema:SCHEMA,modelVersion:MODEL_VERSION,featureSchema:FEATURE_SCHEMA,mode:'SHADOW_ONLY',samples:state.samples,weights:state.weights,bias:state.bias,open:Object.values(state.positions).map(p=>({id:p.id,symbol:p.symbol,dir:p.dir,tf:p.tf,entryAt:p.entryAt,entryPrice:p.entryPrice,entryMode:p.entryMode||'FREE_MODEL',baselineDecision:p.baselineDecision||null,baselineDecisionReason:p.baselineDecisionReason||null,lastPrice:p.lastPrice,peakNetPct:round(p.peakNetPct),lastDecision:p.decisions?.at(-1)||null,baseline:p.baseline||null})),closed:state.closed.slice(-40).reverse(),recent:state.recent.slice(-60).reverse(),feePolicy:'SPOT_NO_BNB',roundTripFeePct:.20,integrity:'PROSPECTIVE_DECISIONS_FUTURE_LABELS_ONLY'}}
module.exports={SCHEMA,MODEL_VERSION,FEATURE_SCHEMA,FEATURES,OBS_RAM_MAX,DECISION_RAM_MAX,CLOSED_RAM_MAX,RECENT_RAM_MAX,initialState,normalizeState,open,observe,noteBaseline,compactForPersistence,publicState};
