'use strict';
const SCHEMA='alpha-proof-shadow-ai/2';
const MODEL_VERSION='SHADOW-AI-005-NET-PNL';
const FEATURE_SCHEMA='FEATURES-V3-ECONOMICS';
const ECONOMICS_SCHEMA='alpha-proof-trade-economics/1';
const REPAIR_VERSION='NET-PNL-INTEGRITY-2026-09-06-R2';
const PRIMARY_THRESHOLD=.60;
// Conservative Spot fee policy requested by the project owner: no BNB discount.
const SPOT_ENTRY_FEE_PCT=.10;
const SPOT_EXIT_FEE_PCT=.10;
const SPOT_ROUND_TRIP_FEE_PCT=.20;
const DAY_HISTORY_MAX=120;
const ECONOMIC_SOFT_TARGET_SCALE_PCT=1.0;
const ECONOMIC_WEIGHT_BASE_PCT=.25;
const FEATURE_NAMES=['score','relative','pressure','persistence','impact','move','speed','acceleration','market','fearGreed','marketForecast','marketForecastConfidence','marketTurning','marketAgreement','pa','ce','ema','timeframe','dirShort','net24h','dayVsHistory','profitBalance24h'];
const clamp=(x,a,b)=>Math.max(a,Math.min(b,Number.isFinite(Number(x))?Number(x):0));
const sigmoid=z=>1/(1+Math.exp(-clamp(z,-12,12)));
const tfMin=tf=>({"5m":5,"15m":15,"30m":30,"1h":60,"4h":240,"6h":360,"12h":720,"1d":1440}[String(tf||'').toLowerCase()]||60);
const round=(v,d=5)=>Number.isFinite(Number(v))?Number(Number(v).toFixed(d)):null;
const blankRelation=()=>({cases:0,wins:0,losses:0});
const blankMarketRelations=()=>({current:{WITH:blankRelation(),COUNTER:blankRelation(),NEUTRAL:blankRelation()},forecast60:{WITH:blankRelation(),COUNTER:blankRelation(),NEUTRAL:blankRelation()},turning:{WITH:blankRelation(),COUNTER:blankRelation(),NEUTRAL:blankRelation()}});
function relationDirection(dir){return dir==='UP'?1:dir==='DOWN'?-1:0}
function tradeRelation(tradeDir,marketDir){let t=tradeDir==='SHORT'?-1:1,m=relationDirection(marketDir);return !m?'NEUTRAL':t===m?'WITH':'COUNTER'}
function normalizeMarketRelations(raw={}){let b=blankMarketRelations(),out={};for(const group of Object.keys(b)){out[group]={};for(const key of Object.keys(b[group])){let r=raw?.[group]?.[key]||{};out[group][key]={cases:Math.max(0,Math.round(Number(r.cases)||0)),wins:Math.max(0,Math.round(Number(r.wins)||0)),losses:Math.max(0,Math.round(Number(r.losses)||0))}}}return out}
function bumpRelation(rel,group,key,win){let r=rel[group][key];r.cases++;if(win)r.wins++;else r.losses++}
function newLineage(now=Date.now()){return `AI-${Math.round(now).toString(36).toUpperCase()}`}
function riyadhDayKey(now=Date.now()){return new Date(Number(now)+3*60*60*1000).toISOString().slice(0,10)}
function blankDay(day){return {day,trades:0,wins:0,losses:0,grossMarketPct:0,profitPct:0,lossPct:0,feesPct:0,netPct:0,bestTradePct:null,worstTradePct:null,lastAt:null}}
function normalizeDay(raw={}){let d=blankDay(String(raw.day||''));d={...d,...raw,day:String(raw.day||'')};for(const k of ['trades','wins','losses'])d[k]=Math.max(0,Math.round(Number(d[k])||0));for(const k of ['grossMarketPct','profitPct','lossPct','feesPct','netPct'])d[k]=Number.isFinite(Number(d[k]))?Number(d[k]):0;d.bestTradePct=Number.isFinite(Number(d.bestTradePct))?Number(d.bestTradePct):null;d.worstTradePct=Number.isFinite(Number(d.worstTradePct))?Number(d.worstTradePct):null;d.lastAt=Number.isFinite(Number(d.lastAt))?Number(d.lastAt):null;return d}
function blankLifetime(){return {trades:0,wins:0,losses:0,grossMarketPct:0,profitPct:0,lossPct:0,feesPct:0,netPct:0,bestTradePct:null,worstTradePct:null}}
function normalizeLifetime(raw={}){let x={...blankLifetime(),...(raw||{})};for(const k of ['trades','wins','losses'])x[k]=Math.max(0,Math.round(Number(x[k])||0));for(const k of ['grossMarketPct','profitPct','lossPct','feesPct','netPct'])x[k]=Number.isFinite(Number(x[k]))?Number(x[k]):0;x.bestTradePct=Number.isFinite(Number(x.bestTradePct))?Number(x.bestTradePct):null;x.worstTradePct=Number.isFinite(Number(x.worstTradePct))?Number(x.worstTradePct):null;return x}
function blankEconomics(){return {schema:ECONOMICS_SCHEMA,feePolicy:'SPOT_NO_BNB',entryFeePct:SPOT_ENTRY_FEE_PCT,exitFeePct:SPOT_EXIT_FEE_PCT,roundTripFeePct:SPOT_ROUND_TRIP_FEE_PCT,timezone:'Asia/Riyadh',lifetime:blankLifetime(),days:[],lastUpdatedAt:null}}
function normalizeEconomics(raw={}){let e={...blankEconomics(),...(raw&&typeof raw==='object'?raw:{})};e.schema=ECONOMICS_SCHEMA;e.feePolicy='SPOT_NO_BNB';e.entryFeePct=SPOT_ENTRY_FEE_PCT;e.exitFeePct=SPOT_EXIT_FEE_PCT;e.roundTripFeePct=SPOT_ROUND_TRIP_FEE_PCT;e.timezone='Asia/Riyadh';e.lifetime=normalizeLifetime(e.lifetime);e.days=(Array.isArray(e.days)?e.days:[]).map(normalizeDay).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x.day)).sort((a,b)=>a.day.localeCompare(b.day)).slice(-DAY_HISTORY_MAX);e.lastUpdatedAt=Number.isFinite(Number(e.lastUpdatedAt))?Number(e.lastUpdatedAt):null;return e}
function summarizeBucket(x){if(!x)return null;let d=normalizeDay(x),wr=d.trades?d.wins/d.trades*100:null,pf=d.lossPct>0?d.profitPct/d.lossPct:(d.profitPct>0?Infinity:null);return {...d,winRate:round(wr,2),avgNetPct:d.trades?round(d.netPct/d.trades,5):null,profitFactor:Number.isFinite(pf)?round(pf,4):(pf===Infinity?'∞':null)}}
function summarizeLifetime(x){let d=normalizeLifetime(x),wr=d.trades?d.wins/d.trades*100:null,pf=d.lossPct>0?d.profitPct/d.lossPct:(d.profitPct>0?Infinity:null);return {...d,winRate:round(wr,2),avgNetPct:d.trades?round(d.netPct/d.trades,5):null,profitFactor:Number.isFinite(pf)?round(pf,4):(pf===Infinity?'∞':null)}}
function portfolioContext(rawState,now=Date.now()){
 let e=normalizeEconomics(rawState?.economics||rawState),key=riyadhDayKey(now),today=e.days.find(x=>x.day===key)||blankDay(key),prior=e.days.filter(x=>x.day<key),prev=prior.at(-1)||null,last7=prior.slice(-7),avgPrev=last7.length?last7.reduce((s,x)=>s+x.netPct,0)/last7.length:null,balance=(today.profitPct+today.lossPct)>0?(today.profitPct-today.lossPct)/(today.profitPct+today.lossPct):0;
 return {day:key,netPct:round(today.netPct,5),profitPct:round(today.profitPct,5),lossPct:round(today.lossPct,5),feesPct:round(today.feesPct,5),trades:today.trades,wins:today.wins,losses:today.losses,profitBalance:round(balance,5),previousDayNetPct:prev?round(prev.netPct,5):null,averagePrevious7NetPct:avgPrev==null?null:round(avgPrev,5),deltaVsPreviousDay:prev&&today.trades?round(today.netPct-prev.netPct,5):null,deltaVsAverage7:avgPrev!=null&&today.trades?round(today.netPct-avgPrev,5):null};
}
function economicsFeatureValues(pc={}){return {net24h:clamp(Number(pc.netPct||0)/5,-1,1),dayVsHistory:clamp(Number(pc.deltaVsAverage7||0)/5,-1,1),profitBalance24h:clamp(Number(pc.profitBalance||0),-1,1)}}
function economicsPublic(rawState,now=Date.now()){
 let e=normalizeEconomics(rawState?.economics||rawState),ctx=portfolioContext({economics:e},now),key=ctx.day,today=e.days.find(x=>x.day===key)||blankDay(key),prior=e.days.filter(x=>x.day<key),previous=prior.at(-1)||null,last7=prior.slice(-7),avg7=last7.length?last7.reduce((s,x)=>s+x.netPct,0)/last7.length:null,best=prior.length?[...prior].sort((a,b)=>b.netPct-a.netPct)[0]:null,worst=prior.length?[...prior].sort((a,b)=>a.netPct-b.netPct)[0]:null;
 return {schema:ECONOMICS_SCHEMA,feePolicy:e.feePolicy,entryFeePct:e.entryFeePct,exitFeePct:e.exitFeePct,roundTripFeePct:e.roundTripFeePct,timezone:e.timezone,today:summarizeBucket(today),previousDay:summarizeBucket(previous),averagePrevious7NetPct:avg7==null?null:round(avg7,5),deltaVsPreviousDay:ctx.deltaVsPreviousDay,deltaVsAverage7:ctx.deltaVsAverage7,bestPreviousDay:summarizeBucket(best),worstPreviousDay:summarizeBucket(worst),lifetime:summarizeLifetime(e.lifetime),days:e.days.slice(-14).reverse().map(summarizeBucket),lastUpdatedAt:e.lastUpdatedAt};
}
function updatePnlBucket(x,gross,net,fees,now){x.trades++;if(net>0){x.wins++;x.profitPct+=net}else{x.losses++;x.lossPct+=Math.abs(net)}x.grossMarketPct+=gross;x.feesPct+=fees;x.netPct=x.profitPct-x.lossPct;x.bestTradePct=x.bestTradePct==null?net:Math.max(x.bestTradePct,net);x.worstTradePct=x.worstTradePct==null?net:Math.min(x.worstTradePct,net);if('lastAt' in x)x.lastAt=now;return x}
function recordEconomicTrade(state,shadow,outcome,now=Date.now()){
 if(!shadow||shadow.finalDecision!=='ENTER'||!outcome||outcome.executionValid===false)return state;
 let e=normalizeEconomics(state.economics),gross=Number(outcome.grossMovePct),net=Number(outcome.netPnlPct),fees=Number(outcome.totalFeesPct);if(![gross,net,fees].every(Number.isFinite))return state;
 let key=riyadhDayKey(now),idx=e.days.findIndex(x=>x.day===key),day=idx>=0?e.days[idx]:blankDay(key);updatePnlBucket(day,gross,net,fees,now);if(idx>=0)e.days[idx]=day;else e.days.push(day);e.days=e.days.sort((a,b)=>a.day.localeCompare(b.day)).slice(-DAY_HISTORY_MAX);updatePnlBucket(e.lifetime,gross,net,fees,now);e.lastUpdatedAt=now;state.economics=e;return state;
}
function initialState(now=Date.now()){
 const weights=Object.fromEntries(FEATURE_NAMES.map(k=>[k,0]));
 return {schema:SCHEMA,featureSchema:FEATURE_SCHEMA,mode:'SHADOW',modelVersion:MODEL_VERSION,lineageId:newLineage(now),startedAt:now,threshold:PRIMARY_THRESHOLD,repairVersion:null,modelSamples:0,decisions:0,entered:0,skipped:0,economicSkips:0,invalidExecution:0,resolved:0,wins:0,losses:0,missedWins:0,avoidedLosses:0,correct:0,brierSum:0,bias:0,weights,challengers:{},marketRelations:blankMarketRelations(),economics:blankEconomics(),recent:[],trainedCaseIdsRecent:[],lastTrainedAt:null};
}
function normalizeState(raw={},now=Date.now()){
 let base=initialState(now),s={...base,...(raw&&typeof raw==='object'?raw:{})};
 s.schema=SCHEMA;s.featureSchema=FEATURE_SCHEMA;s.mode='SHADOW';s.modelVersion=MODEL_VERSION;s.threshold=PRIMARY_THRESHOLD;
 s.lineageId=String(s.lineageId||base.lineageId);s.weights={...base.weights,...(s.weights||{})};
 for(const k of ['modelSamples','decisions','entered','skipped','economicSkips','invalidExecution','resolved','wins','losses','missedWins','avoidedLosses','correct','brierSum','bias'])s[k]=Number.isFinite(Number(s[k]))?Number(s[k]):0;
 s.startedAt=Number.isFinite(Number(s.startedAt))?Number(s.startedAt):now;s.lastTrainedAt=Number.isFinite(Number(s.lastTrainedAt))?Number(s.lastTrainedAt):null;s.repairVersion=s.repairVersion?String(s.repairVersion):null;
 s.economics=normalizeEconomics(s.economics);s.recent=Array.isArray(s.recent)?s.recent.slice(-80):[];s.challengers=s.challengers&&typeof s.challengers==='object'?s.challengers:{};s.marketRelations=normalizeMarketRelations(s.marketRelations);s.trainedCaseIdsRecent=Array.isArray(s.trainedCaseIdsRecent)?s.trainedCaseIdsRecent.map(String).slice(-512):[];
 return s;
}
function extractFeatures(w={},market={}){
 const f=w.flow||{},support=w.support||w.supportAtEntry||{},fg=Number(market?.fearGreed?.value),up=Number(market?.upPct),down=Number(market?.downPct),dir=w.dir==='SHORT'?'SHORT':'LONG',sgn=dir==='SHORT'?-1:1,mai=market?.marketAI||{},mf=mai?.forecast60||{},ready=mf?.ready===true||Number(mf?.samples)>=50,mfDir=ready?relationDirection(mf?.direction):0,curDir=relationDirection(market?.direction),regime=String(mai?.regime||''),turnDir=regime==='TURNING_UP'?1:regime==='TURNING_DOWN'?-1:0,mfConf=ready?clamp((Number(mf?.confidence||0)-1/3)/(2/3),0,1):0,pc=w.aiPortfolioContext||{};
 const supportVal=x=>!x||x.enabled===false?0:x.pass===true?1:x.pass===false?-1:0;
 return {score:clamp((Number(w.radarScore??f.score??50)-50)/50,-1,1),relative:clamp((Number(f.relative??1)-1)/4,-1,1),pressure:clamp((Number(f.pressure??50)-50)/25,-1,1),persistence:clamp((Number(f.persistence??50)-50)/50,-1,1),impact:clamp(Number(f.impact??0)/5,-1,1),move:clamp(Number(f.move??0)/3,-1,1),speed:clamp(Number(f.speed??0)/1.5,-1,1),acceleration:clamp(Number(f.acceleration??0)/.15,-1,1),market:Number.isFinite(up)&&Number.isFinite(down)?clamp(sgn*(up-down)/100,-1,1):0,fearGreed:Number.isFinite(fg)?clamp(sgn*(fg-50)/50,-1,1):0,marketForecast:ready?sgn*mfDir*mfConf:0,marketForecastConfidence:mfConf,marketTurning:sgn*turnDir,marketAgreement:ready&&curDir&&mfDir?(sgn===curDir&&sgn===mfDir?1:sgn!==curDir&&sgn!==mfDir?-1:0):0,pa:supportVal(support.pa),ce:supportVal(support.ce),ema:supportVal(support.ema),timeframe:clamp(Math.log(tfMin(w.tf)/5+1)/Math.log(1440/5+1),0,1),dirShort:dir==='SHORT'?1:-1,...economicsFeatureValues(pc)};
}
function decisionFacts(w={},market={},price=null){let f=w.flow||{},s=w.support||w.supportAtEntry||{};return {symbol:w.symbol||null,dir:w.dir||null,tf:w.tf||null,price:round(price??w.livePrice??w.lastPrice??w.entryPrice,10),entryPrice:round(w.entryPrice,10),targetPrice:round(w.targetPrice,10),stopPrice:round(w.stopPrice,10),radarScore:round(w.radarScore??f.score,4),portfolio:w.aiPortfolioContext?{...w.aiPortfolioContext}:null,flow:{minutes:f.minutes??null,volume:round(f.volume,2),directionalVolume:round(f.directionalVolume,2),net:round(f.net,2),relative:round(f.relative,5),pressure:round(f.pressure,5),persistence:round(f.persistence,5),impact:round(f.impact,5),move:round(f.move,5),speed:round(f.speed,6),acceleration:round(f.acceleration,7),score:round(f.score,4),eligible:!!f.eligible,alive:f.alive!==false,measuredAt:f.measuredAt??null},market:{direction:market?.direction||null,upPct:round(market?.upPct,4),downPct:round(market?.downPct,4),medianChangePct:round(market?.medianChangePct,5),fearGreed:Number.isFinite(Number(market?.fearGreed?.value))?Number(market.fearGreed.value):null,observedAt:market?.updatedAt||market?.observedAt||null,relation:tradeRelation(w.dir,market?.direction),marketAI:market?.marketAI?{regime:market.marketAI.regime||null,currentDirection:market.marketAI.currentDirection||null,featureSchema:market.marketAI.featureSchema||null,modelVersion:market.marketAI.modelVersion||null,forecast60:market.marketAI.forecast60?{direction:market.marketAI.forecast60.direction||null,confidence:round(market.marketAI.forecast60.confidence,5),ready:!!market.marketAI.forecast60.ready,samples:Number(market.marketAI.forecast60.samples)||0,relation:market.marketAI.forecast60.ready?tradeRelation(w.dir,market.marketAI.forecast60.direction):'NEUTRAL'}:null}:null},support:{pa:s.pa?{enabled:s.pa.enabled!==false,pass:s.pa.pass??null}:null,ce:s.ce?{enabled:s.ce.enabled!==false,pass:s.ce.pass??null,ratio:round(s.ce.ratio,5)}:null,ema:s.ema?{enabled:s.ema.enabled!==false,pass:s.ema.pass??null,dist:round(s.ema.dist??s.ema.distPct,5),slope:round(s.ema.slope,6)}:null}}}
const SEED={score:1.25,relative:.75,pressure:.85,persistence:.50,impact:.45,move:.35,speed:.35,acceleration:.22,market:.22,fearGreed:.08,marketForecast:.18,marketForecastConfidence:.05,marketTurning:.12,marketAgreement:.12,pa:.07,ce:.07,ema:.07,timeframe:.06,dirShort:0,net24h:0,dayVsHistory:0,profitBalance24h:0};
function dot(weights,x){let z=0;for(const k of FEATURE_NAMES)z+=(Number(weights?.[k])||0)*(Number(x?.[k])||0);return z}
function seedProbability(x){return sigmoid(-.12+dot(SEED,x))}
function learnedProbability(state,x){return sigmoid((Number(state.bias)||0)+dot(state.weights,x))}
function blendedProbability(state,x){let seed=seedProbability(x),learned=learnedProbability(state,x),blend=Math.min(.85,(Number(state.modelSamples)||0)/400*.85);return {seed,learned,blend,p:seed*(1-blend)+learned*blend}}
function featureAblations(state,x){let out={};for(const k of FEATURE_NAMES){let z={...x,[k]:0};out[k]=round(blendedProbability(state,z).p,5)}return out}
function executionGeometry(dir,fill,target,stop){fill=Number(fill);target=Number(target);stop=Number(stop);let numeric=[fill,target,stop].every(x=>Number.isFinite(x)&&x>0),side=numeric&&(dir==='SHORT'?(target<fill&&stop>fill):(target>fill&&stop<fill)),targetGrossPct=numeric?(dir==='SHORT'?(fill/target-1)*100:(target/fill-1)*100):null,targetNetPct=Number.isFinite(targetGrossPct)?targetGrossPct-SPOT_ROUND_TRIP_FEE_PCT:null;return {valid:!!side,reason:!numeric?'NON_NUMERIC_LEVELS':side?null:'LEVELS_WRONG_SIDE',dir:dir==='SHORT'?'SHORT':'LONG',fillPrice:round(fill,10),targetPrice:round(target,10),stopPrice:round(stop,10),targetGrossPct:round(targetGrossPct,5),targetNetPct:round(targetNetPct,5),economicallyViableTarget:Number.isFinite(targetNetPct)&&targetNetPct>0,feePolicy:'SPOT_NO_BNB',roundTripFeePct:SPOT_ROUND_TRIP_FEE_PCT}}
function challengerDecisions(p,w,baseP=p,economicGate=false){if(economicGate)return {CONTROL_ALL:'SKIP',FLOW_GATE:'SKIP',BASE_AI:'SKIP',CORTEX_AI:'SKIP',AGGRESSIVE:'SKIP',BALANCED:'SKIP',STRICT:'SKIP',MOMENTUM:'SKIP'};let f=w.flow||{},speed=Number(f.speed),accel=Number(f.acceleration);return {CONTROL_ALL:'ENTER',FLOW_GATE:f.eligible?'ENTER':'SKIP',BASE_AI:baseP>=PRIMARY_THRESHOLD?'ENTER':'SKIP',CORTEX_AI:p>=PRIMARY_THRESHOLD?'ENTER':'SKIP',AGGRESSIVE:p>=.52?'ENTER':'SKIP',BALANCED:p>=PRIMARY_THRESHOLD?'ENTER':'SKIP',STRICT:p>=.68?'ENTER':'SKIP',MOMENTUM:p>=.56&&speed>0&&accel>=0&&f.alive!==false?'ENTER':'SKIP'}}
function decide(state,w,market,now=Date.now(),price=null,mentor=null){
 state=normalizeState(state,now);if(w?.aiShadow?.finalDecision)return {state,shadow:w.aiShadow,created:false};if(!w?.flow||w.dataStale||!Number.isFinite(Number(w.flow.relative)))return {state,shadow:w?.aiShadow||null,created:false,waiting:true};if(Number(w.entryAt)<Number(state.startedAt)){let shadow={schema:SCHEMA,featureSchema:FEATURE_SCHEMA,status:'LEGACY',finalDecision:'IGNORE',decidedAt:now,reason:'PRE_AI_ACTIVE_CASE',modelVersion:MODEL_VERSION,lineageId:state.lineageId};return {state,shadow,created:true,legacy:true};}
 w.aiPortfolioContext=w.aiPortfolioContext||portfolioContext(state,now);let fill=Number.isFinite(Number(price))?Number(price):Number(w.livePrice??w.lastPrice??w.entryPrice),geometry=executionGeometry(w.dir,fill,w.targetPrice,w.stopPrice),features=extractFeatures(w,market);
 if(!geometry.valid){state.invalidExecution++;let shadow={schema:SCHEMA,featureSchema:FEATURE_SCHEMA,status:'REJECTED',finalDecision:'IGNORE',symbol:w.symbol||null,direction:w.dir==='SHORT'?'SHORT':'LONG',timeframe:w.tf||null,decidedAt:now,reason:'INVALID_EXECUTION_GEOMETRY',modelVersion:MODEL_VERSION,lineageId:state.lineageId,features,facts:decisionFacts(w,market,fill),fillPrice:round(fill,10),targetPrice:round(w.targetPrice,10),stopPrice:round(w.stopPrice,10),execution:geometry,portfolioAtDecision:{...w.aiPortfolioContext}};state.recent=(state.recent||[]).concat({t:now,caseId:w.cycleId,symbol:w.symbol,dir:w.dir,tf:w.tf,decision:'IGNORE',status:'REJECTED',reason:shadow.reason}).slice(-80);return {state,shadow,created:true,rejected:true};}
 let probs=blendedProbability(state,features),mentorDelta=clamp(Number(mentor?.delta)||0,-.08,.08),baseP=probs.p,finalP=clamp(baseP+mentorDelta,.02,.98),modelDecision=finalP>=PRIMARY_THRESHOLD?'ENTER':'SKIP',economicGate=!geometry.economicallyViableTarget,decision=economicGate?'SKIP':modelDecision,alts=challengerDecisions(finalP,w,baseP,economicGate);
 let mentorSnap=mentor&&mentor.active?{schema:mentor.schema||null,version:mentor.version||null,delta:round(mentorDelta,5),rawDelta:round(mentor.rawDelta,5),driftStatus:mentor.driftStatus||null,driftFactor:round(mentor.driftFactor,4),quarantined:!!mentor.quarantined,validatedCount:Number(mentor.validatedCount)||0,hits:Array.isArray(mentor.hits)?mentor.hits.slice(0,6):[]}:null;
 let shadow={schema:SCHEMA,featureSchema:FEATURE_SCHEMA,status:decision==='ENTER'?'OPEN':'SKIPPED',finalDecision:decision,symbol:w.symbol||null,direction:w.dir==='SHORT'?'SHORT':'LONG',timeframe:w.tf||null,modelDecision,decisionReason:economicGate?'TARGET_DOES_NOT_COVER_SPOT_FEES':'MODEL',economicGate,decidedAt:now,modelVersion:MODEL_VERSION,lineageId:state.lineageId,modelSamplesAtDecision:state.modelSamples,threshold:PRIMARY_THRESHOLD,confidence:round(finalP,5),baseConfidence:round(baseP,5),seedProbability:round(probs.seed,5),learnedProbability:round(probs.learned,5),learningBlend:round(probs.blend,5),mentor:mentorSnap,features,featureAblations:featureAblations(state,features),facts:decisionFacts(w,market,fill),fillPrice:round(fill,10),targetPrice:round(w.targetPrice,10),stopPrice:round(w.stopPrice,10),execution:geometry,portfolioAtDecision:{...w.aiPortfolioContext},challengers:alts};
 state.decisions++;if(decision==='ENTER')state.entered++;else state.skipped++;if(economicGate)state.economicSkips++;state.recent=(state.recent||[]).concat({t:now,caseId:w.cycleId,symbol:w.symbol,dir:w.dir,tf:w.tf,decision,modelDecision,decisionReason:shadow.decisionReason,confidence:shadow.confidence,baseConfidence:shadow.baseConfidence,cortexDelta:round(mentorDelta,5),status:shadow.status,targetNetPct:geometry.targetNetPct}).slice(-80);return {state,shadow,created:true};
}
function shadowBarrier(shadow,price){if(!shadow||!['OPEN','SKIPPED'].includes(shadow.status))return null;let p=Number(price),target=Number(shadow.targetPrice),stop=Number(shadow.stopPrice),dir=shadow.direction||shadow?.facts?.dir;if(![p,target,stop].every(Number.isFinite))return null;if(dir==='SHORT'){if(p<=target)return {reason:'TP',exitPrice:target};if(p>=stop)return {reason:'SL',exitPrice:stop}}else{if(p>=target)return {reason:'TP',exitPrice:target};if(p<=stop)return {reason:'SL',exitPrice:stop}}return null}
function economicOutcome(shadow,w,reason,exitPrice,now=Date.now()){
 let entered=shadow?.finalDecision==='ENTER',dir=shadow?.direction||shadow?.facts?.dir||w?.dir,sgn=dir==='SHORT'?-1:1,fill=Number(shadow?.fillPrice||w?.entryPrice||exitPrice),exit=Number(exitPrice),gross=fill>0&&exit>0?sgn*(exit/fill-1)*100:NaN,fees=SPOT_ROUND_TRIP_FEE_PCT,net=Number.isFinite(gross)?gross-fees:NaN,geometry=shadow?.execution||executionGeometry(dir,fill,shadow?.targetPrice??w?.targetPrice,shadow?.stopPrice??w?.stopPrice),y=geometry.valid&&Number.isFinite(net)&&net>0?1:0;
 // Binary win/loss remains available for calibration, but learning strength follows real net magnitude.
 // A tiny +0.01% net win must never cancel a much larger -1.00% net loss merely because both count as one case.
 let softTarget=Number.isFinite(net)?clamp(.5+net/(2*ECONOMIC_SOFT_TARGET_SCALE_PCT),.02,.98):.5,weight=Number.isFinite(net)?clamp(Math.abs(net)/ECONOMIC_WEIGHT_BASE_PCT,.25,4):.25;
 return {at:now,result:entered?reason:'SKIPPED',counterfactual:reason,exitPrice:round(exit,10),shadowMovePct:round(gross,5),grossMovePct:round(gross,5),entryFeePct:SPOT_ENTRY_FEE_PCT,exitFeePct:SPOT_EXIT_FEE_PCT,totalFeesPct:SPOT_ROUND_TRIP_FEE_PCT,netPnlPct:round(net,5),feePolicy:'SPOT_NO_BNB',economicResult:y?'NET_WIN':'NET_LOSS',winLabel:y,economicSoftTarget:round(softTarget,5),economicWeight:round(weight,5),grossPositive:Number.isFinite(gross)&&gross>0,missedWin:!entered&&!!y,avoidedLoss:!entered&&!y,executionValid:!!geometry.valid,trainingAccepted:null};
}
function resolveShadow(shadow,w,reason,exitPrice,now=Date.now()){
 if(!shadow||shadow.status==='LEGACY'||shadow.status==='REJECTED'||shadow.status==='CLOSED')return {shadow,outcome:shadow?.outcome||null,updated:false};let outcome=economicOutcome(shadow,w,reason,exitPrice,now);return {shadow:{...shadow,status:'CLOSED',outcome},outcome,updated:true};
}
function trainResolved(state,shadow,w,now=Date.now()){
 state=normalizeState(state,now);if(!shadow||shadow.status!=='CLOSED'||!shadow.outcome||shadow.outcome.executionValid===false)return {state,shadow,updated:false,duplicate:false};let caseId=String(w?.cycleId||shadow.caseId||'');if(caseId&&state.trainedCaseIdsRecent.includes(caseId)){let sh={...shadow,outcome:{...shadow.outcome,trainingAccepted:true,duplicateTrainingPrevented:true}};return {state,shadow:sh,updated:false,duplicate:true};}
 let y=Number(shadow.outcome.winLabel)===1?1:0,features=shadow.features||extractFeatures(w,{}),p=Number(shadow.confidence??.5),entered=shadow.finalDecision==='ENTER';if(entered){state.resolved++;if(y)state.wins++;else state.losses++;recordEconomicTrade(state,shadow,shadow.outcome,Number(shadow.outcome.at)||now)}else{if(y)state.missedWins++;else state.avoidedLosses++;}let pred=p>=.5?1:0;if(pred===y)state.correct++;state.brierSum+=(p-y)*(p-y);
 const oldSamples=Number(state.modelSamples)||0,lr=Math.max(.015,.065/Math.sqrt(1+oldSamples/80)),reg=.002,lp=learnedProbability(state,features),softTarget=clamp(Number(shadow.outcome.economicSoftTarget ?? y),.02,.98),economicWeight=clamp(Number(shadow.outcome.economicWeight ?? 1),.25,4),err=clamp((softTarget-lp)*economicWeight,-2,2);for(const k of FEATURE_NAMES)state.weights[k]=clamp((Number(state.weights[k])||0)+lr*(err*(Number(features[k])||0)-reg*(Number(state.weights[k])||0)),-4,4);state.bias=clamp((Number(state.bias)||0)+lr*err,-4,4);state.modelSamples=oldSamples+1;state.lastTrainedAt=now;
 let factsMarket=shadow?.facts?.market||{},tradeDir=shadow?.direction||shadow?.facts?.dir||w?.dir,curRel=factsMarket.relation||tradeRelation(tradeDir,factsMarket.direction),fc=factsMarket?.marketAI?.forecast60,fcRel=fc?.ready?(fc.relation||tradeRelation(tradeDir,fc.direction)):'NEUTRAL',turnReg=String(factsMarket?.marketAI?.regime||''),turnDir=turnReg==='TURNING_UP'?'UP':turnReg==='TURNING_DOWN'?'DOWN':'NEUTRAL',turnRel=turnDir==='NEUTRAL'?'NEUTRAL':tradeRelation(tradeDir,turnDir);bumpRelation(state.marketRelations,'current',curRel,y===1);bumpRelation(state.marketRelations,'forecast60',fcRel,y===1);bumpRelation(state.marketRelations,'turning',turnRel,y===1);
 let challengerOutcomes={};for(const [name,d] of Object.entries(shadow.challengers||{})){let st=state.challengers[name]||(state.challengers[name]={entered:0,skipped:0,wins:0,losses:0,missedWins:0,avoidedLosses:0});if(d==='ENTER'){st.entered++;if(y)st.wins++;else st.losses++;challengerOutcomes[name]={decision:d,result:shadow.outcome.counterfactual,netPnlPct:shadow.outcome.netPnlPct}}else{st.skipped++;if(y)st.missedWins++;else st.avoidedLosses++;challengerOutcomes[name]={decision:d,result:'SKIPPED',counterfactual:shadow.outcome.counterfactual,netPnlPct:shadow.outcome.netPnlPct}}}
 if(caseId)state.trainedCaseIdsRecent=(state.trainedCaseIdsRecent||[]).concat(caseId).slice(-512);let outcome={...shadow.outcome,trainingAccepted:true,trainedAt:now,modelSamplesAfter:state.modelSamples,challengers:challengerOutcomes},sh={...shadow,outcome};state.recent=(state.recent||[]).concat({t:now,caseId:w?.cycleId||shadow.caseId,symbol:sh.symbol||sh?.facts?.symbol||w?.symbol,dir:sh.direction||sh?.facts?.dir||w?.dir,tf:sh.timeframe||sh?.facts?.tf||w?.tf,decision:sh.finalDecision,modelDecision:sh.modelDecision||sh.finalDecision,decisionReason:sh.decisionReason||'MODEL',confidence:sh.confidence,status:'CLOSED',result:outcome.result,counterfactual:outcome.counterfactual,grossMovePct:outcome.grossMovePct,totalFeesPct:outcome.totalFeesPct,netPnlPct:outcome.netPnlPct,economicResult:outcome.economicResult,winLabel:outcome.winLabel,economicSoftTarget:outcome.economicSoftTarget,economicWeight:outcome.economicWeight}).slice(-80);return {state,shadow:sh,updated:true,duplicate:false};
}
function settle(state,shadow,w,reason,exitPrice,now=Date.now(),learn=true){state=normalizeState(state,now);let r=resolveShadow(shadow,w,reason,exitPrice,now);if(!r.updated)return {state,shadow:r.shadow,outcome:r.outcome,updated:false};if(!learn){let sh={...r.shadow,outcome:{...r.outcome,trainingAccepted:false}};return {state,shadow:sh,outcome:sh.outcome,updated:false};}let t=trainResolved(state,r.shadow,w,now);return {state:t.state,shadow:t.shadow,outcome:t.shadow?.outcome||r.outcome,updated:t.updated};}
function publicState(state,active=[]){state=normalizeState(state);let open=(active||[]).filter(w=>w?.aiShadow&&['OPEN','SKIPPED'].includes(w.aiShadow.status)).map(w=>({caseId:w.cycleId,symbol:w.aiShadow.symbol||w.symbol,dir:w.aiShadow.direction||w.dir,tf:w.aiShadow.timeframe||w.tf,status:w.aiShadow.status,decision:w.aiShadow.finalDecision,modelDecision:w.aiShadow.modelDecision||w.aiShadow.finalDecision,decisionReason:w.aiShadow.decisionReason||'MODEL',confidence:w.aiShadow.confidence,decidedAt:w.aiShadow.decidedAt,fillPrice:w.aiShadow.fillPrice,targetPrice:w.aiShadow.targetPrice,stopPrice:w.aiShadow.stopPrice,targetNetPct:w.aiShadow.execution?.targetNetPct})).slice(0,100);let resolved=state.resolved,wr=resolved?state.wins/resolved*100:null,totalLabels=state.modelSamples,accuracy=totalLabels?state.correct/totalLabels*100:null,brier=totalLabels?state.brierSum/totalLabels:null;return {schema:SCHEMA,featureSchema:FEATURE_SCHEMA,mode:'SHADOW',modelVersion:MODEL_VERSION,lineageId:state.lineageId,startedAt:state.startedAt,threshold:PRIMARY_THRESHOLD,repairVersion:state.repairVersion,feePolicy:'SPOT_NO_BNB',roundTripFeePct:SPOT_ROUND_TRIP_FEE_PCT,modelSamples:state.modelSamples,decisions:state.decisions,entered:state.entered,skipped:state.skipped,economicSkips:state.economicSkips,invalidExecution:state.invalidExecution,resolved,wins:state.wins,losses:state.losses,winRate:round(wr,2),missedWins:state.missedWins,avoidedLosses:state.avoidedLosses,accuracy:round(accuracy,2),brier:round(brier,5),bias:state.bias,weights:{...state.weights},economics:economicsPublic(state),open,challengers:state.challengers,marketRelations:state.marketRelations,lastTrainedAt:state.lastTrainedAt,recentOrder:'desc',recent:(state.recent||[]).slice(-40).reverse()};}
function caseSnapshot(shadow){if(!shadow||shadow.status==='LEGACY')return null;return {schema:SCHEMA,featureSchema:FEATURE_SCHEMA,modelVersion:shadow.modelVersion,lineageId:shadow.lineageId,symbol:shadow.symbol||shadow?.facts?.symbol||null,direction:shadow.direction||shadow?.facts?.dir||null,timeframe:shadow.timeframe||shadow?.facts?.tf||null,modelSamplesAtDecision:shadow.modelSamplesAtDecision,decision:shadow.finalDecision,modelDecision:shadow.modelDecision||shadow.finalDecision,decisionReason:shadow.decisionReason||null,economicGate:!!shadow.economicGate,decidedAt:shadow.decidedAt,confidence:shadow.confidence,baseConfidence:shadow.baseConfidence??shadow.confidence,seedProbability:shadow.seedProbability,learnedProbability:shadow.learnedProbability,learningBlend:shadow.learningBlend,mentor:shadow.mentor||null,fillPrice:shadow.fillPrice,targetPrice:shadow.targetPrice,stopPrice:shadow.stopPrice,execution:shadow.execution||null,portfolioAtDecision:shadow.portfolioAtDecision||null,features:shadow.features,featureAblations:shadow.featureAblations||null,facts:shadow.facts,challengers:shadow.challengers,outcome:shadow.outcome||null};}
module.exports={SCHEMA,MODEL_VERSION,FEATURE_SCHEMA,ECONOMICS_SCHEMA,REPAIR_VERSION,PRIMARY_THRESHOLD,FEATURE_NAMES,SPOT_ENTRY_FEE_PCT,SPOT_EXIT_FEE_PCT,SPOT_ROUND_TRIP_FEE_PCT,ECONOMIC_SOFT_TARGET_SCALE_PCT,ECONOMIC_WEIGHT_BASE_PCT,initialState,normalizeState,extractFeatures,decisionFacts,seedProbability,learnedProbability,blendedProbability,featureAblations,executionGeometry,shadowBarrier,economicOutcome,portfolioContext,economicsFeatureValues,economicsPublic,decide,resolveShadow,trainResolved,settle,publicState,caseSnapshot};
