'use strict';
const LearningForge=(()=>{
 const SCHEMA='alpha-proof-omega-cortex/3';
 const MODEL_VERSION='OMEGA-CORTEX-003';
 const TRADE_FEATURE_SCHEMA='FEATURES-V2-MARKET';
 const CORTEX_FEATURE_SCHEMA='CORTEX-RESEARCH-V3';
 const THRESHOLDS=[-0.75,-0.5,-0.25,0,0.25,0.5,0.75];
 const DISCOVERY_EVERY=25,MIN_DISCOVERY=60,MIN_CLASS_CASES=12,MIN_PROSPECTIVE=100,PROOF_GATE_EVERY=25;
 const MAX_CANDIDATES=36,MAX_VALIDATED=18,MAX_ARCHIVED=60,MAX_RECENT=100,MAX_SEGMENTS=160,MAX_CONTEXTS=40,MAX_RECENT_LABELS=200,MAX_BLOCKS=8,BLOCK_CASES=25;
 const PRIMARY_THRESHOLD=.60;
 const clamp=(x,a,b)=>Math.max(a,Math.min(b,Number.isFinite(Number(x))?Number(x):0));
 const round=(x,d=5)=>Number.isFinite(Number(x))?Number(Number(x).toFixed(d)):null;
 const mean=(s,n)=>n?s/n:0;
 const quantize=(x,step=.05)=>clamp(Math.round(Number(x)/step)*step,-.95,.95);
 const featureNames=['score','relative','pressure','persistence','impact','move','speed','acceleration','market','fearGreed','marketForecast','marketForecastConfidence','marketTurning','marketAgreement','pa','ce','ema','timeframe','dirShort'];
 const featureLabel={score:'Flow Score',relative:'Directional RVOL',pressure:'Pressure',persistence:'Persistence',impact:'Impact',move:'Move',speed:'Speed',acceleration:'Acceleration',market:'اتجاه السوق',fearGreed:'Fear & Greed',marketForecast:'توقع Market AI',marketForecastConfidence:'ثقة Market AI',marketTurning:'تحول السوق',marketAgreement:'اتفاق السوق',pa:'PA',ce:'C/E',ema:'EMA',timeframe:'الفريم',dirShort:'اتجاه الصفقة'};
 function newLineage(now=Date.now()){return `CORTEX-${Math.round(now).toString(36).toUpperCase()}`}
 function tfGroup(tf){let s=String(tf||'').toLowerCase();if(['5m','15m','30m','1h'].includes(s))return'INTRADAY';if(['4h','6h','12h'].includes(s))return'SWING';if(s==='1d')return'DAILY';return'OTHER'}
 function marketRelation(shadow,w){let r=String(shadow?.facts?.market?.relation||'');if(r)return r;let t=w?.dir==='SHORT'?-1:1,m=shadow?.facts?.market?.direction==='UP'?1:shadow?.facts?.market?.direction==='DOWN'?-1:0;return !m?'NEUTRAL':t===m?'WITH':'COUNTER'}
 function marketRegime(shadow){return String(shadow?.facts?.market?.marketAI?.regime||'NEUTRAL')}
 function contextsFor(shadow,w){let d=w?.dir==='SHORT'?'SHORT':'LONG',tf=tfGroup(w?.tf),rel=marketRelation(shadow,w),reg=marketRegime(shadow),out=['GLOBAL',`DIR_${d}`,`TF_${tf}`,`REL_${rel}`,`DIR_${d}__REL_${rel}`,`DIR_${d}__TF_${tf}`];if(reg&&reg!=='NEUTRAL')out.push(`REGIME_${reg}`);return[...new Set(out)].slice(0,7)}
 function blankFeatureStats(){return{n:0,winN:0,lossN:0,winSum:0,lossSum:0,winSq:0,lossSq:0}}
 function blankContext(){return{n:0,wins:0,losses:0,features:{}}}
 function blankBlock(){return{n:0,wins:0,matchN:0,matchWins:0,changedN:0,diffSum:0}}
 function blankEval(){return{allN:0,allWins:0,matchN:0,matchWins:0,changedN:0,helped:0,hurt:0,diffSum:0,diffSqSum:0,fastTarget:null,slowTarget:null,blocks:[],block:blankBlock(),lastAt:null}}
 function blankCalibration(){return Array.from({length:10},(_,i)=>({bin:i,n:0,wins:0,pSum:0,brier:0}))}
 function blankDrift(){return{features:{},outcome:{n:0,fast:.5,slow:.5},score:0,status:'LEARNING',updatedAt:null}}
 function blankArena(){return{cases:0,baseUtility:0,cortexUtility:0,deltaUtility:0,changed:0,helped:0,hurt:0,same:0,baseEnter:0,cortexEnter:0,baseCorrect:0,cortexCorrect:0,lastAt:null}}
 function blankAblationFeature(){return{n:0,deltaBrierSum:0,helped:0,hurt:0,neutral:0}}
 function blankAblation(){return{features:Object.fromEntries(featureNames.map(f=>[f,blankAblationFeature()])),lastAt:null}}
 function initialState(now=Date.now()){return{schema:SCHEMA,modelVersion:MODEL_VERSION,tradeFeatureSchema:TRADE_FEATURE_SCHEMA,cortexFeatureSchema:CORTEX_FEATURE_SCHEMA,lineageId:newLineage(now),startedAt:now,observedCases:0,wins:0,losses:0,lastObservedAt:null,lastDiscoveryAtSample:0,phase:'OBSERVE',contexts:{},candidates:[],validated:[],archived:[],calibration:{base:blankCalibration(),mentored:blankCalibration()},drift:blankDrift(),arena:blankArena(),ablation:blankAblation(),segments:{},recentLabels:[],recent:[],promotions:0,hypothesesGenerated:0,mentor:{maxAbsDelta:.08,appliedDecisions:0,quarantinedDecisions:0,lastAdviceAt:null,lastDelta:0},seenRuleKeys:[],trainedCaseIdsRecent:[]}}
 function normalizeFeatureStats(raw={}){let b=blankFeatureStats();for(const k of Object.keys(b))b[k]=Number.isFinite(Number(raw[k]))?Number(raw[k]):0;return b}
 function normalizeContext(raw={}){let b=blankContext(),o={...b,...raw,features:{}};for(const k of ['n','wins','losses'])o[k]=Math.max(0,Math.round(Number(o[k])||0));for(const f of featureNames)if(raw?.features?.[f])o.features[f]=normalizeFeatureStats(raw.features[f]);return o}
 function normalizeBlock(raw={}){let b=blankBlock();for(const k of Object.keys(b))b[k]=Number.isFinite(Number(raw[k]))?Number(raw[k]):0;return b}
 function normalizeEval(raw={}){let b=blankEval(),e={...b,...raw};for(const k of ['allN','allWins','matchN','matchWins','changedN','helped','hurt','diffSum','diffSqSum'])e[k]=Number.isFinite(Number(e[k]))?Number(e[k]):0;e.fastTarget=Number.isFinite(Number(e.fastTarget))?Number(e.fastTarget):null;e.slowTarget=Number.isFinite(Number(e.slowTarget))?Number(e.slowTarget):null;e.blocks=(Array.isArray(raw.blocks)?raw.blocks:[]).map(normalizeBlock).slice(-MAX_BLOCKS);e.block=normalizeBlock(raw.block||{});e.lastAt=Number.isFinite(Number(e.lastAt))?Number(e.lastAt):null;return e}
 function normalizeRule(r={}){return{type:r.type==='AND'?'AND':'SINGLE',terms:(Array.isArray(r.terms)?r.terms:[]).slice(0,2).map(t=>({feature:featureNames.includes(t.feature)?t.feature:'score',op:t.op==='LE'?'LE':'GE',threshold:quantize(t.threshold)}))}}
 function normalizeCandidate(c={}){return{id:String(c.id||''),kind:c.kind==='RISK'?'RISK':'EDGE',context:String(c.context||'GLOBAL'),status:['TESTING','PROMISING','PROVEN','REJECTED','DECAYED'].includes(c.status)?c.status:'TESTING',createdAt:Number(c.createdAt)||Date.now(),bornAtSample:Math.max(0,Math.round(Number(c.bornAtSample)||0)),rule:normalizeRule(c.rule),source:c.source||'AUTO_DISCOVERY',reason:String(c.reason||''),discovery:c.discovery&&typeof c.discovery==='object'?c.discovery:{},eval:normalizeEval(c.eval),validatedAt:Number(c.validatedAt)||null,rejectedAt:Number(c.rejectedAt)||null,decayedAt:Number(c.decayedAt)||null,strength:clamp(Number(c.strength)||0,0,.08),proof:c.proof&&typeof c.proof==='object'?{...c.proof}:null,lastChangedAt:Number(c.lastChangedAt)||Number(c.createdAt)||Date.now()}}
 function normalizeCal(raw){return Array.from({length:10},(_,i)=>{let x=Array.isArray(raw)?raw[i]||{}:{};return{bin:i,n:Math.max(0,Math.round(Number(x.n)||0)),wins:Math.max(0,Math.round(Number(x.wins)||0)),pSum:Number(x.pSum)||0,brier:Number(x.brier)||0}})}
 function normalizeDrift(raw={}){let d=blankDrift();d.outcome={n:Math.max(0,Math.round(Number(raw?.outcome?.n)||0)),fast:Number.isFinite(Number(raw?.outcome?.fast))?Number(raw.outcome.fast):.5,slow:Number.isFinite(Number(raw?.outcome?.slow))?Number(raw.outcome.slow):.5};d.score=Number(raw.score)||0;d.status=['LEARNING','STABLE','WATCH','SHIFT'].includes(raw.status)?raw.status:'LEARNING';d.updatedAt=Number(raw.updatedAt)||null;d.features={};for(const f of featureNames){let z=raw?.features?.[f];if(z)d.features[f]={n:Math.max(0,Math.round(Number(z.n)||0)),fast:Number(z.fast)||0,slow:Number(z.slow)||0}}return d}
 function normalizeArena(raw={}){let a=blankArena();for(const k of Object.keys(a))a[k]=k==='lastAt'?(Number(raw[k])||null):(Number.isFinite(Number(raw[k]))?Number(raw[k]):a[k]);return a}
 function normalizeAblation(raw={}){let out=blankAblation();out.lastAt=Number(raw?.lastAt)||null;for(const f of featureNames){let z=raw?.features?.[f]||{},d=out.features[f];for(const k of ['n','deltaBrierSum','helped','hurt','neutral'])d[k]=Number.isFinite(Number(z[k]))?Number(z[k]):0}return out}
 function normalizeState(raw={},now=Date.now()){let b=initialState(now),s={...b,...(raw&&typeof raw==='object'?raw:{})};s.schema=SCHEMA;s.modelVersion=MODEL_VERSION;s.tradeFeatureSchema=TRADE_FEATURE_SCHEMA;s.cortexFeatureSchema=CORTEX_FEATURE_SCHEMA;s.lineageId=String(s.lineageId||b.lineageId);s.startedAt=Number(s.startedAt)||now;for(const k of ['observedCases','wins','losses','lastObservedAt','lastDiscoveryAtSample','promotions','hypothesesGenerated'])s[k]=Number.isFinite(Number(s[k]))?Number(s[k]):b[k];s.contexts={};for(const [k,v] of Object.entries(raw?.contexts||raw?.discovery||{}).slice(0,MAX_CONTEXTS))s.contexts[String(k)]=normalizeContext(v);s.candidates=(Array.isArray(s.candidates)?s.candidates:[]).map(normalizeCandidate).filter(x=>x.id).slice(-MAX_CANDIDATES);s.validated=(Array.isArray(s.validated)?s.validated:[]).map(normalizeCandidate).filter(x=>x.id).slice(-MAX_VALIDATED);s.archived=(Array.isArray(s.archived)?s.archived:[]).map(normalizeCandidate).filter(x=>x.id).slice(-MAX_ARCHIVED);s.calibration={base:normalizeCal(raw?.calibration?.base||raw?.calibration),mentored:normalizeCal(raw?.calibration?.mentored||raw?.calibration)};s.drift=normalizeDrift(raw?.drift||{});s.arena=normalizeArena(raw?.arena||{});s.ablation=normalizeAblation(raw?.ablation||{});s.segments=s.segments&&typeof s.segments==='object'?s.segments:{};s.recentLabels=Array.isArray(s.recentLabels)?s.recentLabels.map(x=>Number(x)?1:0).slice(-MAX_RECENT_LABELS):[];s.recent=Array.isArray(s.recent)?s.recent.slice(-MAX_RECENT):[];s.mentor={...b.mentor,...(s.mentor||{})};s.seenRuleKeys=Array.isArray(s.seenRuleKeys)?s.seenRuleKeys.map(String).slice(-1024):[];s.trainedCaseIdsRecent=Array.isArray(s.trainedCaseIdsRecent)?s.trainedCaseIdsRecent.map(String).slice(-1024):[];updatePhase(s);return s}
 function sourceFeatures(shadow={}){let f=shadow?.features||{},out={};for(const k of featureNames)out[k]=clamp(f[k],-1,1);return out}
 function ruleMatch(rule,features={}){let terms=normalizeRule(rule).terms;if(!terms.length)return false;return terms.every(t=>{let v=Number(features?.[t.feature]);return Number.isFinite(v)&&(t.op==='LE'?v<=t.threshold:v>=t.threshold)})}
 function ruleText(rule){return normalizeRule(rule).terms.map(t=>`${featureLabel[t.feature]||t.feature} ${t.op==='GE'?'≥':'≤'} ${t.threshold}`).join(' + ')}
 function utility(decision,y){if(decision==='ENTER')return y?1:-1;return y?-.35:.35}
 function baseDecision(shadow){return Number(shadow?.baseConfidence??shadow?.confidence??.5)>=PRIMARY_THRESHOLD?'ENTER':'SKIP'}
 function candidateDecision(c,features,baseline){if(!ruleMatch(c.rule,features))return baseline;return c.kind==='RISK'?'SKIP':'ENTER'}
 function updateDiscovery(state,shadow,w,y){let feats=sourceFeatures(shadow);for(const ctxKey of contextsFor(shadow,w)){let ctx=state.contexts[ctxKey]||(state.contexts[ctxKey]=blankContext());ctx.n++;if(y)ctx.wins++;else ctx.losses++;for(const f of featureNames){let x=feats[f],st=ctx.features[f]||(ctx.features[f]=blankFeatureStats());st.n++;if(y){st.winN++;st.winSum+=x;st.winSq+=x*x}else{st.lossN++;st.lossSum+=x;st.lossSq+=x*x}}}}
 function featureSeparation(st){if(!st||st.winN<MIN_CLASS_CASES||st.lossN<MIN_CLASS_CASES)return null;let mw=mean(st.winSum,st.winN),ml=mean(st.lossSum,st.lossN),sep=Math.abs(mw-ml),thr=quantize((mw+ml)/2);if(sep<.10)return null;return{mw,ml,sep,thr,edgeOp:mw>=ml?'GE':'LE',riskOp:mw>=ml?'LE':'GE'}}
 function semanticRuleKey(kind,context,rule){return `${kind}|${context}|`+normalizeRule(rule).terms.map(t=>`${t.feature}|${t.op}|${t.threshold}`).sort().join('&')}
 function candidateId(kind,context,rule,born){return `${semanticRuleKey(kind,context,rule)}@${born}`}
 function existingKeys(state){return new Set([...(state.seenRuleKeys||[]),...[...state.candidates,...state.validated,...state.archived].map(c=>semanticRuleKey(c.kind,c.context,c.rule))])}
 function makeCandidate(kind,context,rule,state,reason,discovery,now){let born=state.observedCases;return normalizeCandidate({id:candidateId(kind,context,rule,born),kind,context,status:'TESTING',createdAt:now,bornAtSample:born,rule,source:'AUTO_DISCOVERY',reason,discovery,eval:blankEval()})}
 function discover(rawState,now=Date.now()){let state=normalizeState(rawState,now);if(state.observedCases<MIN_DISCOVERY||state.observedCases-state.lastDiscoveryAtSample<DISCOVERY_EVERY)return{state,created:[]};let keys=existingKeys(state),created=[];for(const [context,ctx] of Object.entries(state.contexts)){if(ctx.n<MIN_DISCOVERY)continue;let ranked=[];for(const f of featureNames){let z=featureSeparation(ctx.features[f]);if(z)ranked.push({feature:f,...z})}ranked.sort((a,b)=>b.sep-a.sep);for(const z of ranked.slice(0,5)){for(const kind of ['EDGE','RISK']){let op=kind==='EDGE'?z.edgeOp:z.riskOp,rule={type:'SINGLE',terms:[{feature:z.feature,op,threshold:z.thr}]},sk=semanticRuleKey(kind,context,rule);if(keys.has(sk))continue;let c=makeCandidate(kind,context,rule,state,`${kind==='EDGE'?'Edge':'Risk'} مكتشف في ${featureLabel[z.feature]||z.feature}`,{contextN:ctx.n,contextWinRate:round(ctx.wins/Math.max(1,ctx.n),5),feature:z.feature,separation:round(z.sep,5),winnerMean:round(z.mw,5),loserMean:round(z.ml,5)},now);created.push(c);keys.add(sk);state.seenRuleKeys=state.seenRuleKeys.concat(sk).slice(-1024);if(created.length>=8)break}if(created.length>=8)break}if(created.length<10){let top=ranked.slice(0,3);for(let i=0;i<top.length&&created.length<10;i++)for(let j=i+1;j<top.length&&created.length<10;j++){let a=top[i],b=top[j];for(const kind of ['EDGE','RISK']){let rule={type:'AND',terms:[{feature:a.feature,op:kind==='EDGE'?a.edgeOp:a.riskOp,threshold:a.thr},{feature:b.feature,op:kind==='EDGE'?b.edgeOp:b.riskOp,threshold:b.thr}]},sk=semanticRuleKey(kind,context,rule);if(keys.has(sk))continue;let c=makeCandidate(kind,context,rule,state,`تفاعل ${kind==='EDGE'?'Edge':'Risk'}: ${featureLabel[a.feature]} × ${featureLabel[b.feature]}`,{contextN:ctx.n,pair:[a.feature,b.feature],separation:round((a.sep+b.sep)/2,5)},now);created.push(c);keys.add(sk);state.seenRuleKeys=state.seenRuleKeys.concat(sk).slice(-1024);if(created.length>=10)break}}}if(created.length>=10)break}if(created.length){state.candidates=state.candidates.concat(created);state.hypothesesGenerated+=created.length;state.recent=state.recent.concat(created.map(c=>({t:now,type:'HYPOTHESIS',id:c.id,kind:c.kind,context:c.context,text:ruleText(c.rule),reason:c.reason,bornAtSample:c.bornAtSample}))).slice(-MAX_RECENT)}state.lastDiscoveryAtSample=state.observedCases;return{state,created}}
 function blockLift(c,b){if(!b?.n||!b.matchN)return null;let base=b.wins/b.n,rate=b.matchWins/b.matchN;return c.kind==='EDGE'?rate-base:base-rate}
 function updateEval(c,features,baseline,y,now){let e=c.eval,match=ruleMatch(c.rule,features),cand=candidateDecision(c,features,baseline),bu=utility(baseline,y),cu=utility(cand,y),diff=cu-bu;e.allN++;if(y)e.allWins++;if(match){e.matchN++;if(y)e.matchWins++;let target=c.kind==='EDGE'?y:1-y;e.fastTarget=e.fastTarget==null?target:.18*target+.82*e.fastTarget;e.slowTarget=e.slowTarget==null?target:.035*target+.965*e.slowTarget}if(cand!==baseline){e.changedN++;if(diff>0)e.helped++;else if(diff<0)e.hurt++}e.diffSum+=diff;e.diffSqSum+=diff*diff;e.lastAt=now;let b=e.block;b.n++;if(y)b.wins++;if(match){b.matchN++;if(y)b.matchWins++}if(cand!==baseline){b.changedN++;b.diffSum+=diff}if(b.n>=BLOCK_CASES){e.blocks=e.blocks.concat(normalizeBlock(b)).slice(-MAX_BLOCKS);e.block=blankBlock()}return{match,candidateDecision:cand,diff}}
 function wilsonLower(success,n,z=1.64){if(!n)return 0;let p=success/n,z2=z*z,den=1+z2/n,center=p+z2/(2*n),adj=z*Math.sqrt((p*(1-p)+z2/(4*n))/n);return(center-adj)/den}
 function proofZ(state,c){let tests=Math.max(1,Number(state?.hypothesesGenerated)||1),complexity=c?.rule?.type==='AND'?.10:0;return Math.min(2.58,1.96+Math.log10(tests+1)*.18+complexity)}
 function proofFirewall(state,c,st){let z=proofZ(state,c),success=c.kind==='EDGE'?c.eval.matchWins:c.eval.matchN-c.eval.matchWins,adjustedLower=c.eval.matchN?wilsonLower(success,c.eval.matchN,z):0,gate=c.eval.allN>=MIN_PROSPECTIVE&&c.eval.allN%PROOF_GATE_EVERY===0,blockGate=st.positiveBlocks>=3&&st.positiveBlocks>st.negativeBlocks*2;return{z,adjustedLower,gate,blockGate,hypothesesTested:Math.max(1,Number(state?.hypothesesGenerated)||1)}}
 function evalStats(c){let e=normalizeEval(c.eval),baseline=e.allN?e.allWins/e.allN:null,rate=e.matchN?e.matchWins/e.matchN:null,coverage=e.allN?e.matchN/e.allN:0,predictiveLift=baseline==null||rate==null?null:(c.kind==='EDGE'?rate-baseline:baseline-rate),targetSuccess=e.matchN?(c.kind==='EDGE'?e.matchWins/e.matchN:(e.matchN-e.matchWins)/e.matchN):null,targetLower=e.matchN?wilsonLower(c.kind==='EDGE'?e.matchWins:e.matchN-e.matchWins,e.matchN):0,changedMean=e.changedN?e.diffSum/e.changedN:0,allMean=e.allN?e.diffSum/e.allN:0,variance=e.changedN>1?Math.max(0,(e.diffSqSum-e.diffSum*e.diffSum/e.changedN)/(e.changedN-1)):0,se=e.changedN?Math.sqrt(variance/e.changedN):Infinity,changedLcb=Number.isFinite(se)?changedMean-1.645*se:-Infinity,blockLifts=e.blocks.map(b=>blockLift(c,b)).filter(Number.isFinite),positiveBlocks=blockLifts.filter(x=>x>=.02).length,negativeBlocks=blockLifts.filter(x=>x<=-.02).length,score=(predictiveLift||0)*Math.sqrt(Math.max(1,e.matchN))*Math.pow(Math.max(.02,coverage),.25)+Math.max(0,changedMean)*Math.sqrt(Math.max(1,e.changedN))*.25;return{n:e.allN,baseline,rate,coverage,predictiveLift,targetSuccess,targetLower,changedN:e.changedN,helped:e.helped,hurt:e.hurt,changedMean,changedLcb,allMean,blockLifts,positiveBlocks,negativeBlocks,fastTarget:e.fastTarget,slowTarget:e.slowTarget,score}}
 function removeById(arr,id){return(arr||[]).filter(x=>x.id!==id)}
 function statusEvent(c,from,to,st,now){return{type:'CORTEX_HYPOTHESIS_STATUS',t:now,id:c.id,kind:c.kind,context:c.context,from,to,rule:ruleText(c.rule),metrics:{prospectiveN:st.n,matchN:c.eval.matchN,changedN:st.changedN,predictiveLift:round(st.predictiveLift,5),changedMean:round(st.changedMean,5),targetLower:round(st.targetLower,5),positiveBlocks:st.positiveBlocks,negativeBlocks:st.negativeBlocks,score:round(st.score,5)}}}
 function updateCandidateStatus(state,c,now){let st=evalStats(c),old=c.status,next=old,fw=proofFirewall(state,c,st);if(['REJECTED','DECAYED'].includes(old))return{state,c,action:null,stats:st,event:null,firewall:fw};if(old==='PROVEN'){if(c.eval.matchN>=100&&Number.isFinite(st.fastTarget)&&Number.isFinite(st.slowTarget)&&st.fastTarget<.48&&st.fastTarget<st.slowTarget-.12)next='DECAYED'}else{if(c.eval.matchN>=20&&st.changedN>=5&&st.predictiveLift>=.04&&st.changedMean>0)next='PROMISING';let proof=fw.gate&&fw.blockGate&&c.eval.matchN>=40&&st.changedN>=10&&st.coverage>=.05&&st.coverage<=.90&&st.predictiveLift>=.055&&st.changedMean>=.05&&fw.adjustedLower>=.50;if(proof)next='PROVEN';if(c.eval.matchN>=50&&(st.predictiveLift<=-.02||st.changedN>=10&&st.changedMean<=-.05))next='REJECTED'}c.strength=clamp(.01+Math.max(0,st.predictiveLift||0)*.18+Math.max(0,st.changedMean)*.05,.01,.045);c.lastChangedAt=next!==old?now:c.lastChangedAt;if(next===old)return{state,c,action:null,stats:st,event:null,firewall:fw};c.status=next;let ev=statusEvent(c,old,next,st,now);if(next==='PROVEN'){c.validatedAt=now;c.proof={z:round(fw.z,3),adjustedLower:round(fw.adjustedLower,5),hypothesesTested:fw.hypothesesTested,prospectiveN:c.eval.allN,matchN:c.eval.matchN,positiveBlocks:st.positiveBlocks,negativeBlocks:st.negativeBlocks,gateEvery:PROOF_GATE_EVERY};state.validated=removeById(state.validated,c.id).concat(c).slice(-MAX_VALIDATED);state.candidates=removeById(state.candidates,c.id);state.promotions++}else if(next==='REJECTED'){c.rejectedAt=now;state.archived=removeById(state.archived,c.id).concat(c).slice(-MAX_ARCHIVED);state.candidates=removeById(state.candidates,c.id)}else if(next==='DECAYED'){c.decayedAt=now;state.archived=removeById(state.archived,c.id).concat(c).slice(-MAX_ARCHIVED);state.validated=removeById(state.validated,c.id)}return{state,c,action:next,stats:st,event:ev,firewall:fw}}
 function contextMatch(context,shadow,w){return contextsFor(shadow,w).includes(context)}
 function evaluateHypotheses(state,shadow,w,y,now){let events=[],features=sourceFeatures(shadow),baseline=baseDecision(shadow);for(const listName of ['candidates','validated']){let list=[...(state[listName]||[])];for(const c of list){if(state.observedCases<=c.bornAtSample||!contextMatch(c.context,shadow,w))continue;updateEval(c,features,baseline,y,now);let u=updateCandidateStatus(state,c,now);state=u.state;if(u.event)events.push(u.event)}}return events}
 function updateCalibrationBins(bins,p,y){p=clamp(p,0,1);let idx=Math.min(9,Math.floor(p*10)),b=bins[idx];b.n++;b.wins+=y;b.pSum+=p;b.brier+=(p-y)*(p-y)}
 function calibrationSummary(bins){let total=0,ece=0,brier=0;for(const b of bins){if(!b.n)continue;let ap=b.pSum/b.n,aw=b.wins/b.n;total+=b.n;ece+=b.n*Math.abs(ap-aw);brier+=b.brier}return{samples:total,ece:total?round(ece/total,5):null,brier:total?round(brier/total,5):null,bins:bins.map(b=>({bin:b.bin,n:b.n,predicted:b.n?round(b.pSum/b.n,4):null,actual:b.n?round(b.wins/b.n,4):null}))}}
 function updateCalibration(state,shadow,y){updateCalibrationBins(state.calibration.base,Number(shadow?.baseConfidence??shadow?.confidence??.5),y);updateCalibrationBins(state.calibration.mentored,Number(shadow?.confidence??.5),y)}
 function updateAblation(state,shadow,y,now){let full=clamp(Number(shadow?.baseConfidence??shadow?.confidence??.5),0,1),fullLoss=(full-y)*(full-y),src=shadow?.featureAblations||{};for(const f of featureNames){let p=Number(src[f]);if(!Number.isFinite(p))continue;let z=state.ablation.features[f],delta=(p-y)*(p-y)-fullLoss;z.n++;z.deltaBrierSum+=delta;if(delta>.0005)z.helped++;else if(delta<-.0005)z.hurt++;else z.neutral++}state.ablation.lastAt=now}
 function updateDrift(state,shadow,y,now){let feats=sourceFeatures(shadow),scores=[];for(const f of featureNames){let x=feats[f],d=state.drift.features[f]||(state.drift.features[f]={n:0,fast:x,slow:x});if(!d.n){d.fast=x;d.slow=x}else{d.fast=.12*x+.88*d.fast;d.slow=.018*x+.982*d.slow}d.n++;if(d.n>=30)scores.push(Math.abs(d.fast-d.slow))}let o=state.drift.outcome;if(!o.n){o.fast=y;o.slow=y}else{o.fast=.12*y+.88*o.fast;o.slow=.018*y+.982*o.slow}o.n++;if(o.n>=30)scores.push(Math.abs(o.fast-o.slow));let score=scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:0;state.drift.score=round(score,5);state.drift.status=state.observedCases<120?'LEARNING':score>=.18?'SHIFT':score>=.09?'WATCH':'STABLE';state.drift.updatedAt=now}
 function updateArena(state,shadow,y,now){let b=baseDecision(shadow),c=shadow?.finalDecision==='ENTER'?'ENTER':'SKIP',bu=utility(b,y),cu=utility(c,y),a=state.arena;a.cases++;a.baseUtility+=bu;a.cortexUtility+=cu;a.deltaUtility+=cu-bu;if(b==='ENTER')a.baseEnter++;if(c==='ENTER')a.cortexEnter++;if((b==='ENTER')===!!y)a.baseCorrect++;if((c==='ENTER')===!!y)a.cortexCorrect++;if(b===c)a.same++;else{a.changed++;if(cu>bu)a.helped++;else if(cu<bu)a.hurt++}a.lastAt=now}
 function updateSegments(state,shadow,w,y){let keys=contextsFor(shadow,w);for(const key of keys){let s=state.segments[key]||(state.segments[key]={n:0,wins:0,baseEnter:0,cortexEnter:0,changed:0,helped:0,hurt:0,lastAt:null}),bd=baseDecision(shadow),cd=shadow?.finalDecision==='ENTER'?'ENTER':'SKIP',bu=utility(bd,y),cu=utility(cd,y);s.n++;if(y)s.wins++;if(bd==='ENTER')s.baseEnter++;if(cd==='ENTER')s.cortexEnter++;if(bd!==cd){s.changed++;if(cu>bu)s.helped++;else if(cu<bu)s.hurt++}s.lastAt=Date.now()}let kk=Object.keys(state.segments);if(kk.length>MAX_SEGMENTS){kk.sort((a,b)=>(state.segments[a].n||0)-(state.segments[b].n||0)||(state.segments[a].lastAt||0)-(state.segments[b].lastAt||0));for(const old of kk.slice(0,kk.length-MAX_SEGMENTS))delete state.segments[old]}}
 function updatePhase(state){let n=state.observedCases;state.phase=n<MIN_DISCOVERY?'OBSERVE':n<300?'DISCOVER':n<1200?'VALIDATE':'MATURE'}
 function prune(state){let pool=(state.candidates||[]).filter(x=>['TESTING','PROMISING'].includes(x.status));pool.sort((a,b)=>Number(b.status==='PROMISING')-Number(a.status==='PROMISING')||Math.min(MIN_PROSPECTIVE,evalStats(b).n)-Math.min(MIN_PROSPECTIVE,evalStats(a).n)||evalStats(b).score-evalStats(a).score||a.bornAtSample-b.bornAtSample);let kept=pool.slice(0,MAX_CANDIDATES),dropped=pool.slice(MAX_CANDIDATES);for(const c of dropped){c.status='DECAYED';c.decayedAt=Date.now();c.reason=(c.reason?c.reason+' · ':'')+'RESEARCH_CAPACITY_PRUNE';state.archived=removeById(state.archived,c.id).concat(c).slice(-MAX_ARCHIVED)}state.candidates=kept;state.validated=(state.validated||[]).filter(x=>x.status==='PROVEN').sort((a,b)=>evalStats(b).score-evalStats(a).score).slice(0,MAX_VALIDATED);state.archived=(state.archived||[]).slice(-MAX_ARCHIVED)}
 function observeResolved(rawState,shadow,w,now=Date.now()){let state=normalizeState(rawState,now),caseId=String(w?.cycleId||shadow?.caseId||'');if(!shadow||shadow.status!=='CLOSED'||!shadow.outcome||!shadow.features)return{state,updated:false,events:[],reason:'NOT_RESOLVED'};if(caseId&&state.trainedCaseIdsRecent.includes(caseId))return{state,updated:false,duplicate:true,events:[]};let y=Number(shadow.outcome.winLabel)===1?1:0,events=evaluateHypotheses(state,shadow,w,y,now);updateCalibration(state,shadow,y);updateAblation(state,shadow,y,now);updateDrift(state,shadow,y,now);updateArena(state,shadow,y,now);updateSegments(state,shadow,w,y);updateDiscovery(state,shadow,w,y);state.observedCases++;if(y)state.wins++;else state.losses++;state.lastObservedAt=now;state.recentLabels=state.recentLabels.concat(y).slice(-MAX_RECENT_LABELS);if(caseId)state.trainedCaseIdsRecent=state.trainedCaseIdsRecent.concat(caseId).slice(-1024);updatePhase(state);if(state.observedCases-state.lastDiscoveryAtSample>=DISCOVERY_EVERY){let d=discover(state,now);state=d.state;for(const c of d.created)events.push({type:'CORTEX_HYPOTHESIS_CREATED',t:now,id:c.id,kind:c.kind,context:c.context,rule:ruleText(c.rule),bornAtSample:c.bornAtSample,reason:c.reason})}state.recent=state.recent.concat({t:now,type:'CASE',caseId:caseId||null,symbol:w?.symbol||null,dir:w?.dir||null,tf:w?.tf||null,y,baseDecision:baseDecision(shadow),cortexDecision:shadow?.finalDecision||null,baseConfidence:round(shadow?.baseConfidence,5),confidence:round(shadow?.confidence,5),drift:state.drift.status}).slice(-MAX_RECENT);prune(state);return{state,updated:true,events}}
 function mentorAdvice(rawState,features={},now=Date.now(),contextHints=null){let state=normalizeState(rawState,now),hits=[],rawDelta=0,contexts=contextHints?.contexts||null;for(const c of state.validated){if(c.status!=='PROVEN')continue;if(contexts&&Array.isArray(contexts)&&!contexts.includes(c.context))continue;if(!ruleMatch(c.rule,features))continue;let st=evalStats(c),ev=Math.min(1,c.eval.matchN/100),block=Math.min(1,st.positiveBlocks/3),strength=clamp((Number(c.strength)||.01)*(.55+.25*ev+.20*block),.005,.045),d=c.kind==='RISK'?-strength:strength;rawDelta+=d;hits.push({id:c.id,kind:c.kind,context:c.context,delta:round(d,4),rule:ruleText(c.rule),n:c.eval.matchN,lift:round(st.predictiveLift,4),changedMean:round(st.changedMean,4),blocks:st.positiveBlocks})}let driftFactor=state.drift.status==='SHIFT'?0:state.drift.status==='WATCH'?.5:1,delta=clamp(rawDelta*driftFactor,-state.mentor.maxAbsDelta,state.mentor.maxAbsDelta),active=hits.length>0;return{schema:SCHEMA,version:MODEL_VERSION,active,delta:round(delta,5),rawDelta:round(clamp(rawDelta,-state.mentor.maxAbsDelta,state.mentor.maxAbsDelta),5),driftStatus:state.drift.status,driftFactor,quarantined:active&&driftFactor===0,validatedCount:state.validated.length,hits:hits.sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)).slice(0,6),at:now}}
 function noteMentorApplied(rawState,advice,now=Date.now()){let state=normalizeState(rawState,now);if(advice?.quarantined)state.mentor.quarantinedDecisions++;if(advice?.active&&Math.abs(Number(advice.delta)||0)>0){state.mentor.appliedDecisions++;state.mentor.lastAdviceAt=now;state.mentor.lastDelta=Number(advice.delta)||0}return state}
 function topInsights(state,limit=10){let out=[];for(const [context,ctx] of Object.entries(state.contexts||{})){if(ctx.n<MIN_DISCOVERY)continue;for(const f of featureNames){let z=featureSeparation(ctx.features[f]);if(!z)continue;let overall=ctx.n?ctx.wins/ctx.n:null;out.push({context,feature:f,label:featureLabel[f]||f,op:z.edgeOp,threshold:z.thr,separation:round(z.sep,3),winnerMean:round(z.mw,3),loserMean:round(z.ml,3),samples:ctx.n,overallWinRate:round(overall,3)})}}return out.sort((a,b)=>b.separation-a.separation||b.samples-a.samples).slice(0,limit)}
 function topSegments(state,limit=10){return Object.entries(state.segments||{}).filter(([,s])=>s.n>=10).map(([key,s])=>({key,n:s.n,winRate:round(s.wins/s.n,3),changed:s.changed,helped:s.helped,hurt:s.hurt,helpRate:s.changed?round(s.helped/s.changed,3):null})).sort((a,b)=>b.n-a.n).slice(0,limit)}
 function ablationSummary(state){return featureNames.map(f=>{let z=state.ablation?.features?.[f]||blankAblationFeature(),avg=z.n?z.deltaBrierSum/z.n:null;return{feature:f,label:featureLabel[f]||f,n:z.n,avgDeltaBrier:round(avg,6),helped:z.helped,hurt:z.hurt,neutral:z.neutral,helpRate:z.n?round(z.helped/z.n*100,2):null}}).filter(x=>x.n).sort((a,b)=>(b.avgDeltaBrier??-Infinity)-(a.avgDeltaBrier??-Infinity))}
 function publicCandidate(c){let st=evalStats(c);return{id:c.id,kind:c.kind,context:c.context,status:c.status,rule:ruleText(c.rule),bornAtSample:c.bornAtSample,prospectiveN:st.n,matchN:c.eval.matchN,changedN:st.changedN,lift:round(st.predictiveLift,4),changedMean:round(st.changedMean,4),targetLower:round(st.targetLower,4),positiveBlocks:st.positiveBlocks,negativeBlocks:st.negativeBlocks,score:round(st.score,4),strength:round(c.strength,4),proof:c.proof||null,reason:c.reason,validatedAt:c.validatedAt}}
 function publicState(rawState){let state=normalizeState(rawState),baseCal=calibrationSummary(state.calibration.base),mentCal=calibrationSummary(state.calibration.mentored),a=state.arena,arena={...a,baseAvgUtility:a.cases?round(a.baseUtility/a.cases,4):null,cortexAvgUtility:a.cases?round(a.cortexUtility/a.cases,4):null,deltaAvgUtility:a.cases?round(a.deltaUtility/a.cases,4):null,baseAccuracy:a.cases?round(a.baseCorrect/a.cases*100,2):null,cortexAccuracy:a.cases?round(a.cortexCorrect/a.cases*100,2):null,changeHelpRate:a.changed?round(a.helped/a.changed*100,2):null};let candidates=state.candidates.map(publicCandidate).sort((a,b)=>(b.status==='PROMISING')-(a.status==='PROMISING')||b.score-a.score).slice(0,16),validated=state.validated.map(publicCandidate).sort((a,b)=>b.score-a.score).slice(0,16);return{schema:SCHEMA,modelVersion:MODEL_VERSION,tradeFeatureSchema:TRADE_FEATURE_SCHEMA,cortexFeatureSchema:CORTEX_FEATURE_SCHEMA,lineageId:state.lineageId,mode:'SHADOW_RESEARCH',startedAt:state.startedAt,phase:state.phase,observedCases:state.observedCases,wins:state.wins,losses:state.losses,winRate:state.observedCases?round(state.wins/state.observedCases*100,2):null,hypothesesGenerated:state.hypothesesGenerated,promotions:state.promotions,testingCount:candidates.filter(x=>x.status==='TESTING').length,promisingCount:candidates.filter(x=>x.status==='PROMISING').length,validatedCount:validated.length,edgeProven:validated.filter(x=>x.kind==='EDGE').length,riskProven:validated.filter(x=>x.kind==='RISK').length,mentor:state.mentor,drift:state.drift,calibration:{base:baseCal,mentored:mentCal,deltaEce:baseCal.ece!=null&&mentCal.ece!=null?round(baseCal.ece-mentCal.ece,5):null,deltaBrier:baseCal.brier!=null&&mentCal.brier!=null?round(baseCal.brier-mentCal.brier,5):null},arena,statisticalFirewall:{enabled:true,prospectiveOnly:true,proofGateEvery:PROOF_GATE_EVERY,minProspective:MIN_PROSPECTIVE,multipleTestingAdjusted:true,minPositiveBlocks:3},ablation:ablationSummary(state),topInsights:topInsights(state),topSegments:topSegments(state),candidates,validated,recent:(state.recent||[]).slice(-40).reverse()}}
 return{SCHEMA,MODEL_VERSION,TRADE_FEATURE_SCHEMA,CORTEX_FEATURE_SCHEMA,featureNames,featureLabel,THRESHOLDS,DISCOVERY_EVERY,MIN_DISCOVERY,MIN_PROSPECTIVE,PROOF_GATE_EVERY,MAX_CANDIDATES,MAX_VALIDATED,PRIMARY_THRESHOLD,initialState,normalizeState,contextsFor,sourceFeatures,ruleMatch,ruleText,utility,evalStats,proofFirewall,ablationSummary,observeResolved,mentorAdvice,noteMentorApplied,discover,publicState,topInsights,topSegments};
})();
if(typeof module!=='undefined'&&module.exports)module.exports=LearningForge;
if(typeof window!=='undefined')window.LearningForge=LearningForge;
