'use strict';
const MarketAI=(()=>{
 const SCHEMA='alpha-proof-market-ai/1';
 const RUNTIME_SCHEMA='alpha-proof-market-ai-runtime/1';
 const FEATURE_SCHEMA='MARKET-FEATURES-V1';
 const MODEL_VERSION='MARKET-AI-001';
 const HORIZONS=[15,60,240,720,1440];
 const CLASSES=['UP','NEUTRAL','DOWN'];
 const OBS_INTERVAL_MIN=5, ANCHOR_INTERVAL_MIN=15, MIN_READY=50;
 const HISTORY_MAX=300, ANCHOR_MAX=120, RECENT_MAX=80, TRAINED_ID_MAX=512;
 const FEATURE_NAMES=['breadthGap','median24h','strongGap','weighted24h','dispersion','btc24h','eth24h','breadthMom15','breadthMom60','medianMom15','medianMom60','indexMom15','indexMom60','fearGreed','fearGreedMom60','participation'];
 const clamp=(x,a,b)=>Math.max(a,Math.min(b,Number.isFinite(Number(x))?Number(x):0));
 const round=(x,d=5)=>Number.isFinite(Number(x))?Number(Number(x).toFixed(d)):null;
 const median=a=>{let v=(a||[]).filter(Number.isFinite).sort((x,y)=>x-y),n=v.length;if(!n)return 0;return n%2?v[(n-1)/2]:(v[n/2-1]+v[n/2])/2};
 const mean=a=>a?.length?a.reduce((s,x)=>s+x,0)/a.length:0;
 const std=a=>{if(!a?.length)return 0;let m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)**2)))};
 const newLineage=(now=Date.now())=>`MARKET-${Math.round(now).toString(36).toUpperCase()}`;
 const blankWeights=()=>Object.fromEntries(CLASSES.map(c=>[c,Object.fromEntries(FEATURE_NAMES.map(k=>[k,0]))]));
 const blankStats=()=>({samples:0,correct:0,brierSum:0,bias:{UP:0,NEUTRAL:0,DOWN:0},weights:blankWeights(),trainedResolutionIdsRecent:[],lastTrainedAt:null});
 function initialState(now=Date.now()){return {schema:SCHEMA,featureSchema:FEATURE_SCHEMA,modelVersion:MODEL_VERSION,lineageId:newLineage(now),startedAt:now,resolvedLabels:0,anchorsCreated:0,lastTrainedAt:null,horizons:Object.fromEntries(HORIZONS.map(h=>[String(h),blankStats()])),recent:[]}}
 function initialRuntime(now=Date.now()){return {schema:RUNTIME_SCHEMA,featureSchema:FEATURE_SCHEMA,modelVersion:MODEL_VERSION,startedAt:now,baseline:{startedAt:null,prices:{}},history:[],anchors:[],lastAnchorAt:null,lastObservedAt:null,lastFacts:null,lastRegime:'NEUTRAL'}}
 function normalizeStats(raw={}){let b=blankStats(),s={...b,...(raw||{})};for(const k of ['samples','correct','brierSum'])s[k]=Number.isFinite(Number(s[k]))?Number(s[k]):0;s.bias={...b.bias,...(s.bias||{})};s.weights={};for(const c of CLASSES)s.weights[c]={...b.weights[c],...(raw?.weights?.[c]||{})};s.trainedResolutionIdsRecent=Array.isArray(s.trainedResolutionIdsRecent)?s.trainedResolutionIdsRecent.map(String).slice(-TRAINED_ID_MAX):[];s.lastTrainedAt=Number.isFinite(Number(s.lastTrainedAt))?Number(s.lastTrainedAt):null;return s}
 function normalizeState(raw={},now=Date.now()){let b=initialState(now),s={...b,...(raw&&typeof raw==='object'?raw:{})};s.schema=SCHEMA;s.featureSchema=FEATURE_SCHEMA;s.modelVersion=MODEL_VERSION;s.lineageId=String(s.lineageId||b.lineageId);s.startedAt=Number.isFinite(Number(s.startedAt))?Number(s.startedAt):now;s.resolvedLabels=Math.max(0,Math.round(Number(s.resolvedLabels)||0));s.anchorsCreated=Math.max(0,Math.round(Number(s.anchorsCreated)||0));s.horizons={};for(const h of HORIZONS)s.horizons[String(h)]=normalizeStats(raw?.horizons?.[String(h)]||{});s.recent=Array.isArray(s.recent)?s.recent.slice(-RECENT_MAX):[];s.lastTrainedAt=Number.isFinite(Number(s.lastTrainedAt))?Number(s.lastTrainedAt):null;return s}
 function normalizeRuntime(raw={},now=Date.now()){let b=initialRuntime(now),r={...b,...(raw&&typeof raw==='object'?raw:{})};r.schema=RUNTIME_SCHEMA;r.featureSchema=FEATURE_SCHEMA;r.modelVersion=MODEL_VERSION;r.startedAt=Number.isFinite(Number(r.startedAt))?Number(r.startedAt):now;r.baseline=r.baseline&&typeof r.baseline==='object'?{startedAt:Number(r.baseline.startedAt)||null,prices:r.baseline.prices&&typeof r.baseline.prices==='object'?r.baseline.prices:{}}:b.baseline;r.history=Array.isArray(r.history)?r.history.filter(x=>x&&Number.isFinite(Number(x.t))).slice(-HISTORY_MAX):[];r.anchors=Array.isArray(r.anchors)?r.anchors.filter(x=>x&&x.id&&Number.isFinite(Number(x.t))).slice(-ANCHOR_MAX):[];r.lastAnchorAt=Number.isFinite(Number(r.lastAnchorAt))?Number(r.lastAnchorAt):null;r.lastObservedAt=Number.isFinite(Number(r.lastObservedAt))?Number(r.lastObservedAt):null;r.lastRegime=String(r.lastRegime||'NEUTRAL');return r}
 function priceOf(t){let p=Number(t?.lastPrice??t?.price??t?.c);return Number.isFinite(p)&&p>0?p:null}
 function changeOf(t){let v=Number(t?.priceChangePercent);return Number.isFinite(v)?v:null}
 function volumeOf(t){let v=Number(t?.quoteVolume??t?.q);return Number.isFinite(v)&&v>=0?v:0}
 function tickerEntries(tickerMap){let arr=[];if(tickerMap instanceof Map){for(const [symbol,t] of tickerMap)if(String(symbol).endsWith('USDT'))arr.push([String(symbol),t])}else if(tickerMap&&typeof tickerMap==='object'){for(const [symbol,t] of Object.entries(tickerMap))if(String(symbol).endsWith('USDT'))arr.push([String(symbol),t])}return arr}
 function rebuildBaseline(runtime,entries,now){runtime.baseline={startedAt:now,prices:Object.fromEntries(entries.map(([s,t])=>[s,typeof t==='number'?t:priceOf(t)]).filter(([,p])=>Number.isFinite(p)&&p>0))};runtime.history=[];runtime.anchors=[];runtime.lastAnchorAt=null}
 function marketIndex(runtime,entries,now){let prices=runtime.baseline?.prices||{},available=entries.map(([s,t])=>[s,priceOf(t)]).filter(([,p])=>p),keys=Object.keys(prices),overlap=available.filter(([s])=>Number(prices[s])>0);if(keys.length<50){rebuildBaseline(runtime,available,now);prices=runtime.baseline.prices;overlap=available.filter(([s])=>Number(prices[s])>0)}else if(overlap.length<Math.max(40,keys.length*.60)){rebuildBaseline(runtime,available,now);prices=runtime.baseline.prices;overlap=available.filter(([s])=>Number(prices[s])>0)}let logs=overlap.map(([s,p])=>Math.log(p/Number(prices[s]))*100).filter(Number.isFinite);return {indexPct:round(median(logs),6)??0,overlap:logs.length,baselineSize:Object.keys(prices).length}}
 function atOrBefore(history,now,mins){let target=now-mins*60000,best=null;for(const x of history||[]){if(x.t<=target&&(!best||x.t>best.t))best=x}return best}
 function factsFromTicker(tickerMap,fearGreed,runtime,now=Date.now()){let entries=tickerEntries(tickerMap),changes=[],weightedNum=0,weightedDen=0,strongUp=0,strongDown=0,up=0,down=0;for(const [s,t] of entries){let c=changeOf(t);if(c==null)continue;changes.push(c);if(c>0)up++;if(c<0)down++;if(c>=2)strongUp++;if(c<=-2)strongDown++;let w=Math.sqrt(Math.max(0,volumeOf(t)));weightedNum+=c*w;weightedDen+=w}let count=changes.length||1,idx=marketIndex(runtime,entries,now),btc=changeOf((tickerMap instanceof Map?tickerMap.get('BTCUSDT'):tickerMap?.BTCUSDT)||{}),eth=changeOf((tickerMap instanceof Map?tickerMap.get('ETHUSDT'):tickerMap?.ETHUSDT)||{}),fg=Number(fearGreed?.value),base={t:now,sampleCount:changes.length,upPct:up/count*100,downPct:down/count*100,breadthGap:(up-down)/count,median24h:median(changes),strongGap:(strongUp-strongDown)/count,weighted24h:weightedDen?weightedNum/weightedDen:median(changes),dispersion:std(changes),btc24h:Number.isFinite(btc)?btc:0,eth24h:Number.isFinite(eth)?eth:0,fearGreed:Number.isFinite(fg)?fg:null,participation:clamp(changes.length/400,0,1),indexPct:idx.indexPct,baselineOverlap:idx.overlap,baselineSize:idx.baselineSize};let h15=atOrBefore(runtime.history,now,15),h60=atOrBefore(runtime.history,now,60);base.breadthMom15=h15?base.breadthGap-Number(h15.breadthGap||0):0;base.breadthMom60=h60?base.breadthGap-Number(h60.breadthGap||0):0;base.medianMom15=h15?base.median24h-Number(h15.median24h||0):0;base.medianMom60=h60?base.median24h-Number(h60.median24h||0):0;base.indexMom15=h15?base.indexPct-Number(h15.indexPct||0):0;base.indexMom60=h60?base.indexPct-Number(h60.indexPct||0):0;base.fearGreedMom60=h60&&Number.isFinite(Number(h60.fearGreed))&&Number.isFinite(Number(base.fearGreed))?Number(base.fearGreed)-Number(h60.fearGreed):0;return base}
 function extractFeatures(f={}){return {breadthGap:clamp(f.breadthGap,-1,1),median24h:clamp(Number(f.median24h||0)/5,-1,1),strongGap:clamp(f.strongGap,-1,1),weighted24h:clamp(Number(f.weighted24h||0)/5,-1,1),dispersion:clamp(Number(f.dispersion||0)/10,0,1),btc24h:clamp(Number(f.btc24h||0)/5,-1,1),eth24h:clamp(Number(f.eth24h||0)/5,-1,1),breadthMom15:clamp(Number(f.breadthMom15||0)/.35,-1,1),breadthMom60:clamp(Number(f.breadthMom60||0)/.60,-1,1),medianMom15:clamp(Number(f.medianMom15||0)/2,-1,1),medianMom60:clamp(Number(f.medianMom60||0)/4,-1,1),indexMom15:clamp(Number(f.indexMom15||0)/1,-1,1),indexMom60:clamp(Number(f.indexMom60||0)/2,-1,1),fearGreed:Number.isFinite(Number(f.fearGreed))?clamp((Number(f.fearGreed)-50)/50,-1,1):0,fearGreedMom60:clamp(Number(f.fearGreedMom60||0)/30,-1,1),participation:clamp(f.participation,0,1)}}
 function currentRegime(f={}){let bg=Number(f.breadthGap||0),med=Number(f.median24h||0),bm=Number(f.breadthMom15||0),im=Number(f.indexMom15||0);if(bg>=.10&&bm<=-.12&&im<=-.12)return'TURNING_DOWN';if(bg<=-.10&&bm>=.12&&im>=.12)return'TURNING_UP';if(bg>=.35&&med>=1)return'STRONG_UP';if(bg<=-.35&&med<=-1)return'STRONG_DOWN';if(bg>=.10&&med>=0)return'UP';if(bg<=-.10&&med<=0)return'DOWN';if(bm>=.15&&im>=.12)return'TURNING_UP';if(bm<=-.15&&im<=-.12)return'TURNING_DOWN';return'NEUTRAL'}
 function softmax(logits){let m=Math.max(...Object.values(logits)),e=Object.fromEntries(CLASSES.map(c=>[c,Math.exp(clamp(logits[c]-m,-20,20))])),z=Object.values(e).reduce((a,b)=>a+b,0)||1;return Object.fromEntries(CLASSES.map(c=>[c,e[c]/z]))}
 function seedProbabilities(x,h=60){let horizonDamp=clamp(Math.sqrt(60/Math.max(15,h)),.35,1.4),momentum=.70*x.breadthMom15+.55*x.indexMom15+.35*x.breadthMom60+.30*x.indexMom60,structure=1.15*x.breadthGap+.55*x.strongGap+.40*x.median24h+.25*x.weighted24h+.20*x.btc24h+.15*x.eth24h+.08*x.fearGreed,trend=structure+horizonDamp*momentum,neutral=.55-.55*Math.abs(x.breadthGap)-.35*Math.abs(x.indexMom15)-.15*Math.abs(x.median24h)+.18*x.dispersion;return softmax({UP:trend,DOWN:-trend,NEUTRAL:neutral})}
 function learnedProbabilities(stats,x){let logits={};for(const c of CLASSES){let z=Number(stats.bias?.[c])||0;for(const k of FEATURE_NAMES)z+=(Number(stats.weights?.[c]?.[k])||0)*(Number(x?.[k])||0);logits[c]=z}return softmax(logits)}
 function blendedProbabilities(state,x,h){let stats=state.horizons[String(h)],seed=seedProbabilities(x,h),learned=learnedProbabilities(stats,x),blend=Math.min(.88,(Number(stats.samples)||0)/500*.88),p={};for(const c of CLASSES)p[c]=seed[c]*(1-blend)+learned[c]*blend;return {p,seed,learned,blend}}
 function forecastFor(state,x,h){let b=blendedProbabilities(state,x,h),direction=CLASSES.slice().sort((a,c)=>b.p[c]-b.p[a])[0],confidence=b.p[direction],stats=state.horizons[String(h)]||blankStats();return {horizonMin:h,direction,confidence:round(confidence,5),probabilities:Object.fromEntries(CLASSES.map(c=>[c,round(b.p[c],5)])),seedBlend:round(1-b.blend,5),learningBlend:round(b.blend,5),samples:Math.round(stats.samples||0),accuracy:stats.samples?round(stats.correct/stats.samples*100,2):null,brier:stats.samples?round(stats.brierSum/stats.samples,5):null,ready:Number(stats.samples||0)>=MIN_READY}}
 function allForecasts(state,x){return Object.fromEntries(HORIZONS.map(h=>[String(h),forecastFor(state,x,h)]))}
 function returnThreshold(h){return .15*Math.sqrt(h/15)}
 function directionFromReturn(ret,h){let th=returnThreshold(h);return ret>th?'UP':ret<-th?'DOWN':'NEUTRAL'}
 function trainOne(state,h,features,label,resolutionId,now){let st=state.horizons[String(h)];if(st.trainedResolutionIdsRecent.includes(String(resolutionId)))return false;let probs=learnedProbabilities(st,features),samples=st.samples,lr=Math.max(.012,.055/Math.sqrt(1+samples/100)),reg=.0015;for(const c of CLASSES){let y=c===label?1:0,err=y-probs[c];st.bias[c]=clamp(Number(st.bias[c]||0)+lr*err,-5,5);for(const k of FEATURE_NAMES)st.weights[c][k]=clamp(Number(st.weights[c][k]||0)+lr*(err*Number(features[k]||0)-reg*Number(st.weights[c][k]||0)),-5,5)}let pred=CLASSES.slice().sort((a,b)=>probs[b]-probs[a])[0];st.samples=samples+1;if(pred===label)st.correct++;st.brierSum+=CLASSES.reduce((s,c)=>s+(probs[c]-(c===label?1:0))**2,0)/CLASSES.length;st.lastTrainedAt=now;st.trainedResolutionIdsRecent=st.trainedResolutionIdsRecent.concat(String(resolutionId)).slice(-TRAINED_ID_MAX);state.resolvedLabels++;state.lastTrainedAt=now;return true}
 function compactFacts(f){let keys=['t','sampleCount','upPct','downPct','breadthGap','median24h','strongGap','weighted24h','dispersion','btc24h','eth24h','fearGreed','participation','indexPct','breadthMom15','breadthMom60','medianMom15','medianMom60','indexMom15','indexMom60','fearGreedMom60','baselineOverlap','baselineSize'];return Object.fromEntries(keys.map(k=>[k,round(f[k],k==='t'||k==='sampleCount'||k==='fearGreed'||k==='baselineOverlap'||k==='baselineSize'?0:6)]))}
 function observe(rawState,rawRuntime,tickerMap,fearGreed,now=Date.now()){let state=normalizeState(rawState,now),runtime=normalizeRuntime(rawRuntime,now),facts=factsFromTicker(tickerMap,fearGreed,runtime,now),features=extractFeatures(facts),regime=currentRegime(facts),createdAnchor=null,resolutions=[],observationAdded=false;runtime.lastFacts=compactFacts(facts);runtime.lastRegime=regime;runtime.lastObservedAt=now;let last=runtime.history.at(-1);if(!last||now-last.t>=OBS_INTERVAL_MIN*60000){runtime.history.push(compactFacts(facts));runtime.history=runtime.history.slice(-HISTORY_MAX);observationAdded=true}if(!runtime.lastAnchorAt||now-runtime.lastAnchorAt>=ANCHOR_INTERVAL_MIN*60000){let forecasts=allForecasts(state,features),id=`MKT-${Math.floor(now/(ANCHOR_INTERVAL_MIN*60000))}`;createdAnchor={id,t:now,indexPct:facts.indexPct,regime,features,facts:compactFacts(facts),forecasts:Object.fromEntries(HORIZONS.map(h=>[String(h),{direction:forecasts[String(h)].direction,confidence:forecasts[String(h)].confidence,probabilities:forecasts[String(h)].probabilities,samples:forecasts[String(h)].samples,ready:forecasts[String(h)].ready}])),resolved:{}};runtime.anchors.push(createdAnchor);runtime.lastAnchorAt=now;state.anchorsCreated++}for(const a of runtime.anchors){a.resolved=a.resolved||{};for(const h of HORIZONS){let hk=String(h);if(a.resolved[hk]||now<a.t+h*60000)continue;let ret=Number(facts.indexPct)-Number(a.indexPct),actual=directionFromReturn(ret,h),rid=`${a.id}|${h}`,forecast=a.forecasts?.[hk]||forecastFor(state,a.features,h),trained=trainOne(state,h,a.features,actual,rid,now);a.resolved[hk]={resolutionId:rid,at:now,actualDirection:actual,marketReturnPct:round(ret,6),thresholdPct:round(returnThreshold(h),6),trained};let ev={type:'MARKET_RESOLUTION',schema:'alpha-proof-market-ai-dataset/1',resolutionId:rid,anchorId:a.id,anchorAt:a.t,resolvedAt:now,horizonMin:h,featureSchema:FEATURE_SCHEMA,modelVersion:MODEL_VERSION,lineageId:state.lineageId,regimeAtAnchor:a.regime,features:a.features,facts:a.facts,forecastAtAnchor:forecast,actual:{direction:actual,marketReturnPct:round(ret,6),thresholdPct:round(returnThreshold(h),6)},trained};resolutions.push(ev);state.recent=state.recent.concat({t:now,resolutionId:rid,horizonMin:h,predicted:forecast.direction,confidence:forecast.confidence,actual,marketReturnPct:round(ret,5),correct:forecast.direction===actual}).slice(-RECENT_MAX)}}runtime.anchors=runtime.anchors.filter(a=>Object.keys(a.resolved||{}).length<HORIZONS.length&&now-a.t<2*1440*60000).slice(-ANCHOR_MAX);return {state,runtime,facts:compactFacts(facts),features,regime,forecasts:allForecasts(state,features),createdAnchor,observationAdded,resolutions}}
 function regimeLabel(r){return ({STRONG_UP:'صاعد قوي',UP:'صاعد',TURNING_UP:'يتحول للصعود',NEUTRAL:'محايد',TURNING_DOWN:'يتحول للهبوط',DOWN:'هابط',STRONG_DOWN:'هابط قوي'})[r]||'محايد'}
 function publicState(rawState,rawRuntime){let state=normalizeState(rawState),runtime=normalizeRuntime(rawRuntime),facts=runtime.lastFacts||{},features=extractFeatures(facts),forecasts=allForecasts(state,features),perH={};for(const h of HORIZONS){let st=state.horizons[String(h)],fc=forecasts[String(h)];perH[String(h)]={...fc,samples:st.samples,accuracy:st.samples?round(st.correct/st.samples*100,2):null,brier:st.samples?round(st.brierSum/st.samples,5):null}}return {schema:SCHEMA,runtimeSchema:RUNTIME_SCHEMA,featureSchema:FEATURE_SCHEMA,modelVersion:MODEL_VERSION,lineageId:state.lineageId,mode:'SHADOW_MARKET',startedAt:state.startedAt,anchorEveryMin:ANCHOR_INTERVAL_MIN,observationEveryMin:OBS_INTERVAL_MIN,minReadySamples:MIN_READY,resolvedLabels:state.resolvedLabels,totalResolved:state.resolvedLabels,anchorsCreated:state.anchorsCreated,regime:runtime.lastRegime||'NEUTRAL',regimeLabel:regimeLabel(runtime.lastRegime||'NEUTRAL'),current:facts,forecasts:perH,forecast60:perH['60'],historyPoints:runtime.history.length,pendingAnchors:runtime.anchors.length,baselineSize:Object.keys(runtime.baseline?.prices||{}).length,lastObservedAt:runtime.lastObservedAt,lastTrainedAt:state.lastTrainedAt,recent:(state.recent||[]).slice(-30).reverse()}}
 function tradeContext(rawState,rawRuntime){let p=publicState(rawState,rawRuntime),f=p.forecast60||{};return {schema:SCHEMA,featureSchema:FEATURE_SCHEMA,modelVersion:MODEL_VERSION,lineageId:p.lineageId,regime:p.regime,observedAt:p.lastObservedAt,currentDirection:p.regime.includes('UP')?'UP':p.regime.includes('DOWN')?'DOWN':'NEUTRAL',forecast60:{direction:f.direction||'NEUTRAL',confidence:f.confidence??null,ready:!!f.ready,samples:f.samples||0,probabilities:f.probabilities||null}}}
 return {SCHEMA,RUNTIME_SCHEMA,FEATURE_SCHEMA,MODEL_VERSION,HORIZONS,CLASSES,FEATURE_NAMES,OBS_INTERVAL_MIN,ANCHOR_INTERVAL_MIN,MIN_READY,HISTORY_MAX,ANCHOR_MAX,initialState,initialRuntime,normalizeState,normalizeRuntime,factsFromTicker,extractFeatures,currentRegime,seedProbabilities,learnedProbabilities,forecastFor,allForecasts,returnThreshold,directionFromReturn,observe,publicState,tradeContext,trainOne,regimeLabel};
})();
if(typeof module!=='undefined'&&module.exports)module.exports=MarketAI;
