'use strict';
const SCHEMA='alpha-proof-problem-solver/1';
function n(v,d=0){v=Number(v);return Number.isFinite(v)?v:d}
function initialState(){return {schema:SCHEMA,problems:[],lastIngestedJob:null,lastAt:null}}
function normalizeState(raw={}){let s={...initialState(),...(raw&&typeof raw==='object'?raw:{})};s.schema=SCHEMA;s.problems=Array.isArray(s.problems)?s.problems:[];return s}
function signature(job){let text=String(job?.summary||'').replace(/\d+(?:\.\d+)?%/g,'#%').replace(/\d+/g,'#').replace(/\s+/g,' ').trim();return `${job?.worker||''}|${text}`.slice(0,500)}
function ingestWorkforce(raw,jobs=[],now=Date.now()){let s=normalizeState(raw);let ordered=[...(jobs||[])].filter(j=>j&&j.id).sort((a,b)=>n(a.createdAt)-n(b.createdAt));for(const j of ordered){if(s.problems.some(p=>p.sourceJobIds?.includes(j.id)))continue;if(j.worker!=='FALSIFIER'&&!/حالة مضادة|حالات مضادة|counter/i.test(String(j.summary||'')))continue;let sig=signature(j),p=s.problems.find(x=>x.signature===sig&&x.status!=='SOLVED');if(!p){p={id:`P-${String(s.problems.length+1).padStart(4,'0')}`,signature:sig,type:'RESEARCH',status:'OPEN',title:String(j.summary||'مشكلة بحثية'),summary:String(j.summary||''),recurrences:0,firstSeenAt:n(j.createdAt,now),lastSeenAt:n(j.createdAt,now),sourceJobIds:[],attempts:[],solution:null,hypothesisId:null};s.problems.push(p)}p.recurrences++;p.lastSeenAt=n(j.createdAt,now);p.sourceJobIds.push(j.id);p.sourceJobIds=p.sourceJobIds.slice(-50);if(p.recurrences>=2&&p.status==='OPEN')p.status='NEEDS_SOLVER';s.lastIngestedJob=j.id;s.lastAt=now}s.problems=s.problems.slice(-500);return s}
function ingestAccounting(raw,issues=[],now=Date.now()){let s=normalizeState(raw);for(const x of issues||[]){if(!x?.id)continue;let sig=`ACCOUNTING|${x.type}|${x.symbol||''}|${x.tf||''}`,p=s.problems.find(z=>z.signature===sig&&z.status!=='SOLVED');if(!p){p={id:`P-${String(s.problems.length+1).padStart(4,'0')}`,signature:sig,type:x.type?.includes('UNEXPLAINED')?'RESEARCH':'OPERATIONAL_REVIEW',status:'OPEN',title:x.summary||x.type,summary:x.summary||'',recurrences:0,firstSeenAt:x.createdAt||now,lastSeenAt:x.createdAt||now,sourceIssueIds:[],attempts:[],solution:null,hypothesisId:null};s.problems.push(p)}if(!p.sourceIssueIds.includes(x.id)){p.sourceIssueIds.push(x.id);p.recurrences++;p.lastSeenAt=x.createdAt||now;if(p.recurrences>=2)p.status='NEEDS_SOLVER'}}s.problems=s.problems.slice(-500);return s}
function applyCortexAttempts(raw,workforce={},now=Date.now()){let s=normalizeState(raw),e=workforce?.workers?.evidenceHunter?.lastResult,g=workforce?.workers?.generalizationTester?.lastResult;for(const p of s.problems.filter(x=>x.status==='NEEDS_SOLVER')){let fingerprint=[e?.summary,g?.summary].filter(Boolean).join(' | ');if(!fingerprint)continue;if(p.attempts.some(a=>a.fingerprint===fingerprint))continue;p.attempts.push({at:now,by:'PROBLEM_SOLVER',fingerprint,summary:`راجع أدلة CORTEX الحالية: ${fingerprint}`});p.attempts=p.attempts.slice(-20);p.status='SOLVING'}return s}

function reconcileSolutions(raw,workforce={},cortex={},now=Date.now()){let s=normalizeState(raw),jobs=Array.isArray(workforce?.recentJobs)?workforce.recentJobs:[],pool=[...(cortex?.candidates||[]),...(cortex?.validated||[]),...(cortex?.archived||[])];for(const p of s.problems){let linkedJobs=jobs.filter(j=>p.sourceJobIds?.includes(j.id)&&j.proposal?.rule?.terms?.length),candidate=pool.find(c=>linkedJobs.some(j=>c?.discovery?.jobId===j.id));if(candidate){p.solution={at:now,by:candidate.source||'CORTEX',summary:candidate.reason||linkedJobs.at(-1)?.solution||'تم استخراج حل قابل للاختبار',sourceJobId:candidate.discovery?.jobId||null};p.hypothesisId=candidate.id;if(candidate.status==='PROVEN'){p.status='SOLVED';p.solvedAt=now;p.proofStatus='PROVEN'}else if(candidate.status==='REJECTED'||candidate.status==='DECAYED'){p.status=p.recurrences>=2?'NEEDS_SOLVER':'OPEN';p.proofStatus=candidate.status;p.hypothesisId=null;p.solution=null;p.attempts.push({at:now,by:'CORTEX_PROOF',summary:`الحل السابق ${candidate.id} لم يثبت (${candidate.status})؛ أعيدت المشكلة للبحث عن حل مختلف.`})}else{p.status='HYPOTHESIS_TESTING';p.proofStatus=candidate.status}}}return s}
function publicState(raw={}){let s=normalizeState(raw),open=s.problems.filter(p=>!['SOLVED','PROVEN'].includes(p.status)),repeated=open.filter(p=>p.recurrences>=2);return {schema:SCHEMA,total:s.problems.length,open:open.length,repeated:repeated.length,solving:open.filter(p=>['NEEDS_SOLVER','SOLVING','HYPOTHESIS_TESTING'].includes(p.status)).length,solved:s.problems.filter(p=>p.status==='SOLVED').length,problems:open.slice(-30).reverse(),repeatedProblems:repeated.sort((a,b)=>b.recurrences-a.recurrences).slice(0,20),lastAt:s.lastAt}}
module.exports={SCHEMA,initialState,normalizeState,ingestWorkforce,ingestAccounting,applyCortexAttempts,reconcileSolutions,publicState};
