/* ALPHA PROOF: prospective research only. Never sends an order or promotes a model. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./research-math'),require('./research-execution'));else root.ResearchEngine=factory(root.ResearchMath,root.ResearchExecution)})(typeof globalThis!=='undefined'?globalThis:this,function(M,E){
'use strict';
const VERSION='RESEARCH-14-1',DAY=86400000,EPOCH=7*DAY,HORIZONS=[1,2,4],POLICIES=['HOLD','ECONOMIC','PARTIAL','STUDENT'];
const LIMITS={studies:64,labels:1200,markets:96,positions:16,events:512,deepBudget:4};
const copy=x=>JSON.parse(JSON.stringify(x));
const finite=x=>Number.isFinite(x);
function frame(tf){let m=/^(\d+)(m|h|d|w)$/.exec(tf||'');return m?+m[1]*({m:60000,h:3600000,d:DAY,w:7*DAY}[m[2]]):3600000}
function newModels(){return Object.fromEntries(HORIZONS.map(h=>[h,M.model()]))}
function create(now=Date.now()){return {version:VERSION,startedAt:now,lastAt:now,studies:{},seen:[],labels:[],markets:{},models:newModels(),fast:newModels(),student:newModels(),ssl:M.model(),regime:{fast:0,slow:0,noise:.05,change:0,probabilities:[.25,.25,.25,.25]},uniqueEvidence:0,labelCount:0,replayUpdates:0,teacherUpdates:0,sslUpdates:0,rejected:0,capacityRejected:0,blocks:{},events:[],eventSeq:0,epoch:null,proof:{ECONOMIC:[],PARTIAL:[],STUDENT:[]},epochs:0,lastEpoch:null,scheduleCursor:0}}
function validate(s){
 const vector=x=>Array.isArray(x)&&x.length===8&&x.every(finite),model=m=>m&&vector(m.w)&&finite(m.updates)&&finite(m.error),models=m=>m&&HORIZONS.every(h=>model(m[h]));
 if(!(s&&s.version===VERSION&&finite(s.startedAt)&&s.startedAt>0&&finite(s.lastAt)&&s.lastAt>=s.startedAt&&models(s.models)&&models(s.fast)&&models(s.student)&&model(s.ssl)&&Array.isArray(s.labels)&&s.labels.length<=LIMITS.labels&&Array.isArray(s.events)&&s.events.length<=LIMITS.events&&s.studies&&Object.keys(s.studies).length<=LIMITS.studies&&s.markets&&Object.keys(s.markets).length<=LIMITS.markets&&Array.isArray(s.seen)&&s.seen.length<=2048&&s.regime&&Array.isArray(s.regime.probabilities)&&s.regime.probabilities.length===4&&s.proof&&POLICIES.slice(1).every(k=>Array.isArray(s.proof[k])&&s.proof[k].length<=2048&&s.proof[k].every(finite))))return false;
 if(!['uniqueEvidence','labelCount','replayUpdates','teacherUpdates','sslUpdates','rejected','capacityRejected','eventSeq'].every(k=>finite(s[k])&&s[k]>=0))return false;
 if(!s.labels.every(r=>vector(r.x)&&finite(r.y)&&HORIZONS.includes(r.h)&&r.featureAt>=s.startedAt&&r.due>r.featureAt&&r.observedAt>=r.due))return false;
 if(!Object.values(s.studies).every(p=>vector(p.x)&&p.at>=s.startedAt&&p.price>0&&Array.isArray(p.horizons)&&p.horizons.length===3&&p.horizons.every(h=>HORIZONS.includes(h.h)&&h.due>p.at)))return false;
 if(s.epoch&&!(model(s.epoch.frozen?.ssl)&&models(s.epoch.frozen?.models)&&models(s.epoch.frozen?.fast)&&models(s.epoch.frozen?.student)&&Array.isArray(s.epoch.frozen?.labels)&&s.epoch.frozen.labels.length<=LIMITS.labels&&POLICIES.every(k=>s.epoch.portfolios?.[k]&&finite(s.epoch.portfolios[k].cash)&&Object.keys(s.epoch.portfolios[k].positions).length<=LIMITS.positions)))return false;
 function numbers(v){if(typeof v==='number')return finite(v);if(v&&typeof v==='object')return Object.values(v).every(numbers);return true}return numbers(s);
}
function event(s,type,now,data={}){s.events.push({seq:++s.eventSeq,type,at:now,...data});if(s.events.length>LIMITS.events)s.events.shift()}
function features(row,market,s,encoder=s.ssl){let flow=market?.flow,x=[1,M.clamp((+row.radarScore||50)/100,0,1),M.clamp((+row.relativeVolume||1)/5,0,2),M.clamp((+row.alignedPressure||50)/50-1,-1,1),M.clamp((flow?.imbalance||0)*(1-M.clamp(flow?.absorption||0,0,.9)),-1,1),M.clamp(flow?.responsePct||0,-2,2),M.clamp(s.regime.fast,-2,2),M.clamp(s.regime.noise,0,2)];if(encoder)x[5]=M.clamp(M.predict(encoder,x),-2,2);return x}
function liquidity(q){return +q?.quoteVolume>=1e8?'HIGH':+q?.quoteVolume>=1e7?'MID':'LOW'}
function regime(s,returns){if(!returns.length)return;let r=M.mean(returns),g=s.regime;g.fast=.8*g.fast+.2*r;g.slow=.99*g.slow+.01*r;g.noise=Math.max(.005,.95*g.noise+.05*Math.abs(r-g.slow));g.change=Math.max(0,g.change+Math.abs(g.fast-g.slow)/g.noise-.8);let scores=[g.fast/g.noise,-g.fast/g.noise,1-Math.abs(g.fast)/g.noise,g.change/10],max=Math.max(...scores),p=scores.map(x=>Math.exp(M.clamp(x-max,-20,0))),sum=p.reduce((a,b)=>a+b,0);g.probabilities=p.map(x=>x/sum);if(g.change>25){event(s,'REGIME_CHANGE',s.lastAt,{distance:g.change});g.change=0}return g.probabilities.indexOf(Math.max(...g.probabilities))}
function forecast(s,key,x,frozen=null){let src=frozen||s,d=M.pooled(src.labels,key),slow=M.predict(src.models[key.h],x),fast=M.predict(src.fast[key.h],x),student=M.predict(src.student[key.h],x),emp=d.mean,fastWeight=.2+.4*(s.regime.probabilities[3]||0),teacher=.4*emp+(.6-fastWeight)*slow+fastWeight*fast;return {...d,slow,fast,student,teacher,uncertainty:Math.max(.05,(d.q90??1)-(d.q10??-1))/Math.sqrt(1+d.groupN/8),ready:d.globalN>=64&&d.groupN>=16}}
function startEpoch(s,now){let portfolios={};for(let p of POLICIES)portfolios[p]={cash:10000,positions:{},fees:0,realized:0,equity:10000,valid:true,actions:0};s.epoch={id:++s.epochs,start:now,end:now+EPOCH,modelCutoff:now,version:VERSION,frozen:{ssl:copy(s.ssl),models:copy(s.models),fast:copy(s.fast),student:copy(s.student),labels:copy(s.labels)},portfolios,admitted:0,quality:true};event(s,'EPOCH_START',now,{id:s.epoch.id,policyVersions:POLICIES.map(p=>p+'-1'),capital:10000})}
function register(s,shadow,row,now){let id=String(row?.cycleId||shadow?.id||'');if(!id||!shadow||!finite(+shadow.decidedAt)||row.dir!=='LONG'||+shadow.decidedAt<s.startedAt||+shadow.decidedAt>now||row.dataStale||!(+shadow.fillPrice>0)||s.studies[id]||s.seen.includes(id))return false;if(Object.keys(s.studies).length>=LIMITS.studies){s.capacityRejected++;return false}let tf=row.tf||'1h',ms=frame(tf),m=s.markets[row.symbol],x=features(row,m,s),p=+shadow.fillPrice;let st={id,symbol:row.symbol,tf,ms,at:now,price:p,lastAt:now,lastPrice:p,x:x.slice(),liq:m?.liq||'UNKNOWN',regime:s.regime.probabilities.indexOf(Math.max(...s.regime.probabilities)),horizons:HORIZONS.map(h=>({h,due:now+h*ms,done:false})),max:0,min:0,first:null,hitMs:null,valid:true,counted:false,portfolioTried:false};s.studies[id]=st;s.seen.push(id);if(s.seen.length>2048)s.seen.shift();event(s,'PATH_REGISTERED',now,{id,symbol:st.symbol,tf,featureAt:now,horizons:st.horizons.map(h=>h.due),x:st.x,price:st.price,liquidity:st.liq,regime:st.regime,version:VERSION});return true}
// Rotating exploration takes half the budget; the rest targets uncertainty and elapsed coverage.
function schedule(s,tickers,now){let entries=[...tickers].filter(([symbol,q])=>/USDT$/.test(symbol)&&+q.lastPrice>0&&+q.quoteVolume>=1e6).map(([symbol])=>symbol).sort();let pending=[...new Set(Object.values(s.studies).map(p=>p.symbol))],universe=[...new Set([...pending,...entries])];if(!universe.length)return [];let held=new Set(Object.values(s.epoch?.portfolios||{}).flatMap(p=>Object.values(p.positions).map(p=>p.symbol)));let ranked=universe.map(symbol=>({symbol,score:(pending.includes(symbol)?3:0)+(held.has(symbol)?5:0)+Math.min(4,(now-(s.markets[symbol]?.depthAt||0))/60000)+(1/(1+(s.markets[symbol]?.observations||0)))+Math.min(2,Math.abs(M.predict(s.models[1],s.markets[symbol]?.x||[])-M.predict(s.fast[1],s.markets[symbol]?.x||[])))})).sort((a,b)=>b.score-a.score||a.symbol.localeCompare(b.symbol));let selected=ranked.slice(0,2).map(x=>x.symbol);for(let i=0;i<universe.length&&selected.length<LIMITS.deepBudget;i++){let sym=universe[(s.scheduleCursor+i)%universe.length];if(!selected.includes(sym))selected.push(sym)}s.scheduleCursor=(s.scheduleCursor+LIMITS.deepBudget)%universe.length;return selected}
function observeDepth(s,symbol,raw,trades,now){let book=E.snapshot(raw,now);if(!book.valid)return false;if(!s.markets[symbol]&&Object.keys(s.markets).length>=LIMITS.markets){let protectedSymbols=new Set(Object.values(s.studies).map(p=>p.symbol));for(let port of Object.values(s.epoch?.portfolios||{}))for(let p of Object.values(port.positions))protectedSymbols.add(p.symbol);let victim=Object.keys(s.markets).filter(k=>!protectedSymbols.has(k)).sort((a,b)=>(s.markets[a].depthAt||0)-(s.markets[b].depthAt||0))[0];if(!victim)return false;delete s.markets[victim]}let m=s.markets[symbol]||(s.markets[symbol]={history:[],observations:0}),mid=(book.bids[0][0]+book.asks[0][0])/2;m.flow=E.flow(trades,m.flow,mid,now);m.book=book;m.depthAt=now;return true}
function teacherTarget(s,r){let d=M.pooled(s.labels.filter(x=>x.id!==r.id),r),slow=M.predict(s.models[r.h],r.x),fast=M.predict(s.fast[r.h],r.x);return .4*d.mean+.4*slow+.2*fast}
function mature(s,st,item,p,now){item.done=true;if(!st.valid){s.rejected++;event(s,'LABEL_REJECTED',now,{id:st.id,h:item.h,reason:'OBSERVATION_GAP'});return}let y=(p/st.price-1)*100-.2;let r={id:st.id,h:item.h,tf:st.tf,symbol:st.symbol,liq:st.liq,regime:st.regime,x:st.x.slice(),featureAt:st.at,due:item.due,observedAt:now,y,mfe:st.max,mae:st.min,first:st.first,hitMs:st.hitMs,quality:'OBSERVED_PATH_APPROXIMATION',targetKind:'MID_MINUS_FEES_NOT_EXECUTABLE'};
 if(!st.counted){s.uniqueEvidence++;st.counted=true;let b=String(Math.floor(st.at/DAY));s.blocks[b]=(s.blocks[b]||0)+1;let keys=Object.keys(s.blocks).sort();while(keys.length>366)delete s.blocks[keys.shift()]}
 // Prequential predictions and distillation targets computed before this record trains a teacher.
 let target=teacherTarget(s,r),before=M.predict(s.models[item.h],r.x);M.fit(s.student[item.h],r.x,target,.01);s.teacherUpdates++;
 M.fit(s.models[item.h],r.x,y,.01);M.fit(s.fast[item.h],r.x,y,.06);s.labels.push(r);if(s.labels.length>LIMITS.labels)s.labels.shift();s.labelCount++;event(s,'MATURE_LABEL',now,{id:st.id,h:item.h,y,predictionBefore:before,teacherTarget:target,featureAt:st.at,due:item.due,quality:r.quality,mfe:r.mfe,mae:r.mae,first:r.first,hitMs:r.hitMs});
}
function marked(port,s,now){let equity=port.cash,valid=true;for(let p of Object.values(port.positions)){let f=E.fill(s.markets[p.symbol]?.book,'SELL',p.quantity,now);if(f.valid&&f.complete){equity+=f.cash;p.mark=f.cash;p.markAt=now}else{equity+=p.mark??p.basis;valid=false}}port.equity=equity;return valid}
function correlationFor(s,a,b){let aa=s.markets[a]?.history||[],bb=s.markets[b]?.history||[],map=new Map(bb.map(x=>[x.t,x.r])),paired=aa.filter(x=>map.has(x.t));return M.correlation(paired.map(x=>x.r),paired.map(x=>map.get(x.t)))}
function openPortfolios(s,st,now){let epoch=s.epoch;if(st.portfolioTried||!epoch)return;let book=s.markets[st.symbol]?.book;if(st.ms<900000||now-st.at>60000||st.at+4*st.ms>epoch.end){st.portfolioTried=true;event(s,'PORTFOLIO_SKIP',now,{id:st.id,reason:'FRAME_OR_DEPTH_OR_DEADLINE'});return}if(!book?.valid||book.at>now||now-book.at>60000)return;st.portfolioTried=true;let reference=epoch.portfolios.HOLD,existing=Object.values(reference.positions);if(existing.length>=LIMITS.positions||existing.some(p=>p.symbol===st.symbol)){event(s,'PORTFOLIO_SKIP',now,{id:st.id,reason:'CAPACITY_OR_SYMBOL_CONCENTRATION'});return}let correlated=existing.filter(p=>{let c=correlationFor(s,p.symbol,st.symbol);return c===null||c>.7}).length;if(correlated>=4){event(s,'PORTFOLIO_SKIP',now,{id:st.id,reason:'CORRELATED_OR_UNKNOWN_EXPOSURE'});return}
 let price=book.asks[0][0],budget=500,quantity=budget/(price*1.003),f=E.fill(book,'BUY',quantity,now);if(!f.valid||!f.complete||f.cash>budget){event(s,'PORTFOLIO_SKIP',now,{id:st.id,reason:'INSUFFICIENT_DEPTH'});return}epoch.admitted++;
 for(let policy of POLICIES){let port=epoch.portfolios[policy];if(port.cash<f.cash)continue;port.cash-=f.cash;port.fees+=f.fee;port.positions[st.id]={id:st.id,symbol:st.symbol,tf:st.tf,liq:st.liq,ms:st.ms,at:now,end:st.at+4*st.ms,quantity:f.filled,basis:f.cash,lastReview:now,weak:0,partial:false,mark:f.cash,markAt:now};event(s,'SHADOW_BUY',now,{policy,id:st.id,quantity:f.filled,cash:f.cash,epoch:epoch.id,modelCutoff:epoch.modelCutoff})}
}
function stoppingAction(f,policy,position,now){if(now>=position.end)return {action:'EXIT',fraction:1,reason:'COMMON_HORIZON'};if(policy==='HOLD'||!f.ready)return {action:'HOLD',fraction:0,reason:!f.ready?'INSUFFICIENT_EVIDENCE':'FROZEN_REFERENCE'};
 // Forecast is incremental mid return minus round-trip fees. A held position owes only exit fees,
 // already in both alternatives, so add back the .20 training convention. Do not charge entry twice.
 let gain=(policy==='STUDENT'?f.student:f.teacher)+.2,risk=.25*Math.max(0,-f.q10)+f.uncertainty,hold=gain-risk,exit=0,partial=.5*gain-.25*risk-.02;
 if(hold<exit-.05)position.weak++;else position.weak=0;
 if(position.weak<2)return {action:'HOLD',fraction:0,reason:'HYSTERESIS',hold,exit,partial};
 if(policy==='PARTIAL'&&!position.partial&&partial>Math.max(exit,hold)+.02)return {action:'PARTIAL',fraction:.5,reason:'REDUCE_DOWNSIDE',hold,exit,partial};return {action:'EXIT',fraction:1,reason:'INCREMENTAL_UTILITY_NEGATIVE',hold,exit,partial};
}
function reviewPortfolios(s,now){let epoch=s.epoch;if(!epoch)return;for(let policy of POLICIES){let port=epoch.portfolios[policy];for(let p of Object.values(port.positions)){if(now>p.end+90000){port.valid=false;epoch.quality=false}if(now<p.end&&now-p.lastReview<Math.max(120000,p.ms/4))continue;let market=s.markets[p.symbol];let liquidate=E.fill(market?.book,'SELL',p.quantity,now);if(!liquidate.valid||!liquidate.complete){if(now>=p.end+90000){port.valid=false;epoch.quality=false}continue}p.lastReview=now;let st=s.studies[p.id],x=features(market?.row||{radarScore:50},market,s,epoch.frozen.ssl),remaining=(p.end-now)/p.ms,h=HORIZONS.reduce((a,b)=>Math.abs(b-remaining)<Math.abs(a-remaining)?b:a,1),f=forecast(s,{symbol:p.symbol,tf:p.tf,liq:p.liq,h},x,epoch.frozen),a=stoppingAction(f,policy,p,now);event(s,'SHADOW_REVIEW',now,{policy,id:p.id,epoch:epoch.id,...a,horizonModel:h,remainingFrames:remaining});if(a.fraction>0){let sold=p.quantity*a.fraction,f=E.fill(market.book,'SELL',sold,now);if(!f.valid||!f.complete)continue;let basis=p.basis*a.fraction;port.cash+=f.cash;port.fees+=f.fee;port.realized+=f.cash-basis;port.actions++;p.quantity-=sold;p.basis-=basis;p.partial=true;if(p.quantity<1e-12)delete port.positions[p.id]}}
 port.markFresh=marked(port,s,now);
 }
 if(now>=epoch.end){let valid=epoch.quality&&Object.values(epoch.portfolios).every(p=>p.valid&&!Object.keys(p.positions).length),result={id:epoch.id,start:epoch.start,end:now,valid,admitted:epoch.admitted,portfolios:Object.fromEntries(POLICIES.map(k=>[k,{cash:epoch.portfolios[k].cash,equity:epoch.portfolios[k].equity,returnPct:(epoch.portfolios[k].equity/10000-1)*100,fees:epoch.portfolios[k].fees,realized:epoch.portfolios[k].realized}]))};if(valid&&epoch.admitted){for(let k of POLICIES.slice(1)){if(s.proof[k].length<2048)s.proof[k].push(result.portfolios[k].returnPct-result.portfolios.HOLD.returnPct)}}s.lastEpoch=result;event(s,'EPOCH_CLOSED',now,result);startEpoch(s,now)}
}
function advance(s,tickers,rows={},now=Date.now()){if(now<=s.lastAt)return s;if(!s.epoch)startEpoch(s,now);let previousAt=s.lastAt;if(now-previousAt>90000&&Object.values(s.epoch.portfolios).some(p=>Object.keys(p.positions).length))s.epoch.quality=false;s.lastAt=now;let tracked=new Set([...Object.values(s.studies).map(p=>p.symbol),...Object.keys(s.markets)]),returns=[];for(let symbol of tracked){let q=tickers.get(symbol),price=+q?.lastPrice;if(!(price>0))continue;let m=s.markets[symbol]||(s.markets[symbol]={history:[],observations:0}),r=m.price>0?(price/m.price-1)*100:0;let row=rows[symbol]||m.row||{},rawX=features(row,m,s,null);if(m.rawX&&m.at>=s.startedAt&&now-m.at<=90000){M.fit(s.ssl,m.rawX,M.clamp(r,-5,5),.02);s.sslUpdates++}m.rawX=rawX;m.row={radarScore:row.radarScore,relativeVolume:row.relativeVolume,alignedPressure:row.alignedPressure};m.x=features(row,m,s);m.price=price;m.at=now;m.liq=liquidity(q);m.observations++;m.history.push({t:now,r});if(m.history.length>96)m.history.shift();returns.push(r)}regime(s,returns);
 for(let st of Object.values(s.studies)){let q=tickers.get(st.symbol),p=+q?.lastPrice;if(!(p>0)){if(now-st.lastAt>90000)st.valid=false;if(now>=st.at+4*st.ms+90000){s.rejected+=st.horizons.filter(h=>!h.done).length;event(s,'PATH_EXPIRED',now,{id:st.id,reason:'MISSING_PRICE'});delete s.studies[st.id]}continue}if(now-st.lastAt>90000)st.valid=false;let move=(p/st.price-1)*100;st.max=Math.max(st.max,move);st.min=Math.min(st.min,move);if(!st.first&&(move>=3||move<=-2)){st.first=move>=3?'TARGET':'LOSS';if(move>=3)st.hitMs=now-st.at}st.lastAt=now;st.lastPrice=p;openPortfolios(s,st,now);for(let item of st.horizons)if(!item.done&&now>=item.due)mature(s,st,item,p,now);if(st.horizons.every(h=>h.done))delete s.studies[st.id]}
 for(let sample of M.replay(s.labels,s.models,Math.random,8)){M.fit(s.models[sample.row.h],sample.row.x,sample.row.y,.005,sample.importance);s.replayUpdates++}reviewPortfolios(s,now);
 let protectedSymbols=new Set(Object.values(s.studies).map(p=>p.symbol));for(let p of Object.values(s.epoch?.portfolios||{}))for(let pos of Object.values(p.positions))protectedSymbols.add(pos.symbol);let keys=Object.keys(s.markets).sort((a,b)=>(s.markets[a].at||0)-(s.markets[b].at||0));for(let key of keys){if(Object.keys(s.markets).length<=LIMITS.markets)break;if(!protectedSymbols.has(key))delete s.markets[key]}
 if(now-previousAt>90000)event(s,'OBSERVATION_GAP',now,{gapMs:now-previousAt});return s;
}
function publicState(s){return {version:VERSION,mode:'PROSPECTIVE_SHADOW_ONLY',automaticPromotion:false,startedAt:s.startedAt,uniqueEvidence:s.uniqueEvidence,labelCount:s.labelCount,independentTimeBlocks:Object.keys(s.blocks).length,replayUpdates:s.replayUpdates,teacherUpdates:s.teacherUpdates,sslUpdates:s.sslUpdates,rejected:s.rejected,capacityRejected:s.capacityRejected,pending:Object.keys(s.studies).length,regime:s.regime,proof:Object.fromEntries(POLICIES.slice(1).map(k=>[k,M.proof(s.proof[k])])),portfolios:s.epoch?Object.fromEntries(POLICIES.map(k=>{let p=s.epoch.portfolios[k];return [k,{equity:p.equity,cash:p.cash,realized:p.realized,unrealized:p.equity-p.cash-Object.values(p.positions).reduce((a,b)=>a+b.basis,0),fees:p.fees,positions:Object.keys(p.positions).length,valid:p.valid,markFresh:p.markFresh!==false}]})):null,epoch:s.epoch?{id:s.epoch.id,start:s.epoch.start,end:s.epoch.end,modelCutoff:s.epoch.modelCutoff,quality:s.epoch.quality}:null,lastEpoch:s.lastEpoch,distributions:HORIZONS.map(h=>({h,...M.distribution(s.labels.filter(r=>r.h===h))})),recent:s.events.slice(-24)}}
return {VERSION,LIMITS,HORIZONS,POLICIES,frame,create,validate,register,schedule,observeDepth,advance,forecast,stoppingAction,publicState,features,startEpoch,reviewPortfolios,correlationFor};
});
