
"use strict";
const http=require('http'), fs=require('fs'), path=require('path');
const PORT=Number(process.env.PORT||3000), ROOT=__dirname, PUBLIC=path.join(ROOT,'public');
const DATA_DIR=process.env.DATA_DIR || (fs.existsSync('/data')?'/data':path.join(ROOT,'data'));
fs.mkdirSync(DATA_DIR,{recursive:true});
const STATE_FILE=path.join(DATA_DIR,'state.json');
const VERSION='8.1.0-CLOUD-24X7-TELEGRAM';
const SPOT_BASES=['https://data-api.binance.vision','https://api.binance.com','https://api-gcp.binance.com','https://api1.binance.com','https://api2.binance.com','https://api3.binance.com','https://api4.binance.com'];
const TELEGRAM_TOKEN=String(process.env.ALPHAPROOF_TELEGRAM_TOKEN||process.env.NEXTMOVE_TELEGRAM_TOKEN||'').trim();
const TELEGRAM_CHAT_ID=String(process.env.ALPHAPROOF_TELEGRAM_CHAT_ID||process.env.NEXTMOVE_TELEGRAM_CHAT_ID||'').trim();
const TELEGRAM_ENABLED=!!(TELEGRAM_TOKEN&&TELEGRAM_CHAT_ID);

function trendBreakLabel(dir){return dir==='SHORT'?'اختراق ترند صاعد':'اختراق ترند هابط'}
function tgFmt(v){v=Number(v);if(!Number.isFinite(v))return '—';let a=Math.abs(v);if(a>=1000)return v.toFixed(2);if(a>=1)return v.toFixed(6).replace(/0+$/,'').replace(/\.$/,'');return v.toPrecision(7).replace(/0+$/,'').replace(/\.$/,'')}
function tgTime(t){try{return new Date(t).toLocaleString('ar-SA',{timeZone:'Asia/Riyadh'})}catch{return new Date(t).toISOString()}}
async function sendTelegram(text){if(!TELEGRAM_ENABLED)return {ok:false,skipped:true};try{let r=await fetch(`https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:TELEGRAM_CHAT_ID,text,disable_web_page_preview:true})});let j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw new Error(j.description||`Telegram HTTP ${r.status}`);return {ok:true}}catch(e){console.error('telegram',e.message);state.meta.lastTelegramError=e.message;persist();return {ok:false,error:e.message}}}
function radarEntryMessage(w){let d=w.dir==='LONG'?'🟢 LONG':'🔴 SHORT',br=w.dir==='LONG'?'📈':'📉';return `🧬 ALPHA PROOF | ألفا بروف
🟢 فرصة جديدة دخلت الرادار

العملة: ${w.symbol}
الاتجاه: ${d}
الفريم: ${w.tf}
السعر عند دخول الرادار: ${tgFmt(w.entryPrice)}
${br} ${trendBreakLabel(w.dir)}: ✅
📊 اختراق Volume EMA${w.volumeEmaLength||400}: ✅
🎯 الهدف: ${tgFmt(w.targetPrice)} (+${Number(w.acceptedTargetPct||0).toFixed(2)}%)
🛑 وقف الخسارة: ${tgFmt(w.stopPrice)}
🕒 وقت الدخول: ${tgTime(w.entryAt)}

📡 تتم متابعتها الآن بواسطة Alpha Proof`}
function tradeExitMessage(w,reason,price,now){let isTP=reason==='TP',icon=isTP?'🎯':'🛑',title=isTP?'تحقق الهدف':'وقف الخسارة',d=w.dir==='LONG'?'🟢 LONG':'🔴 SHORT',move=w.entryPrice?((price/w.entryPrice)-1)*100:0,signed=w.dir==='LONG'?move:-move;return `🧬 ALPHA PROOF | ألفا بروف
${icon} ${title}

العملة: ${w.symbol}
الاتجاه: ${d}
الفريم: ${w.tf}
سعر دخول الرادار: ${tgFmt(w.entryPrice)}
سعر الخروج: ${tgFmt(price)}
الحركة منذ دخول الرادار: ${signed>=0?'+':''}${signed.toFixed(2)}%
🎯 الهدف: ${tgFmt(w.targetPrice)}
🛑 وقف الخسارة: ${tgFmt(w.stopPrice)}
🕒 وقت الخروج: ${tgTime(now)}

🧬 ALPHA PROOF`}
const defaults={scanMode:'manual',autoScanMin:5,tf:'4h',directionMode:'both',barMode:'closed',candleLimit:500,concurrency:4,sortMode:'scoreDesc',excludeTokenizedStocks:true,stockBases:'AAPL,TSLA,MSFT,AMZN,GOOG,GOOGL,META,NVDA,NFLX,COIN,MSTR,SPY,QQQ,AMD,INTC,BA,BABA,DIS,PYPL,NKE,SBUX',paEnabled:true,paLookback:5,paMinDir:4,paDirMetric:'body',paStructureMode:'both',paMinStructure:0,paDoji:'ignore',expEnabled:true,expMetric:'range',expMode:'expansion',expFast:3,expBase:10,expBaseMode:'include',expThreshold1:1.25,expThreshold2:2,emaEnabled:true,emaLength:200,emaRule:'side',emaSlopeBars:5,emaMinSlope:0,emaMinDistance:0,emaMaxDistance:0,trendEnabled:true,trendLookback:24,trendMult:1.4,trendMethod:'atr',trendMaxBars:20,volEmaLength:400,targetTolerance:.10,slPivotStrength:2,slSearchBars:30,liveEnabled:true,liveSec:30,liveWindowMin:30,liveMinQuoteVol:0,liveVolNorm:3,liveSpeedNorm:.1,liveDeltaWeight:60,liveSpeedWeight:40};
let state={settings:{...defaults},results:[],universe:[],errors:0,liveRows:[],liveHistory:{},active:{},closed:[],hiddenResearch:{},lastScanAt:null,meta:{scanning:false,progress:0,scanMessage:'الخادم جاهز',lastError:null,lastAdded:0,analyzedCount:0,universeCount:0}};
try{if(fs.existsSync(STATE_FILE)){let x=JSON.parse(fs.readFileSync(STATE_FILE,'utf8'));state={...state,...x,settings:{...defaults,...(x.settings||{})},meta:{...state.meta,...(x.meta||{}),scanning:false}}}}catch(e){console.error('state load',e)}
let savePending=null, autoTimer=null, liveTimer=null;
function persist(){clearTimeout(savePending);savePending=setTimeout(()=>{try{let cp={...state,closed:(state.closed||[]).slice(-5000),meta:{...state.meta,scanning:false}};fs.writeFileSync(STATE_FILE+'.tmp',JSON.stringify(cp));fs.renameSync(STATE_FILE+'.tmp',STATE_FILE)}catch(e){console.error('persist',e)}},150)}
function n(v,d=0){v=Number(v);return Number.isFinite(v)?v:d} function clamp(x,a,b){return Math.max(a,Math.min(b,x))} function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:0}
function timeframeHours(tf){let m=/^(\d+)([mhd])$/.exec(tf);if(!m)return 4;let v=+m[1];return m[2]==='m'?v/60:m[2]==='d'?v*24:v} function targetPct(tf){return 3*timeframeHours(tf)} function acceptedTargetPct(tf,C){return Math.max(0,targetPct(tf)-C.targetTolerance)} function targetFromBreak(z,dir,p){return dir==='LONG'?z.l*(1+p/100):z.h*(1-p/100)}
async function fetchJSON(p){let last;for(const base of SPOT_BASES){try{let r=await fetch(base+p,{headers:{'User-Agent':'AlphaProofCloud/8.0'}});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}catch(e){last=e}}throw last||new Error('Binance unavailable')}
function stockSet(C){return new Set(String(C.stockBases||'').split(/[\s,;|]+/).map(x=>x.trim().toUpperCase()).filter(Boolean))} function isTokenizedStock(s,C){if(!C.excludeTokenizedStocks)return false;let set=stockSet(C),b=String(s.baseAsset||'').toUpperCase();if(set.has(b))return true;for(let t of set)if(b===t+'X'||b===t+'ON'||b===t+'TOKEN')return true;return false}
function parseKlines(a){return a.map(z=>({t:+z[0],o:+z[1],h:+z[2],l:+z[3],c:+z[4],v:+z[5],T:+z[6]}))} function ema(vals,p){if(!vals.length)return[];let a=2/(p+1),out=new Array(vals.length),e=vals[0];for(let i=0;i<vals.length;i++){e=i===0?vals[i]:vals[i]*a+e*(1-a);out[i]=e}return out} function candleMetric(z,metric){let base=z.o||z.c||1;return metric==='body'?Math.abs(z.c-z.o)/base*100:(z.h-z.l)/base*100}
function analyzePA(c,i,dir,C){let N=C.paLookback,start=i-N+1;if(start<1)return {pass:false,dirCount:0,lookback:N,dirRatio:0,structurePct:0};let dirCount=0,doji=0,structHits=0,structTotal=0;for(let k=start;k<=i;k++){let z=c[k],p=c[k-1],up=C.paDirMetric==='prevClose'?z.c>p.c:z.c>z.o,down=C.paDirMetric==='prevClose'?z.c<p.c:z.c<z.o;if(up){if(dir==='LONG')dirCount++}else if(down){if(dir==='SHORT')dirCount++}else doji++;if(k>start&&C.paStructureMode!=='off'){let highHit=dir==='LONG'?z.h>p.h:z.h<p.h,lowHit=dir==='LONG'?z.l>p.l:z.l<p.l;if(C.paStructureMode==='both'||C.paStructureMode==='highs'){structHits+=highHit?1:0;structTotal++}if(C.paStructureMode==='both'||C.paStructureMode==='lows'){structHits+=lowHit?1:0;structTotal++}}}let structurePct=structTotal?structHits/structTotal*100:0,passDir=dirCount>=Math.min(C.paMinDir,N),passStructure=C.paStructureMode==='off'||C.paMinStructure<=0||structurePct>=C.paMinStructure;return {pass:passDir&&passStructure,dirCount,lookback:N,dirRatio:dirCount/N,structurePct,doji,passDir,passStructure,dirMetric:C.paDirMetric,structureMode:C.paStructureMode}}
function analyzeExpansion(c,i,C){let fast=C.expFast,base=C.expBase,fastStart=i-fast+1,refEnd=C.expBaseMode==='prior'?fastStart-1:i,refStart=refEnd-base+1;if(fastStart<0||refStart<0)return {pass:false,ratio:0,fastAvg:0,baseAvg:0};let fastVals=[],refVals=[];for(let k=fastStart;k<=i;k++)fastVals.push(candleMetric(c[k],C.expMetric));for(let k=refStart;k<=refEnd;k++)refVals.push(candleMetric(c[k],C.expMetric));let fa=mean(fastVals),ba=mean(refVals),ratio=ba>0?fa/ba:0,t1=Math.min(C.expThreshold1,C.expThreshold2),t2=Math.max(C.expThreshold1,C.expThreshold2),pass=C.expMode==='compression'?ratio<=C.expThreshold1:C.expMode==='between'?(ratio>=t1&&ratio<=t2):ratio>=C.expThreshold1;return {pass,ratio,fastAvg:fa,baseAvg:ba,metric:C.expMetric,fast,base,mode:C.expMode,baseMode:C.expBaseMode,t1:C.expThreshold1,t2:C.expThreshold2}}
function analyzeEMA(c,i,dir,C){let E=ema(c.map(z=>z.c),C.emaLength),cur=E[i],prev=E[Math.max(0,i-C.emaSlopeBars)],price=c[i].c,dist=(price/cur-1)*100,slope=(cur/prev-1)*100,sidePass=dir==='LONG'?price>cur:price<cur,slopeDirPass=dir==='LONG'?slope>=0:slope<=0,slopeMagPass=Math.abs(slope)>=C.emaMinSlope,slopePass=slopeDirPass&&slopeMagPass,absDist=Math.abs(dist),minDistPass=absDist>=C.emaMinDistance,maxDistPass=C.emaMaxDistance<=0||absDist<=C.emaMaxDistance,rulePass=C.emaRule==='side'?sidePass:C.emaRule==='slope'?slopePass:(sidePass&&slopePass);return {pass:rulePass&&minDistPass&&maxDistPass,ema:cur,dist,slope,sidePass,slopePass,minDistPass,maxDistPass}}
function trSeries(c){let out=[];for(let i=0;i<c.length;i++){let pc=i?c[i-1].c:c[i].c;out.push(Math.max(c[i].h-c[i].l,Math.abs(c[i].h-pc),Math.abs(c[i].l-pc)))}return out} function rma(vals,p){let out=new Array(vals.length).fill(null);if(vals.length<p)return out;let seed=mean(vals.slice(0,p));out[p-1]=seed;for(let i=p;i<vals.length;i++)out[i]=(out[i-1]*(p-1)+vals[i])/p;return out} function pivotAt(c,confirmIndex,L,isHigh){let p=confirmIndex-L;if(p<L||p+L>=c.length)return null;let v=isHigh?c[p].h:c[p].l;for(let k=p-L;k<=p+L;k++){if(k===p)continue;if(isHigh?c[k].h>=v:c[k].l<=v)return null}return {pivotIndex:p,price:v,confirmIndex}}
function luxBreakEvents(c,L,mult){let ATR=rma(trSeries(c),L),upper=null,lower=null,slopePH=0,slopePL=0,upos=0,dnos=0,prevU=0,prevD=0,events=[];for(let i=0;i<c.length;i++){let ph=pivotAt(c,i,L,true),pl=pivotAt(c,i,L,false),s=ATR[i]==null?null:ATR[i]/L*mult;if(ph){upper=ph.price;if(s!=null)slopePH=s;upos=0}else if(upper!=null)upper-=slopePH;if(pl){lower=pl.price;if(s!=null)slopePL=s;dnos=0}else if(lower!=null)lower+=slopePL;let upLine=upper==null?null:upper-slopePH*L,dnLine=lower==null?null:lower+slopePL*L;if(!ph&&upLine!=null&&c[i].c>upLine)upos=1;if(!pl&&dnLine!=null&&c[i].c<dnLine)dnos=1;if(upos>prevU)events.push({dir:'LONG',index:i,time:c[i].t,price:c[i].c,line:upLine,atr:ATR[i],slope:slopePH});if(dnos>prevD)events.push({dir:'SHORT',index:i,time:c[i].t,price:c[i].c,line:dnLine,atr:ATR[i],slope:slopePL});prevU=upos;prevD=dnos}return events}
function localPivot(c,j,strength,isLow,maxRight){if(j-strength<0||j+strength>maxRight)return false;let v=isLow?c[j].l:c[j].h;for(let k=j-strength;k<=j+strength;k++){if(k===j)continue;if(isLow?c[k].l<=v:c[k].h>=v)return false}return true} function nearestStop(c,breakIndex,dir,C){let st=C.slPivotStrength,start=Math.max(0,breakIndex-C.slSearchBars);if(dir==='LONG'){for(let j=breakIndex-st;j>=start+st;j--)if(localPivot(c,j,st,true,breakIndex))return {price:c[j].l,index:j,method:'nearest-pivot'};let vals=c.slice(start,breakIndex+1),mn=Math.min(...vals.map(z=>z.l));return {price:mn,index:start+vals.findIndex(z=>z.l===mn),method:'fallback-low'}}else{for(let j=breakIndex-st;j>=start+st;j--)if(localPivot(c,j,st,false,breakIndex))return {price:c[j].h,index:j,method:'nearest-pivot'};let vals=c.slice(start,breakIndex+1),mx=Math.max(...vals.map(z=>z.h));return {price:mx,index:start+vals.findIndex(z=>z.h===mx),method:'fallback-high'}}}
function analyzeTrend(c,i,dir,C,events){if(!C.trendEnabled)return {pass:true,disabled:true,breakIndex:null,breakBarsAgo:null,withinWindow:null,stop:null};let ev=[...events].reverse().find(e=>e.dir===dir&&e.index<=i);if(!ev)return {pass:false,disabled:false,breakIndex:null,breakBarsAgo:null,withinWindow:false,stop:null};let age=i-ev.index,sl=nearestStop(c,ev.index,dir,C);return {pass:true,disabled:false,breakIndex:ev.index,breakTime:ev.time,breakPrice:ev.price,line:ev.line,atr:ev.atr,slope:ev.slope,breakBarsAgo:age,withinWindow:age<=C.trendMaxBars,stop:sl}}
function strength(pa,ex,em,tr,C){let parts=[];if(C.paEnabled)parts.push(clamp(pa.dirRatio*100,0,100)*.55+clamp(pa.structurePct,0,100)*.45);if(C.expEnabled){let q=C.expMode==='compression'?(ex.ratio>0?C.expThreshold1/ex.ratio:2):C.expMode==='between'?1:ex.ratio/Math.max(C.expThreshold1,.0001);parts.push(clamp(q*65,0,100))}if(C.emaEnabled)parts.push(clamp(50+Math.min(35,Math.abs(em.dist)*5)+Math.min(15,Math.abs(em.slope)*20),0,100));return parts.length?mean(parts):50}
function radarEligibility(c,i,dir,C,tr){if(!C.trendEnabled)return {eligible:false,status:'LUX_OFF',reason:'اكتشاف اختراق الترند معطّل'};if(!tr||tr.breakIndex==null||!tr.stop||!Number.isFinite(tr.stop.price))return {eligible:false,status:'NO_BREAK',reason:'لا يوجد اختراق ترند/وقف صالح'};let bi=tr.breakIndex,bc=c[bi],theoryPct=targetPct(C.tf),acceptPct=acceptedTargetPct(C.tf,C),theoryTarget=targetFromBreak(bc,dir,theoryPct),acceptedTarget=targetFromBreak(bc,dir,acceptPct),stop=tr.stop.price;let V=ema(c.map(z=>z.v),C.volEmaLength),confirmIndex=null,confirmVol=null,confirmEma=null,firstOutcome=null;for(let k=bi;k<=i;k++){let hitTP=dir==='LONG'?c[k].h>=acceptedTarget:c[k].l<=acceptedTarget,hitSL=dir==='LONG'?c[k].l<=stop:c[k].h>=stop;if((hitTP||hitSL)&&!firstOutcome)firstOutcome={index:k,type:hitTP&&hitSL?'BOTH':hitTP?'TP':'SL',time:c[k].t};if(confirmIndex==null&&Number.isFinite(V[k])&&c[k].v>V[k]){confirmIndex=k;confirmVol=c[k].v;confirmEma=V[k]}}let common={breakAnchor:dir==='LONG'?bc.l:bc.h,theoryPct,acceptPct,theoryTarget,acceptedTarget,stop,confirmIndex,confirmTime:confirmIndex==null?null:c[confirmIndex].t,confirmVol,confirmEma,confirmBarsAfterBreak:confirmIndex==null?null:confirmIndex-bi};if(firstOutcome){let label=firstOutcome.type==='TP'?'الهدف تحقق':firstOutcome.type==='SL'?'وقف الخسارة تحقق':'TP وSL لُمسا';return {...common,eligible:false,status:firstOutcome.type+'_ALREADY',reason:`${label} قبل دخول الرادار`,firstOutcome}}if(confirmIndex==null)return {...common,eligible:false,status:'WAIT_VOL',reason:`لم يخترق Volume EMA${C.volEmaLength}`};return {...common,eligible:true,status:'READY',reason:`Volume اخترق EMA${C.volEmaLength} قبل TP/SL`}}
function analyzeDirection(c,i,dir,C,events){let pa=analyzePA(c,i,dir,C),ex=analyzeExpansion(c,i,C),em=analyzeEMA(c,i,dir,C),tr=analyzeTrend(c,i,dir,C,events),pass=(!C.paEnabled||pa.pass)&&(!C.expEnabled||ex.pass)&&(!C.emaEnabled||em.pass),radar=radarEligibility(c,i,dir,C,tr);return {dir,pass,pa,ex,em,tr,radar,score:strength(pa,ex,em,tr,C)}}
async function analyzeSymbol(symbol,C){let fetchLimit=Math.min(1000,Math.max(C.candleLimit,C.volEmaLength+100,C.trendLookback*4+100)),arr=await fetchJSON(`/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=${C.tf}&limit=${fetchLimit}`),c=parseKlines(arr),i=C.barMode==='live'?c.length-1:c.length-2,expNeed=C.expBaseMode==='prior'?C.expFast+C.expBase:C.expBase,trendNeed=C.trendEnabled?C.trendLookback*3+5:0,need=Math.max(C.paLookback,expNeed,C.emaLength+C.emaSlopeBars,trendNeed)+5;if(i<need)throw new Error('تاريخ غير كاف');let events=C.trendEnabled?luxBreakEvents(c,C.trendLookback,C.trendMult):[],dirs=C.directionMode==='both'?['LONG','SHORT']:[C.directionMode.toUpperCase()],tests=dirs.map(d=>analyzeDirection(c,i,d,C,events)),hits=tests.filter(x=>x.pass),poolx=hits.length?hits:tests;poolx.sort((a,b)=>b.score-a.score);let best=poolx[0];return {symbol,price:c[i].c,time:c[i].t,tf:C.tf,matched:hits.length>0,...best}}
async function pool(items,limit,fn,onProgress){let out=new Array(items.length),idx=0,done=0;async function worker(){while(true){let j=idx++;if(j>=items.length)return;try{out[j]=await fn(items[j],j)}catch(e){out[j]={error:e.message,symbol:items[j]}}done++;onProgress?.(done,items.length)}}await Promise.all(Array.from({length:Math.min(limit,items.length||1)},worker));return out}
function compactHiddenResearch(){let entries=Object.entries(state.hiddenResearch||{}).sort((a,b)=>(b[1]?.lastSeenAt||0)-(a[1]?.lastSeenAt||0)).slice(0,3000),out={};for(let [k,v] of entries){if(!v)continue;let z={...v};if(Array.isArray(z.observations))z.observations=z.observations.slice(-24);out[k]=z}state.hiddenResearch=out}
function hiddenStudyKey(x){return `${x.symbol}|${x.dir}|${x.tf}|${x?.tr?.breakTime??'NO_BREAK'}`} function hiddenSnapshot(x,scanAt){let r=x.radar||{},fo=r.firstOutcome||null;return {t:scanAt,price:x.price,score:x.score,paDir:x.pa?.dirCount??null,paLookback:x.pa?.lookback??null,paStructure:x.pa?.structurePct??null,ceRatio:x.ex?.ratio??null,emaDist:x.em?.dist??null,emaSlope:x.em?.slope??null,radarStatus:r.status||null,reason:r.reason||null,confirmTime:r.confirmTime||null,confirmBars:r.confirmBarsAfterBreak??null,firstOutcome:fo?{type:fo.type,time:fo.time,index:fo.index}:null}}
function recordHiddenResearch(matches,C,scanAt){for(let x of matches){if(state.active[x.symbol])continue;let r=x.radar||{},key=hiddenStudyKey(x),existing=state.hiddenResearch[key];if(r.eligible){if(existing){existing.lastSeenAt=scanAt;existing.promotedToRadarAt=scanAt;existing.finalState='PROMOTED_TO_RADAR';existing.observations=(existing.observations||[]).concat(hiddenSnapshot(x,scanAt)).slice(-24)}continue}if(!existing){existing=state.hiddenResearch[key]={key,symbol:x.symbol,dir:x.dir,tf:x.tf,discoveryTimeframe:x.tf,firstSeenAt:scanAt,lastSeenAt:scanAt,initialStatus:r.status||'UNKNOWN',initialReason:r.reason||'غير مؤهل للرادار',breakTime:x.tr?.breakTime||null,breakIndex:x.tr?.breakIndex??null,breakAnchor:r.breakAnchor??null,targetTheoryPct:r.theoryPct??null,targetAcceptPct:r.acceptPct??null,theoreticalTarget:r.theoryTarget??null,acceptedTarget:r.acceptedTarget??null,stop:r.stop??x.tr?.stop?.price??null,stopMethod:x.tr?.stop?.method||null,volumeEmaLength:C.volEmaLength,observations:[],finalState:null,outcome:null}}existing.lastSeenAt=scanAt;existing.latestStatus=r.status||null;existing.latestReason=r.reason||null;existing.observations=(existing.observations||[]).concat(hiddenSnapshot(x,scanAt)).slice(-24);if(r.firstOutcome){existing.outcome=r.firstOutcome.type;existing.outcomeAt=r.firstOutcome.time;existing.finalState=r.firstOutcome.type==='TP'?'REJECTED_THEN_TP':r.firstOutcome.type==='SL'?'REJECTED_THEN_SL':'REJECTED_BOTH_SAME_BAR'}else if(r.status==='NO_BREAK'||r.status==='LUX_OFF'){existing.finalState=r.status}else existing.finalState='OPEN_RESEARCH'}compactHiddenResearch()}
function liveBaseline(symbol,now,windowMin){let a=state.liveHistory[symbol]||[],cut=now-windowMin*60000,cand=a.filter(z=>z.t<=now&&z.t>=cut);return cand.length?cand[0]:(a.length?a[0]:null)} function activityStage(row){if(row.samples<2)return '⚪ خط أساس';if(row.volDeltaPct>=3||row.volSpeed>=.1)return '🔥 فوليوم يتسارع';if(row.volDeltaPct>0&&row.volSpeed>0)return '🟠 نشاط صاعد';if(row.volDeltaPct>0)return '🟡 فوليوم أعلى';if(row.volDeltaPct<0)return '⚪ نافذة 24h تتراجع';return '⚪ هادئ'}
function addMatchesToRadar(matches,tickerMap,C){let now=Date.now(),added=0;for(let x of matches){if(state.active[x.symbol]||!x.radar?.eligible)continue;let q=tickerMap.get(x.symbol),entry=n(q?.lastPrice,x.price),qv=n(q?.quoteVolume,0),r=x.radar,stop=n(r.stop,NaN),target=n(r.acceptedTarget,NaN);if(!Number.isFinite(stop)||!Number.isFinite(target))continue;state.active[x.symbol]={cycleId:`${x.symbol}-${now}`,symbol:x.symbol,dir:x.dir,tf:x.tf,entryAt:now,entryPrice:entry,entryQuoteVol:qv,targetPct:r.theoryPct,acceptedTargetPct:r.acceptPct,targetPrice:target,theoreticalTargetPrice:r.theoryTarget,targetAnchor:r.breakAnchor,stopPrice:stop,breakTime:x.tr?.breakTime||null,breakPrice:x.tr?.breakPrice||null,breakBarsAgoAtEntry:x.tr?.breakBarsAgo??null,volumeConfirmTime:r.confirmTime||null,volumeConfirmBarsAfterBreak:r.confirmBarsAfterBreak??null,volumeConfirmVol:r.confirmVol??null,volumeConfirmEma:r.confirmEma??null,volumeEmaLength:C.volEmaLength,stopMethod:x.tr?.stop?.method||'',setup:x,lastPrice:entry,lastQuoteVol:qv,lastCheckAt:now};state.liveHistory[x.symbol]=[{t:now,price:entry,quoteVol:qv}];sendTelegram(radarEntryMessage(state.active[x.symbol]));added++}return added}
function closeTrade(w,reason,price,quoteVol,now){state.closed.push({...w,exitAt:now,exitPrice:price,exitQuoteVol:quoteVol,result:reason});sendTelegram(tradeExitMessage(w,reason,price,now));delete state.active[w.symbol];delete state.liveHistory[w.symbol]}
async function updateLiveRadar(prefetched=null){let C=state.settings;if(!C.liveEnabled||!Object.keys(state.active).length){state.liveRows=[];return}let now=Date.now(),tickerMap=prefetched;if(!tickerMap){let all=await fetchJSON('/api/v3/ticker/24hr');tickerMap=new Map((Array.isArray(all)?all:[]).map(q=>[q.symbol,q]))}let rows=[];for(let w of Object.values(state.active)){let q=tickerMap.get(w.symbol);if(!q)continue;let price=n(q.lastPrice,w.lastPrice||w.entryPrice),quoteVol=n(q.quoteVolume,w.lastQuoteVol||0),hitTP=w.dir==='LONG'?price>=w.targetPrice:price<=w.targetPrice,hitSL=w.dir==='LONG'?price<=w.stopPrice:price>=w.stopPrice;if(hitTP||hitSL){closeTrade(w,hitTP?'TP':'SL',price,quoteVol,now);continue}let hist=state.liveHistory[w.symbol]||(state.liveHistory[w.symbol]=[]),base=liveBaseline(w.symbol,now,C.liveWindowMin),volDelta=base&&base.quoteVol?((quoteVol/base.quoteVol)-1)*100:0,mins=base?Math.max((now-base.t)/60000,.01):0,volSpeed=base?volDelta/mins:0;hist.push({t:now,price,quoteVol});state.liveHistory[w.symbol]=hist.filter(z=>z.t>=now-24*60*60000).slice(-500);let dw=C.liveDeltaWeight,sw=C.liveSpeedWeight,ws=dw+sw||1,deltaPart=clamp(Math.max(0,volDelta)/C.liveVolNorm*100,0,100),speedPart=clamp(Math.max(0,volSpeed)/C.liveSpeedNorm*100,0,100),activity=(deltaPart*dw+speedPart*sw)/ws;if(quoteVol<C.liveMinQuoteVol)activity*=quoteVol/Math.max(C.liveMinQuoteVol,1);w.lastPrice=price;w.lastQuoteVol=quoteVol;w.lastCheckAt=now;let row={...w,livePrice:price,quoteVol,volDeltaPct:volDelta,volSpeed,activityScore:clamp(activity,0,100),samples:state.liveHistory[w.symbol].length,liveAt:now};row.stage=activityStage(row);rows.push(row)}state.liveRows=rows.sort((a,b)=>b.activityScore-a.activityScore||b.volSpeed-a.volSpeed);persist()}
async function scan(fromAuto=false){if(state.meta.scanning)return false;state.meta.scanning=true;state.meta.lastError=null;state.meta.progress=2;state.meta.scanMessage='جلب قائمة Spot/USDT من Binance…';persist();try{let C=state.settings,exInfo=await fetchJSON('/api/v3/exchangeInfo'),universe=(exInfo.symbols||[]).filter(s=>s.status==='TRADING'&&s.quoteAsset==='USDT'&&s.isSpotTradingAllowed!==false&&!isTokenizedStock(s,C)).map(s=>s.symbol).sort();state.universe=universe;let activeSet=new Set(Object.keys(state.active)),scanUniverse=universe.filter(sym=>!activeSet.has(sym)),skippedActive=universe.length-scanUniverse.length;state.meta.universeCount=universe.length;state.meta.analyzedCount=0;let raw=await pool(scanUniverse,C.concurrency,s=>analyzeSymbol(s,C),(d,t)=>{state.meta.analyzedCount=d;state.meta.progress=4+(t?d/t:1)*90;state.meta.scanMessage=`تحليل ${d}/${t} — مستثنى ${skippedActive} داخل الرادار`;if(d%20===0)persist()}),errs=raw.filter(x=>x&&x.error),rows=raw.filter(x=>x&&!x.error);state.errors=errs.length;state.results=rows.filter(x=>x.matched);let cmp={scoreDesc:(a,b)=>b.score-a.score||b.ex.ratio-a.ex.ratio,scoreAsc:(a,b)=>a.score-b.score||a.ex.ratio-b.ex.ratio,ratioAsc:(a,b)=>a.ex.ratio-b.ex.ratio,ratioDesc:(a,b)=>b.ex.ratio-a.ex.ratio,ratioNear:(a,b)=>Math.abs(a.ex.ratio-C.expThreshold1)-Math.abs(b.ex.ratio-C.expThreshold1),symbol:(a,b)=>a.symbol.localeCompare(b.symbol)}[C.sortMode]||((a,b)=>b.score-a.score);state.results.sort(cmp);state.meta.progress=95;state.meta.scanMessage='فحص اختراق الترند → Volume EMA400 → TP/SL…';let allTicker=await fetchJSON('/api/v3/ticker/24hr'),tickerMap=new Map((Array.isArray(allTicker)?allTicker:[]).map(q=>[q.symbol,q])),scanAt=Date.now();recordHiddenResearch(state.results,C,scanAt);let added=addMatchesToRadar(state.results,tickerMap,C);state.lastScanAt=scanAt;state.meta.lastScanAt=scanAt;state.meta.lastAdded=added;await updateLiveRadar(tickerMap);state.meta.progress=100;state.meta.scanMessage=`اكتمل: ${state.results.length} مطابقة · ${added} جديدة للرادار · ${errs.length} أخطاء.`;persist();return true}catch(e){console.error('scan',e);state.meta.lastError=e.message;state.meta.scanMessage='فشل الفحص: '+e.message;persist();return false}finally{state.meta.scanning=false;persist()}}
function schedule(){clearInterval(autoTimer);clearInterval(liveTimer);let C=state.settings;if(C.scanMode==='auto')autoTimer=setInterval(()=>scan(true),Math.max(1,C.autoScanMin)*60000);if(C.liveEnabled)liveTimer=setInterval(()=>updateLiveRadar().catch(e=>{state.meta.lastError='Radar: '+e.message;persist()}),Math.max(15,C.liveSec)*1000)}
schedule(); setTimeout(()=>updateLiveRadar().catch(()=>{}),3000);
function publicState(){return {version:VERSION,settings:state.settings,results:state.results,active:state.active,liveRows:state.liveRows,closed:state.closed,meta:{...state.meta,lastScanAt:state.lastScanAt,universeCount:state.universe.length,activeCount:Object.keys(state.active).length,hiddenResearchCount:Object.keys(state.hiddenResearch).length}}}
function send(res,code,data,type='application/json; charset=utf-8'){res.writeHead(code,{'Content-Type':type,'Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'});res.end(typeof data==='string'?data:JSON.stringify(data))}
function readBody(req){return new Promise((resolve,reject)=>{let b='';req.on('data',d=>{b+=d;if(b.length>2e6)req.destroy()});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}});req.on('error',reject)})}
const server=http.createServer(async(req,res)=>{try{let u=new URL(req.url,'http://x');if(req.method==='OPTIONS')return send(res,204,'','text/plain');if(u.pathname==='/health')return send(res,200,{ok:true,version:VERSION,scanning:state.meta.scanning,lastScanAt:state.lastScanAt,active:Object.keys(state.active).length,telegramConfigured:TELEGRAM_ENABLED});if(u.pathname==='/api/state'&&req.method==='GET')return send(res,200,publicState());if(u.pathname==='/api/settings'&&req.method==='POST'){let b=await readBody(req);state.settings={...defaults,...b};persist();schedule();return send(res,200,{ok:true,settings:state.settings})}if(u.pathname==='/api/scan'&&req.method==='POST'){if(state.meta.scanning)return send(res,409,{ok:false,error:'scan already running'});scan(false);return send(res,202,{ok:true,started:true})}if(u.pathname==='/api/telegram/test'&&req.method==='POST'){if(!TELEGRAM_ENABLED)return send(res,400,{ok:false,error:'Telegram variables are not configured'});let r=await sendTelegram('🧬 ALPHA PROOF | ألفا بروف\n✅ تم ربط Telegram بنجاح.\nهذه رسالة اختبار من خدمة Alpha Proof على Railway.');return send(res,r.ok?200:500,r)}if(u.pathname==='/api/export'&&req.method==='GET'){let payload={app:'ALPHA PROOF PA×C/E×EMA×TREND CLOUD',version:VERSION,exportedAt:new Date().toISOString(),settings:state.settings,universeCount:state.universe.length,lastScanResults:state.results,activeRadar:state.active,liveRadar:state.liveRows,volumeHistory:state.liveHistory,closedTrades:state.closed,hiddenRejectedResearch:state.hiddenResearch};res.writeHead(200,{'Content-Type':'application/json; charset=utf-8','Content-Disposition':`attachment; filename="alpha-proof-cloud-${state.settings.tf}-${new Date().toISOString().slice(0,10)}.json"`,'Cache-Control':'no-store'});return res.end(JSON.stringify(payload,null,2))}let file=u.pathname==='/'?path.join(PUBLIC,'index.html'):path.join(PUBLIC,u.pathname.replace(/^\//,''));if(!file.startsWith(PUBLIC)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return send(res,404,'Not found','text/plain; charset=utf-8');let ext=path.extname(file),types={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':'no-cache'});fs.createReadStream(file).pipe(res)}catch(e){console.error(e);send(res,500,{error:e.message})}});
server.listen(PORT,'0.0.0.0',()=>console.log(`ALPHA PROOF Cloud ${VERSION} on :${PORT} data=${DATA_DIR}`));
