'use strict';
const assert=require('assert');
const fs=require('fs');
const AI=require('./lab-ai.js');
const now=Date.now();
function row(over={}){return {cycleId:'CASE-'+Math.random(),symbol:'TESTUSDT',dir:'LONG',tf:'4h',entryAt:now+1000,entryPrice:100,lastPrice:100,targetPrice:110,stopPrice:95,dataStale:false,radarScore:84,flow:{minutes:60,volume:900000,directionalVolume:600000,net:300000,relative:3.2,pressure:66,persistence:72,impact:3.4,move:1.1,speed:.45,acceleration:.05,score:84,eligible:true,alive:true,measuredAt:now},support:{pa:{enabled:true,pass:true},ce:{enabled:true,pass:true},ema:{enabled:true,pass:true}},...over}}
const market={direction:'UP',upPct:65,downPct:30,medianChangePct:1.1,updatedAt:now,fearGreed:{value:63},marketAI:{featureSchema:'MARKET-FEATURES-V1',modelVersion:'MARKET-AI-001',regime:'TURNING_UP',currentDirection:'UP',forecast60:{direction:'UP',confidence:.78,ready:true,samples:80}}};
let s=AI.initialState(now);assert.equal(AI.MODEL_VERSION,'SHADOW-AI-005-NET-PNL');assert.equal(s.featureSchema,'FEATURES-V3-ECONOMICS');assert.equal(AI.SPOT_ENTRY_FEE_PCT,.10);assert.equal(AI.SPOT_EXIT_FEE_PCT,.10);assert.equal(AI.SPOT_ROUND_TRIP_FEE_PCT,.20);assert(s.lineageId);
let mfLong=AI.extractFeatures(row({dir:'LONG'}),market),mfShort=AI.extractFeatures(row({dir:'SHORT'}),market);assert(mfLong.marketForecast>0&&mfLong.marketTurning>0&&mfLong.marketAgreement>0,'ready bullish Market AI must align a LONG feature');assert(mfShort.marketForecast<0&&mfShort.marketTurning<0&&mfShort.marketAgreement<0,'same market forecast must oppose a SHORT');let cold=AI.extractFeatures(row(),{...market,marketAI:{...market.marketAI,forecast60:{direction:'UP',confidence:.9,ready:false,samples:10}}});assert.equal(cold.marketForecast,0,'Trade AI must ignore Market AI forecast before readiness');

assert(['net24h','dayVsHistory','profitBalance24h'].every(k=>AI.FEATURE_NAMES.includes(k)),'24h portfolio context must be part of Trade AI features');
let goodGeo=AI.executionGeometry('LONG',100,100.5,99);assert(goodGeo.valid&&goodGeo.economicallyViableTarget&&Math.abs(goodGeo.targetNetPct-.3)<1e-9);
let badGeo=AI.executionGeometry('LONG',100,99.8,99);assert(!badGeo.valid&&badGeo.reason==='LEVELS_WRONG_SIDE','wrong-side target must be rejected before Shadow execution');
let invalid=AI.decide(AI.initialState(now),row({cycleId:'INVALID',targetPrice:99.8,stopPrice:99}),market,now+1500,100);assert.equal(invalid.shadow.status,'REJECTED');assert.equal(invalid.shadow.finalDecision,'IGNORE');assert.equal(invalid.shadow.reason,'INVALID_EXECUTION_GEOMETRY');assert.equal(invalid.state.modelSamples,0);
let tinyW=row({cycleId:'TINY',entryPrice:100,targetPrice:100.1,stopPrice:99}),tinyD=AI.decide(AI.initialState(now),tinyW,market,now+1600,100);assert.equal(tinyD.shadow.finalDecision,'SKIP');assert.equal(tinyD.shadow.modelDecision,'ENTER');assert.equal(tinyD.shadow.decisionReason,'TARGET_DOES_NOT_COVER_SPOT_FEES','target below the 0.20% round trip cost must be economically gated');let forcedTiny={...tinyD.shadow,status:'OPEN',finalDecision:'ENTER'},tinyR=AI.resolveShadow(forcedTiny,tinyW,'TP',100.1,now+1700);assert.equal(tinyR.outcome.counterfactual,'TP');assert(Math.abs(tinyR.outcome.grossMovePct-.1)<1e-9);assert(Math.abs(tinyR.outcome.netPnlPct-(-.1))<1e-9);assert.equal(tinyR.outcome.winLabel,0,'touching TP must still be a LOSS if fees make net PnL negative');assert(tinyR.outcome.economicSoftTarget<.5,'net loss must create a sub-50% economic learning target');assert(tinyR.outcome.economicWeight>=AI.ECONOMIC_WEIGHT_BASE_PCT,'economic learning must expose magnitude weight');
let frozen={status:'OPEN',direction:'LONG',targetPrice:101,stopPrice:99};assert.equal(AI.shadowBarrier(frozen,100.5),null);assert.equal(AI.shadowBarrier(frozen,101).reason,'TP');assert.equal(AI.shadowBarrier({...frozen,direction:'SHORT',targetPrice:99,stopPrice:101},99).reason,'TP');

let a=AI.decide(s,row(),market,now+2000,100.2);s=a.state;assert(a.created&&a.shadow.finalDecision==='ENTER');assert(a.shadow.challengers?.BASE_AI&&a.shadow.challengers?.CORTEX_AI,'Trade AI must preserve Base/CORTEX challenger comparison');assert(a.shadow.confidence>=AI.PRIMARY_THRESHOLD);assert.equal(a.shadow.featureSchema,AI.FEATURE_SCHEMA);assert(a.shadow.facts?.flow?.relative===3.2,'raw decision facts must be frozen beside normalized features');assert(a.shadow.featureAblations&&Object.keys(a.shadow.featureAblations).length===AI.FEATURE_NAMES.length,'each decision must freeze one ablation probability per feature');assert(Object.values(a.shadow.featureAblations).every(Number.isFinite),'ablation probabilities must be finite');let snap=AI.caseSnapshot(a.shadow);assert(snap?.featureAblations&&snap.featureAblations.score!=null,'clean CASE snapshot must preserve frozen ablations for future Feature Tribunal scoring');
let before=s.modelSamples,res=AI.resolveShadow(a.shadow,row(),'TP',110,now+60000);assert.equal(res.shadow.status,'CLOSED');assert.equal(res.outcome.trainingAccepted,null,'resolution itself must not train before the clean case is durably stored');let z=AI.trainResolved(s,res.shadow,row({cycleId:a.shadow.caseId||'X'}),now+60001);s=z.state;assert.equal(s.modelSamples,before+1);assert.equal(z.shadow.outcome.trainingAccepted,true);assert.equal(s.marketRelations.current.WITH.cases,1);assert.equal(s.marketRelations.forecast60.WITH.cases,1);
// duplicate training protection stays bounded.
let caseRow=row({cycleId:'DEDUP'}),d=AI.decide(s,caseRow,market,now+3000,100),r=AI.resolveShadow(d.shadow,caseRow,'SL',95,now+90000),t=AI.trainResolved(d.state,r.shadow,caseRow,now+90001);let samples=t.state.modelSamples,t2=AI.trainResolved(t.state,t.shadow,caseRow,now+90002);assert.equal(t2.state.modelSamples,samples);assert(t2.duplicate,'same resolved case must never train twice');
let weak=row({cycleId:'WEAK',radarScore:42,flow:{minutes:60,relative:.9,pressure:50.5,persistence:15,impact:.05,move:-.7,speed:-.6,acceleration:-.1,score:42,eligible:false,alive:false,measuredAt:now}});a=AI.decide(s,weak,{upPct:30,downPct:65,fearGreed:{value:72}},now+3000,99);assert.equal(a.shadow.finalDecision,'SKIP');
let dirty=row({cycleId:'DIRTY'});a=AI.decide(s,dirty,market,now+4000,100);let samples0=a.state.modelSamples;z=AI.settle(a.state,a.shadow,dirty,'SL',95,now+100000,false);assert.equal(z.state.modelSamples,samples0,'REJECTED technical case must not train model');assert.equal(z.shadow.outcome.trainingAccepted,false);
let legacy=row({cycleId:'LEGACY',entryAt:now-10000});a=AI.decide(AI.initialState(now),legacy,market,now+1000,100);assert.equal(a.shadow.finalDecision,'IGNORE');assert.equal(a.shadow.status,'LEGACY');
let pub=AI.publicState(s,[{...row(),aiShadow:{status:'OPEN',finalDecision:'ENTER',symbol:'FROZENUSDT',direction:'SHORT',timeframe:'1h',confidence:.77,decidedAt:now,fillPrice:100,targetPrice:90,stopPrice:105}}]);assert.equal(pub.mode,'SHADOW');assert.equal(pub.featureSchema,AI.FEATURE_SCHEMA);assert(pub.open.length===1);assert.equal(pub.open[0].symbol,'FROZENUSDT');assert.equal(pub.open[0].dir,'SHORT');assert.equal(pub.open[0].tf,'1h');
// Daily economics: one individually profitable trade can be outweighed by a larger loss.
let dayState=AI.initialState(Date.UTC(2026,8,5,0,0,0));
function trainEconomic(st,id,at,exit){let w=row({cycleId:id,entryAt:at-1000,entryPrice:100,targetPrice:100.5,stopPrice:99});let geom=AI.executionGeometry('LONG',100,100.5,99),shadow={schema:AI.SCHEMA,featureSchema:AI.FEATURE_SCHEMA,status:'OPEN',finalDecision:'ENTER',modelDecision:'ENTER',symbol:w.symbol,direction:'LONG',timeframe:w.tf,decidedAt:at-900,modelVersion:AI.MODEL_VERSION,lineageId:st.lineageId,confidence:.7,features:AI.extractFeatures({...w,aiPortfolioContext:AI.portfolioContext(st,at-900)},market),facts:AI.decisionFacts(w,market,100),fillPrice:100,targetPrice:100.5,stopPrice:99,execution:geom,challengers:{}};let rr=AI.resolveShadow(shadow,w,exit>=100?'TP':'REVERSE',exit,at),tt=AI.trainResolved(st,rr.shadow,w,at);return tt.state}
let day1a=Date.UTC(2026,8,5,10,0,0);dayState=trainEconomic(dayState,'DAY-WIN',day1a,100.5);dayState=trainEconomic(dayState,'DAY-LOSS',day1a+3600000,99.8);let d1=AI.economicsPublic(dayState,day1a+7200000);assert.equal(d1.today.trades,2);assert(Math.abs(d1.today.profitPct-.3)<1e-9);assert(Math.abs(d1.today.lossPct-.4)<1e-9);assert(Math.abs(d1.today.netPct-(-.1))<1e-9,'daily total must be negative even though one trade was profitable');assert(Math.abs(d1.today.feesPct-.4)<1e-9,'each ENTER trade must charge 0.20% round trip');assert(d1.today.profitFactor<1,'a day where losses outweigh profits must have profit factor below 1');assert(d1.today.avgNetPct<0,'daily expectancy must expose that the portfolio is losing despite a winning trade');
// Economic magnitude is part of learning: a large loss carries more weight than a small net win.
let magW=row({cycleId:'MAG',entryPrice:100,targetPrice:100.5,stopPrice:98}),magGeo=AI.executionGeometry('LONG',100,100.5,98),magShadow={status:'OPEN',finalDecision:'ENTER',direction:'LONG',fillPrice:100,targetPrice:100.5,stopPrice:98,execution:magGeo};
let smallWin=AI.resolveShadow(magShadow,magW,'TP',100.3,day1a+8000000).outcome,largeLoss=AI.resolveShadow(magShadow,magW,'SL',99,day1a+8001000).outcome;assert(smallWin.netPnlPct>0&&largeLoss.netPnlPct<0);assert(largeLoss.economicWeight>smallWin.economicWeight,'a much larger loss must influence Trade AI more strongly than a small profitable trade');assert(largeLoss.economicSoftTarget<smallWin.economicSoftTarget,'net magnitude must be represented in the soft economic target');
let day2=Date.UTC(2026,8,5,22,30,0);dayState=trainEconomic(dayState,'NEXT-DAY',day2,100.6);let d2=AI.economicsPublic(dayState,day2+1000);assert(d2.today.day!==d1.today.day,'Riyadh next calendar day must have its own saved 24h bucket');assert.equal(d2.previousDay.day,d1.today.day);assert(Math.abs(d2.previousDay.netPct-(-.1))<1e-9);assert(Number.isFinite(Number(d2.deltaVsPreviousDay)),'new day must compare against prior saved day');
let skipState=AI.initialState(day1a),skipW=row({cycleId:'SKIP-NO-PORTFOLIO',entryAt:day1a,targetPrice:110,stopPrice:95}),skipDecision=AI.decide(skipState,skipW,{upPct:20,downPct:70,fearGreed:{value:80}},day1a+1000,100);if(skipDecision.shadow.finalDecision==='SKIP'){let sr=AI.resolveShadow(skipDecision.shadow,skipW,'TP',110,day1a+2000),st=AI.trainResolved(skipDecision.state,sr.shadow,skipW,day1a+2001);assert.equal(AI.economicsPublic(st.state,day1a+3000).today.trades,0,'SKIP counterfactuals must teach labels but must not alter actual Shadow portfolio PnL')}
let bounded=AI.initialState(now);for(let i=0;i<1200;i++){let w=row({cycleId:'B'+i,entryAt:now+1+i,radarScore:55+(i%40),flow:{minutes:60,relative:1+(i%30)/10,pressure:52+(i%20),persistence:35+(i%60),impact:(i%40)/10,move:(i%20)/10,speed:(i%9)/10,acceleration:(i%5)/100,score:55+(i%40),eligible:true,alive:true,measuredAt:now+i}});let q=AI.decide(bounded,w,market,now+10+i,100);bounded=q.state;bounded=AI.settle(bounded,q.shadow,w,i%3?'TP':'SL',i%3?110:95,now+1000+i,true).state}assert((bounded.recent||[]).length<=80);assert((bounded.trainedCaseIdsRecent||[]).length<=512);assert(Buffer.byteLength(JSON.stringify(bounded))<150000,'AI brain must remain bounded instead of storing every case');
const server=fs.readFileSync('server.js','utf8'),flow=fs.readFileSync('radar-flow.js','utf8');assert(server.includes("const AiFoundation=require('./ai-foundation.js')"));assert(server.includes('resolveAiShadow(w,reason,price,now)'));assert(server.includes('trainAiResolved(w,now)'));assert(!flow.includes('LabAI')&&!flow.includes('aiShadow'));
for(const f of ['public/index.html','index.html']){let html=fs.readFileSync(f,'utf8');assert(html.includes('data-page="ai"'));assert(html.includes('SHADOW EXECUTION'));assert(html.includes('لا يرسل أي أمر تداول حقيقي'));assert(html.includes('function renderAI()'))}
console.log('PASS: Trade AI net-PnL integrity, 0.20% no-BNB fees, execution geometry, 24h/day economics, historical comparison, dedupe and bounded brain');
