'use strict';
const assert=require('assert');
const fs=require('fs');
const AI=require('./lab-ai.js');
const now=Date.now();
function row(over={}){return {cycleId:'CASE-'+Math.random(),symbol:'TESTUSDT',dir:'LONG',tf:'4h',entryAt:now+1000,entryPrice:100,lastPrice:100,targetPrice:110,stopPrice:95,dataStale:false,radarScore:84,flow:{minutes:60,volume:900000,directionalVolume:600000,net:300000,relative:3.2,pressure:66,persistence:72,impact:3.4,move:1.1,speed:.45,acceleration:.05,score:84,eligible:true,alive:true,measuredAt:now},support:{pa:{enabled:true,pass:true},ce:{enabled:true,pass:true},ema:{enabled:true,pass:true}},...over}}
const market={direction:'UP',upPct:65,downPct:30,medianChangePct:1.1,updatedAt:now,fearGreed:{value:63},marketAI:{featureSchema:'MARKET-FEATURES-V1',modelVersion:'MARKET-AI-001',regime:'TURNING_UP',currentDirection:'UP',forecast60:{direction:'UP',confidence:.78,ready:true,samples:80}}};
let s=AI.initialState(now);assert.equal(AI.MODEL_VERSION,'SHADOW-AI-004-CORTEX');assert.equal(s.featureSchema,'FEATURES-V2-MARKET');assert(s.lineageId);
let mfLong=AI.extractFeatures(row({dir:'LONG'}),market),mfShort=AI.extractFeatures(row({dir:'SHORT'}),market);assert(mfLong.marketForecast>0&&mfLong.marketTurning>0&&mfLong.marketAgreement>0,'ready bullish Market AI must align a LONG feature');assert(mfShort.marketForecast<0&&mfShort.marketTurning<0&&mfShort.marketAgreement<0,'same market forecast must oppose a SHORT');let cold=AI.extractFeatures(row(),{...market,marketAI:{...market.marketAI,forecast60:{direction:'UP',confidence:.9,ready:false,samples:10}}});assert.equal(cold.marketForecast,0,'Trade AI must ignore Market AI forecast before readiness');

let a=AI.decide(s,row(),market,now+2000,100.2);s=a.state;assert(a.created&&a.shadow.finalDecision==='ENTER');assert(a.shadow.challengers?.BASE_AI&&a.shadow.challengers?.CORTEX_AI,'Trade AI must preserve Base/CORTEX challenger comparison');assert(a.shadow.confidence>=AI.PRIMARY_THRESHOLD);assert.equal(a.shadow.featureSchema,AI.FEATURE_SCHEMA);assert(a.shadow.facts?.flow?.relative===3.2,'raw decision facts must be frozen beside normalized features');assert(a.shadow.featureAblations&&Object.keys(a.shadow.featureAblations).length===AI.FEATURE_NAMES.length,'each decision must freeze one ablation probability per feature');assert(Object.values(a.shadow.featureAblations).every(Number.isFinite),'ablation probabilities must be finite');let snap=AI.caseSnapshot(a.shadow);assert(snap?.featureAblations&&snap.featureAblations.score!=null,'clean CASE snapshot must preserve frozen ablations for future Feature Tribunal scoring');
let before=s.modelSamples,res=AI.resolveShadow(a.shadow,row(),'TP',110,now+60000);assert.equal(res.shadow.status,'CLOSED');assert.equal(res.outcome.trainingAccepted,null,'resolution itself must not train before the clean case is durably stored');let z=AI.trainResolved(s,res.shadow,row({cycleId:a.shadow.caseId||'X'}),now+60001);s=z.state;assert.equal(s.modelSamples,before+1);assert.equal(z.shadow.outcome.trainingAccepted,true);assert.equal(s.marketRelations.current.WITH.cases,1);assert.equal(s.marketRelations.forecast60.WITH.cases,1);
// duplicate training protection stays bounded.
let caseRow=row({cycleId:'DEDUP'}),d=AI.decide(s,caseRow,market,now+3000,100),r=AI.resolveShadow(d.shadow,caseRow,'SL',95,now+90000),t=AI.trainResolved(d.state,r.shadow,caseRow,now+90001);let samples=t.state.modelSamples,t2=AI.trainResolved(t.state,t.shadow,caseRow,now+90002);assert.equal(t2.state.modelSamples,samples);assert(t2.duplicate,'same resolved case must never train twice');
let weak=row({cycleId:'WEAK',radarScore:42,flow:{minutes:60,relative:.9,pressure:50.5,persistence:15,impact:.05,move:-.7,speed:-.6,acceleration:-.1,score:42,eligible:false,alive:false,measuredAt:now}});a=AI.decide(s,weak,{upPct:30,downPct:65,fearGreed:{value:72}},now+3000,99);assert.equal(a.shadow.finalDecision,'SKIP');
let dirty=row({cycleId:'DIRTY'});a=AI.decide(s,dirty,market,now+4000,100);let samples0=a.state.modelSamples;z=AI.settle(a.state,a.shadow,dirty,'SL',95,now+100000,false);assert.equal(z.state.modelSamples,samples0,'REJECTED technical case must not train model');assert.equal(z.shadow.outcome.trainingAccepted,false);
let legacy=row({cycleId:'LEGACY',entryAt:now-10000});a=AI.decide(AI.initialState(now),legacy,market,now+1000,100);assert.equal(a.shadow.finalDecision,'IGNORE');assert.equal(a.shadow.status,'LEGACY');
let pub=AI.publicState(s,[{...row(),aiShadow:{status:'OPEN',finalDecision:'ENTER',confidence:.77,decidedAt:now,fillPrice:100,targetPrice:110,stopPrice:95}}]);assert.equal(pub.mode,'SHADOW');assert.equal(pub.featureSchema,AI.FEATURE_SCHEMA);assert(pub.open.length===1);
let bounded=AI.initialState(now);for(let i=0;i<1200;i++){let w=row({cycleId:'B'+i,entryAt:now+1+i,radarScore:55+(i%40),flow:{minutes:60,relative:1+(i%30)/10,pressure:52+(i%20),persistence:35+(i%60),impact:(i%40)/10,move:(i%20)/10,speed:(i%9)/10,acceleration:(i%5)/100,score:55+(i%40),eligible:true,alive:true,measuredAt:now+i}});let q=AI.decide(bounded,w,market,now+10+i,100);bounded=q.state;bounded=AI.settle(bounded,q.shadow,w,i%3?'TP':'SL',i%3?110:95,now+1000+i,true).state}assert((bounded.recent||[]).length<=80);assert((bounded.trainedCaseIdsRecent||[]).length<=512);assert(Buffer.byteLength(JSON.stringify(bounded))<90000,'AI brain must remain bounded instead of storing every case');
const server=fs.readFileSync('server.js','utf8'),flow=fs.readFileSync('radar-flow.js','utf8');assert(server.includes("const AiFoundation=require('./ai-foundation.js')"));assert(server.includes('resolveAiShadow(w,reason,price,now)'));assert(server.includes('trainAiResolved(w,now)'));assert(!flow.includes('LabAI')&&!flow.includes('aiShadow'));
for(const f of ['public/index.html','index.html']){let html=fs.readFileSync(f,'utf8');assert(html.includes('data-page="ai"'));assert(html.includes('SHADOW EXECUTION'));assert(html.includes('لا يرسل أي أمر تداول حقيقي'));assert(html.includes('function renderAI()'))}
console.log('PASS: shadow decisions freeze raw facts + feature ablations, resolve-before-train transaction, dedupe, VALID-only training and bounded AI brain');
