const assert=require('assert');
const {spawn}=require('child_process');
const fs=require('fs'),os=require('os'),path=require('path');
const PORT=31983, base=`http://127.0.0.1:${PORT}`;
const data=fs.mkdtempSync(path.join(os.tmpdir(),'alpha-proof-v893-'));
fs.writeFileSync(path.join(data,'state.json'),JSON.stringify({settings:{liveEnabled:false,scanMode:'manual'}}));
function start(){return spawn(process.execPath,['server.js'],{cwd:__dirname,env:{...process.env,PORT:String(PORT),DATA_DIR:data,ALPHAPROOF_TELEGRAM_TOKEN:'',ALPHAPROOF_TELEGRAM_CHAT_ID:''},stdio:['ignore','pipe','pipe']})}
async function ready(proc){let out='';proc.stdout.on('data',d=>out+=d);proc.stderr.on('data',d=>out+=d);for(let i=0;i<50;i++){try{let r=await fetch(base+'/health');if(r.ok)return}catch{}await new Promise(r=>setTimeout(r,80))}throw new Error('server not ready '+out)}
async function stop(proc){if(proc.exitCode!=null)return;proc.kill('SIGTERM');await Promise.race([new Promise(r=>proc.once('exit',r)),new Promise(r=>setTimeout(r,3000))])}
(async()=>{let p=start();try{await ready(p);let h=await (await fetch(base+'/health')).json();assert.equal(h.version,'8.9.3-CLOUD-FULL-JOURNEY-AUTOSAVE');let changed={...(await (await fetch(base+'/api/settings/defaults')).json()).settings,liveEnabled:false,scanMode:'manual',autoScanMin:7,paLookback:9,expThreshold1:1.55,emaLength:123,trendMaxBars:33,flowMinMove:.77,flowWindows:'15,60,240',featuredTelegramEnabled:false};let r=await fetch(base+'/api/settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(changed)});assert(r.ok);let j=await r.json();assert(j.settingsRevision>=1);assert.equal(j.settings.flowMinMove,.77);assert.equal(j.settings.emaLength,123);let st=await (await fetch(base+'/api/state')).json();assert.equal(st.settings.paLookback,9);assert.equal(st.settings.expThreshold1,1.55);assert.equal(st.settings.autoScanMin,7);assert.equal(st.settingsRevision,j.settingsRevision);let restart=await (await fetch(base+'/api/restart',{method:'POST',headers:{'content-type':'application/json'},body:'{}'})).json();assert.equal(restart.state.settings.flowMinMove,.77);assert.equal(restart.state.settingsRevision,0);assert.equal(restart.state.learningSamplesCount,0);r=await fetch(base+'/api/settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...changed,flowMinMove:.78})});j=await r.json();assert(j.settingsRevision>=1);assert.equal(j.settings.flowMinMove,.78);await new Promise(r=>setTimeout(r,350));await stop(p);let persisted=JSON.parse(fs.readFileSync(path.join(data,'state.json'),'utf8'));assert(persisted.settingsHistory.length>=1);assert.equal(persisted.settings.flowMinMove,.78);p=start();await ready(p);st=await (await fetch(base+'/api/state')).json();assert.equal(st.settings.flowMinMove,.78);assert.equal(st.settings.emaLength,123);assert.equal(st.settings.paLookback,9);assert(st.settingsRevision>=1);r=await fetch(base+'/api/settings/reset',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});j=await r.json();assert.equal(j.settings.flowMinMove,.12);assert.equal(j.settings.emaLength,200);assert(j.settingsRevision>st.settingsRevision);let t=await fetch(base+'/api/telegram/test',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});assert.equal(t.status,400);console.log('PASS: live settings API, normalization, persistence across restart, defaults reset and safe Telegram test');}finally{await stop(p).catch(()=>{});fs.rmSync(data,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exit(1)});
