const assert=require('assert');
const {spawn}=require('child_process');
const fs=require('fs'),os=require('os'),path=require('path');
const AI=require('./lab-ai.js');
const LearningForge=require('./learning-forge.js');
const PORT=31983, base=`http://127.0.0.1:${PORT}`;
const data=fs.mkdtempSync(path.join(os.tmpdir(),'alpha-proof-v950-'));
fs.mkdirSync(path.join(data,'lab-memory','archives'),{recursive:true});
fs.writeFileSync(path.join(data,'lab-memory','current.jsonl'),JSON.stringify({type:'MANIFEST',schema:'alpha-proof-lab-memory/1',cycleId:'OLD-CLEAN-CYCLE'})+'\n'+JSON.stringify({type:'CASE',case:{caseId:'PRESERVE-ME'}})+'\n');
let legacyBrain=AI.initialState(Date.now()-3600000);legacyBrain.modelSamples=37;legacyBrain.decisions=55;legacyBrain.weights.score=.21;
fs.writeFileSync(path.join(data,'state.json'),JSON.stringify({
 settings:{liveEnabled:false,scanMode:'manual',sortMode:'symbol'},
 liveRows:[{symbol:'KEEPUSDT',dir:'LONG',tf:'4h',radarScore:55,luxFlashActive:true}],
 active:{KEEPUSDT:{cycleId:'LEGACY-ACTIVE',symbol:'KEEPUSDT',dir:'LONG',tf:'4h',entryAt:Date.now()-1000,entryPrice:1,targetPrice:2,stopPrice:.5,setup:{huge:'OLD_SETUP'}}},
 closed:[{symbol:'OLDUSDT',result:'TP'}],learningSamples:[{id:'OLD_NOISE'}],hiddenResearch:{OLD:{noise:true}},
 memory:{epoch:'LAB-MEMORY-V1-2026-09-05',schema:'alpha-proof-lab-memory/1',cycleId:'OLD-CLEAN-CYCLE',validCount:1},aiLab:legacyBrain
}));
function start(){return spawn(process.execPath,['server.js'],{cwd:__dirname,env:{...process.env,PORT:String(PORT),DATA_DIR:data,ALPHAPROOF_TELEGRAM_TOKEN:'',ALPHAPROOF_TELEGRAM_CHAT_ID:''},stdio:['ignore','pipe','pipe']})}
async function ready(proc){let out='';proc.stdout.on('data',d=>out+=d);proc.stderr.on('data',d=>out+=d);for(let i=0;i<70;i++){try{let r=await fetch(base+'/health');if(r.ok)return}catch{}await new Promise(r=>setTimeout(r,80))}throw new Error('server not ready '+out)}
async function stop(proc){if(proc.exitCode!=null)return;proc.kill('SIGTERM');await Promise.race([new Promise(r=>proc.once('exit',r)),new Promise(r=>setTimeout(r,3000))])}
(async()=>{let p=start();try{
 await ready(p);let h=await (await fetch(base+'/health')).json();assert.equal(h.version,'9.9.4-PROFIT-FIRST-SHADOW-MENTOR-RECOVERY-A-B');assert.equal(h.aiMode,'SHADOW');assert.equal(h.aiFeatureSchema,'FEATURES-V3-ECONOMICS');assert.equal(h.spotRoundTripFeePct,.20);assert.equal(h.marketAiMode,'SHADOW_MARKET');assert.equal(h.marketAiFeatureSchema,'MARKET-FEATURES-V1');assert.equal(h.cortexMode,'PROSPECTIVE_RESEARCH');assert.equal(h.cortexVersion,LearningForge.MODEL_VERSION);
 let home=await fetch(base+'/');assert(home.ok);let html=await home.text();assert(html.includes('أقوى لونق')&&html.includes('أقوى شورت'));assert((home.headers.get('cache-control')||'').includes('no-store'));
 let st=await (await fetch(base+'/api/state')).json();assert.equal(st.settings.sortMode,'luxRecent');assert.equal(st.closed.length,0);assert.equal(st.learningSamplesCount,0);assert.equal(st.liveRows.length,1);assert(st.active.KEEPUSDT);assert.equal(st.active.KEEPUSDT.memoryEligible,false);assert.equal(st.active.KEEPUSDT.aiShadow?.status,'LEGACY');assert(!('setup' in st.active.KEEPUSDT));
 assert.equal(st.memory.schema,'alpha-proof-lab-memory/2');assert.equal(st.memory.rejectedRetentionHours,24);assert.equal(st.aiLab.modelSamples,0,'legacy weights must not enter the clean cohort');assert.equal(st.aiLab.featureSchema,'FEATURES-V3-ECONOMICS');assert.equal(st.aiLab.roundTripFeePct,.20);assert(st.aiLab.foundation&&st.aiLab.foundation.checkpointCount>=1);assert(st.memoryTotals&&Number.isFinite(st.memoryTotals.ramLimitBytes));assert.equal(st.memoryUsage,null,'usage must not be calculated by ordinary /api/state polling');let mem=await (await fetch(base+'/api/memory/usage',{method:'POST',headers:{'content-type':'application/json'},body:'{}'})).json();assert(mem.ok&&Number.isFinite(mem.ram.rssBytes)&&Number.isFinite(mem.storage.usedBytes));st=await (await fetch(base+'/api/state')).json();assert(st.memoryUsage&&st.memoryUsage.measuredAt===mem.measuredAt);
 assert(fs.existsSync(path.join(data,'research-cohorts','CLEAN-PROSPECTIVE-1','ai-foundation','brain.json')),'AI brain must live outside state.json');assert(fs.existsSync(path.join(data,'research-cohorts','CLEAN-PROSPECTIVE-1','adaptive-manager','brain.json')),'Adaptive Manager must live outside runtime state.json');assert(st.marketAI&&st.marketAI.featureSchema==='MARKET-FEATURES-V1');assert(fs.existsSync(path.join(data,'market-ai-foundation','brain.json')),'Market AI brain must be separate');assert(fs.existsSync(path.join(data,'market-ai-foundation','runtime.json')),'Market AI runtime must be separate');assert(fs.existsSync(path.join(data,'market-ai-foundation','market-dataset.jsonl')),'Market AI dataset must be separate');assert(st.cortex&&st.cortex.modelVersion===LearningForge.MODEL_VERSION,'CORTEX public state must expose current research model');assert.equal(st.cortex.cortexFeatureSchema,LearningForge.CORTEX_FEATURE_SCHEMA);assert(st.cortex.statisticalFirewall?.enabled&&st.cortex.statisticalFirewall?.multipleTestingAdjusted,'CORTEX Statistical Firewall must be active');assert.equal(st.cortex.mentorCalibration?.policy,'PER_EDGE_MARGINAL_PAIRED_SHADOW_BRIER_LCB');assert.equal(st.cortex.mentorCalibration?.minSamplesPerEdge,100);assert.equal(st.cortex.riskProven,0,'Profit First must not expose proven RISK rules');assert(fs.existsSync(path.join(data,'research-cohorts','CLEAN-PROSPECTIVE-1','omega-cortex','brain.json')),'CORTEX brain must be separate from runtime');assert(fs.existsSync(path.join(data,'research-cohorts','CLEAN-PROSPECTIVE-1','omega-cortex','research-events-v4.jsonl')),'CORTEX research events must be separate');
 let preserved=fs.readdirSync(path.join(data,'lab-memory','archives')).filter(x=>x.includes('preserved'));assert(preserved.length>=1,'previous clean v1 dataset must be archived before v2 starts');assert(fs.readFileSync(path.join(data,'lab-memory','archives',preserved[0]),'utf8').includes('PRESERVE-ME'));
 let exp=await fetch(base+'/api/memory/export');assert(exp.ok);let expText=await exp.text();assert(expText.includes('"schema":"alpha-proof-lab-memory/2"')&&expText.includes('"featureSchema":"FEATURES-V3-ECONOMICS"'));assert(!expText.includes('OLD_NOISE')&&!expText.includes('OLDUSDT'));let mexp=await fetch(base+'/api/market-ai/export');assert(mexp.ok);let mtxt=await mexp.text();assert(mtxt.includes('alpha-proof-market-ai-dataset/1'));assert(mtxt.includes('MARKET-FEATURES-V1'));let cexp=await fetch(base+'/api/cortex/export');assert(cexp.ok);let ctxt=await cexp.text();assert(ctxt.includes('alpha-proof-omega-cortex-events/4'));assert(ctxt.includes('CORTEX-RESEARCH-V4-ECONOMICS'));assert(ctxt.includes(LearningForge.MODEL_VERSION));
 let defaults=(await (await fetch(base+'/api/settings/defaults')).json()).settings,changed={...defaults,liveEnabled:false,scanMode:'manual',autoScanMin:7,paLookback:9,expThreshold1:1.55,emaLength:123,trendMaxBars:33,flowMinMove:.77,flowWindows:'15,60,240',featuredTelegramEnabled:false,freshSignalMovePct:4.2};let r=await fetch(base+'/api/settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(changed)});assert(r.ok);let j=await r.json();assert(j.settingsRevision>=1);st=await (await fetch(base+'/api/state')).json();let lineage=st.aiLab.lineageId,samples=st.aiLab.modelSamples,cycle=st.memory.cycleId,cortexLineage=st.cortex.lineageId,cortexCases=st.cortex.observedCases;
 // Dataset rotation never touches the brain.
 let rot=await (await fetch(base+'/api/memory/rotate',{method:'POST',headers:{'content-type':'application/json'},body:'{}'})).json();assert(rot.ok&&rot.archiveName&&rot.downloadPath);assert.notEqual(rot.memory.cycleId,cycle);st=await (await fetch(base+'/api/state')).json();assert.equal(st.aiLab.modelSamples,samples);assert.equal(st.aiLab.lineageId,lineage);assert.equal(st.cortex.lineageId,cortexLineage);assert.equal(st.cortex.observedCases,cortexCases);assert.equal(st.liveRows.length,1);assert(st.active.KEEPUSDT);let cycleAfterRotate=st.memory.cycleId;
 // Ordinary Restart is runtime-only in Foundation: it must NEVER erase dataset or AI brain.
 let restart=await (await fetch(base+'/api/restart',{method:'POST',headers:{'content-type':'application/json'},body:'{}'})).json();assert.equal(restart.state.settings.flowMinMove,.77);assert.equal(restart.state.liveRows.length,0);assert.equal(restart.state.aiLab.modelSamples,samples);assert.equal(restart.state.aiLab.lineageId,lineage);assert.equal(restart.state.cortex.lineageId,cortexLineage);assert.equal(restart.state.cortex.observedCases,cortexCases);assert.equal(restart.state.memory.cycleId,cycleAfterRotate,'runtime restart must not start a new dataset cycle');
 await new Promise(r=>setTimeout(r,350));await stop(p);let persisted=JSON.parse(fs.readFileSync(path.join(data,'state.json'),'utf8'));assert.equal(persisted.settings.flowMinMove,.77);assert(!('learningSamples' in persisted));assert(!('hiddenResearch' in persisted));assert(!('aiLab' in persisted),'AI brain must not be duplicated inside runtime recovery state');assert(!('adaptiveManager' in persisted),'Adaptive Manager must not be duplicated inside runtime state');assert(!('closed' in persisted),'closed history must be cold-stored instead of duplicated in state.json');
 // Preserve a nonzero trained checkpoint through process restart.
 const brainPath=path.join(data,'research-cohorts','CLEAN-PROSPECTIVE-1','ai-foundation','brain.json');let savedBrain=JSON.parse(fs.readFileSync(brainPath,'utf8'));savedBrain.brain.modelSamples=7;savedBrain.brain.weights.score=.21;samples=7;fs.writeFileSync(brainPath,JSON.stringify(savedBrain));
 p=start();await ready(p);st=await (await fetch(base+'/api/state')).json();assert.equal(st.aiLab.modelSamples,samples);assert.equal(st.aiLab.lineageId,lineage,'brain must survive a real server process restart');assert.equal(st.aiLab.weights.score,.21);let gov=await (await fetch(base+'/api/research/governance')).json();assert.equal(gov.id,st.researchGovernance.id);assert.equal(gov.objective.calibrationIsProfit,false);assert.equal(st.cortex.lineageId,cortexLineage,'CORTEX brain must survive a real server process restart');assert.equal(st.cortex.observedCases,cortexCases);assert.equal(st.settings.flowMinMove,.77);assert.equal(st.memory.cycleId,cycleAfterRotate);
 r=await fetch(base+'/api/settings/reset',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});j=await r.json();assert.equal(j.settings.flowMinMove,.12);let t=await fetch(base+'/api/telegram/test',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});assert.equal(t.status,400);
 console.log('PASS: v9.9.0 tiered-memory Foundation preserves compatible brain, separates runtime/datasets/AI brains, exports V4 research evidence, and keeps Restart non-destructive');
}finally{await stop(p).catch(()=>{});fs.rmSync(data,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exit(1)});
