'use strict';

// Binance USDⓈ-M compatible account model for ALPHA PROOF.
// The engine is mode-aware from day one, but this build only mutates PAPER state.
// TESTNET/LIVE require a separate verified exchange adapter; no credentials,
// signer or order transport exist here.
const SCHEMA='alpha-proof-futures-account/1';
const EXCHANGE='BINANCE_USDM';
const QUOTE_ASSET='USDT';
const MAX_FILLS=300,MAX_REJECTIONS=100;
const finite=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const round=(v,d=10)=>Number.isFinite(Number(v))?Number(Number(v).toFixed(d)):null;
const day=now=>new Date(finite(now,Date.now())+3*3600000).toISOString().slice(0,10);
function configuredMode(cfg={}){const m=String(cfg.mode??process.env.FUTURES_EXECUTION_MODE??'PAPER').toUpperCase();return ['PAPER','TESTNET','LIVE'].includes(m)?m:'PAPER';}
function takerFeePct(cfg={}){const v=finite(cfg.takerFeePct??process.env.FUTURES_TAKER_FEE_PCT,.05);return v>=0?v:.05;}
function makerFeePct(cfg={}){const v=finite(cfg.makerFeePct??process.env.FUTURES_MAKER_FEE_PCT,.02);return v>=0?v:.02;}
function maintenanceMarginRate(cfg={}){const v=finite(cfg.maintenanceMarginRate??process.env.FUTURES_MAINTENANCE_MARGIN_RATE,.004);return v>=0?v:.004;}
function adapterState(mode){return {name:'binance-usdm',contractVersion:1,connected:false,executionEnabled:mode==='PAPER',paperExecutionEnabled:true,testnetPlacementImplemented:false,liveOrderPlacementImplemented:false,requiresVerifiedExchangeFill:mode!=='PAPER',status:mode==='PAPER'?'PAPER_READY':mode==='TESTNET'?'LOCKED_ADAPTER_REQUIRED':'LOCKED_LIVE_ADAPTER_REQUIRED'};}
function initialState(cfg={}){const capital=Math.max(0,finite(cfg.initialCapitalUSDT??process.env.FUTURES_INITIAL_USDT,10000)),mode=configuredMode(cfg);return {schema:SCHEMA,mode,exchange:EXCHANGE,quoteAsset:QUOTE_ASSET,initialCapitalUSDT:capital,cashUSDT:capital,realizedPnlUSDT:0,feesUSDT:0,fundingUSDT:0,closedTrades:0,positions:{},fills:[],rejections:[],updatedAt:Date.now(),policy:{marginMode:'ISOLATED_MODEL',defaultMarginUSDT:Math.max(0,finite(cfg.tradeMarginUSDT??process.env.FUTURES_TRADE_MARGIN_USDT,100)),makerFeePct:makerFeePct(cfg),takerFeePct:takerFeePct(cfg),commissionSource:'CONFIGURABLE_ACCOUNT_RATE_FALLBACK',maintenanceMarginRate:maintenanceMarginRate(cfg),leverageStrategyMax:null},adapter:adapterState(mode)};}
function normalize(raw={},cfg={}){const b=initialState(cfg),x=raw&&typeof raw==='object'?raw:{},mode=configuredMode({mode:x.mode??cfg.mode}),positions={};for(const [id,p] of Object.entries(x.positions&&typeof x.positions==='object'?x.positions:{})){const entry=finite(p.entryPrice),qty=finite(p.quantity),margin=finite(p.marginUSDT),lev=finite(p.leverage);if(entry>0&&qty>0&&margin>0&&lev>=1)positions[id]={...p,id:String(p.id||id),symbol:String(p.symbol||''),direction:p.direction==='SHORT'?'SHORT':'LONG',entryPrice:entry,quantity:qty,marginUSDT:margin,leverage:lev,entryFeeUSDT:Math.max(0,finite(p.entryFeeUSDT)),fundingUSDT:finite(p.fundingUSDT),entryAt:finite(p.entryAt,Date.now())};}
 return {...b,...x,schema:SCHEMA,mode,exchange:EXCHANGE,quoteAsset:QUOTE_ASSET,initialCapitalUSDT:Math.max(0,finite(x.initialCapitalUSDT,b.initialCapitalUSDT)),cashUSDT:finite(x.cashUSDT,b.cashUSDT),realizedPnlUSDT:finite(x.realizedPnlUSDT),feesUSDT:Math.max(0,finite(x.feesUSDT)),fundingUSDT:finite(x.fundingUSDT),closedTrades:Math.max(0,Math.floor(finite(x.closedTrades))),positions,fills:Array.isArray(x.fills)?x.fills.slice(-MAX_FILLS):[],rejections:Array.isArray(x.rejections)?x.rejections.slice(-MAX_REJECTIONS):[],updatedAt:finite(x.updatedAt,Date.now()),policy:{...b.policy,...(x.policy||{}),leverageStrategyMax:null},adapter:adapterState(mode)};}
function reject(s,code,detail={},now=Date.now()){s.rejections.push({t:now,day:day(now),code,...detail});s.rejections=s.rejections.slice(-MAX_REJECTIONS);s.updatedAt=now;return s;}
function markFor(p,marks={}){const px=finite(marks?.[p.symbol],p.entryPrice);return px>0?px:p.entryPrice;}
function grossPnl(p,price){const move=p.direction==='SHORT'?(p.entryPrice-price):(price-p.entryPrice);return move*p.quantity;}
function exitFee(p,price){return Math.max(0,p.quantity*price*finite(p.exitFeePct,p.entryFeePct));}
function liquidationPrice(p){const mmr=Math.max(0,finite(p.maintenanceMarginRate,.004)),L=Math.max(1,finite(p.leverage,1));if(p.direction==='SHORT')return p.entryPrice*(1+1/L-mmr);return Math.max(0,p.entryPrice*(1-1/L+mmr));}
function valuation(raw,marks={}){const s=normalize(raw),positions=[];let lockedMarginUSDT=0,unrealizedPnlUSDT=0,estimatedExitFeesUSDT=0,equityUSDT=s.cashUSDT;for(const p of Object.values(s.positions)){const markPrice=markFor(p,marks),gross=grossPnl(p,markPrice),fee=exitFee(p,markPrice),positionEquity=Math.max(0,p.marginUSDT+gross-fee+p.fundingUSDT);lockedMarginUSDT+=p.marginUSDT;unrealizedPnlUSDT+=gross-fee+p.fundingUSDT-p.entryFeeUSDT;estimatedExitFeesUSDT+=fee;equityUSDT+=positionEquity;positions.push({...p,markPrice:round(markPrice),liquidationPrice:round(liquidationPrice(p)),notionalUSDT:round(p.quantity*markPrice),unrealizedPnlUSDT:round(gross-fee+p.fundingUSDT-p.entryFeeUSDT),positionEquityUSDT:round(positionEquity)});}return {positions,lockedMarginUSDT,unrealizedPnlUSDT,estimatedExitFeesUSDT,equityUSDT,totalPnlUSDT:equityUSDT-s.initialCapitalUSDT};}
function requestedMargin(s,opts={}){const explicit=Number(opts.marginUSDT);if(Number.isFinite(explicit)&&explicit>=0)return explicit;return Math.max(0,finite(s.policy.defaultMarginUSDT,100));}
function open(raw,trade,now=Date.now(),opts={}){let s=normalize(raw);if(!trade||trade.finalDecision!=='ENTER')return s;const profile=trade.executionProfile||{},id=String(opts.id||trade.caseId||trade.cycleId||''),symbol=String(trade.symbol||''),direction=profile.direction==='SHORT'||trade.direction==='SHORT'?'SHORT':'LONG',leverage=finite(profile.leverage);if(profile.venue!=='FUTURES')return s;if(!id)return reject(s,'MISSING_POSITION_ID',{symbol},now);if(s.positions[id])return s;if(!(leverage>=1))return reject(s,'INVALID_LEVERAGE',{id,symbol,leverage},now);const price=finite(trade.fillPrice);if(!(price>0))return reject(s,'INVALID_FILL_PRICE',{id,symbol},now);if(s.mode!=='PAPER')return reject(s,s.mode==='LIVE'?'LIVE_EXECUTION_FAIL_CLOSED':'TESTNET_ADAPTER_REQUIRED',{id,symbol},now);
 const margin=Math.min(requestedMargin(s,opts),Math.max(0,s.cashUSDT)),feePct=Math.max(0,finite(opts.commissionPct,s.policy.takerFeePct))/100,notional=margin*leverage,fee=notional*feePct;if(!(margin>0)||margin+fee>s.cashUSDT+1e-9)return reject(s,'INSUFFICIENT_FUTURES_CASH',{id,symbol},now);const quantity=notional/price,mmr=Math.max(0,finite(opts.maintenanceMarginRate,s.policy.maintenanceMarginRate));s.cashUSDT-=margin+fee;s.feesUSDT+=fee;s.positions[id]={id,symbol,direction,side:direction==='LONG'?'BUY':'SELL',entryAt:now,entryPrice:price,quantity,marginUSDT:margin,costUSDT:margin,initialNotionalUSDT:notional,leverage,entryFeePct:feePct,exitFeePct:feePct,entryFeeUSDT:fee,fundingUSDT:0,maintenanceMarginRate:mmr,liquidationPrice:null,feePolicy:'BINANCE_USDM_CONFIGURABLE',commissionSource:s.policy.commissionSource,source:'ALPHA_PROOF_AI'};s.positions[id].liquidationPrice=liquidationPrice(s.positions[id]);s.fills.push({t:now,day:day(now),id,symbol,venue:'FUTURES',direction,side:s.positions[id].side,action:'OPEN',price,quantity,notionalUSDT:notional,marginUSDT:margin,leverage,feeUSDT:fee,feePct:feePct*100,mode:'PAPER'});s.fills=s.fills.slice(-MAX_FILLS);s.updatedAt=now;return s;}
function accrueFunding(raw,id,amountUSDT,now=Date.now()){let s=normalize(raw),p=s.positions[String(id||'')],a=finite(amountUSDT);if(!p||!Number.isFinite(a))return s;p.fundingUSDT+=a;s.fundingUSDT+=a;s.updatedAt=now;return s;}
function liquidationHit(raw,id,price){const s=normalize(raw),p=s.positions[String(id||'')],px=finite(price);if(!p||!(px>0))return {hit:false};const liq=finite(p.liquidationPrice,liquidationPrice(p)),hit=p.direction==='SHORT'?px>=liq:px<=liq;return {hit,price:hit?liq:px,liquidationPrice:liq,direction:p.direction,leverage:p.leverage};}
function close(raw,id,price,now=Date.now(),opts={}){let s=normalize(raw);id=String(id||'');const p=s.positions[id],px=finite(price);if(!p)return s;if(!(px>0))return reject(s,'INVALID_EXIT_PRICE',{id,symbol:p.symbol},now);if(s.mode!=='PAPER')return reject(s,s.mode==='LIVE'?'LIVE_EXECUTION_FAIL_CLOSED':'TESTNET_ADAPTER_REQUIRED',{id,symbol:p.symbol},now);const gross=grossPnl(p,px),fee=exitFee(p,px),settlement=Math.max(0,p.marginUSDT+gross-fee+p.fundingUSDT),realized=settlement-p.marginUSDT-p.entryFeeUSDT;s.cashUSDT+=settlement;s.realizedPnlUSDT+=realized;s.feesUSDT+=fee;s.closedTrades++;s.fills.push({t:now,day:day(now),id,symbol:p.symbol,venue:'FUTURES',direction:p.direction,side:p.direction==='LONG'?'SELL':'BUY',action:'CLOSE',reason:String(opts.reason||'EXIT'),price:px,quantity:p.quantity,notionalUSDT:p.quantity*px,marginUSDT:p.marginUSDT,leverage:p.leverage,feeUSDT:fee,feePct:p.exitFeePct*100,fundingUSDT:p.fundingUSDT,realizedPnlUSDT:realized,mode:'PAPER'});delete s.positions[id];s.fills=s.fills.slice(-MAX_FILLS);s.updatedAt=now;return s;}
function publicState(raw,marks={}){const s=normalize(raw),v=valuation(s,marks);return {schema:SCHEMA,mode:s.mode,exchange:EXCHANGE,quoteAsset:QUOTE_ASSET,initialCapitalUSDT:round(s.initialCapitalUSDT),cashUSDT:round(s.cashUSDT),equityUSDT:round(v.equityUSDT),lockedMarginUSDT:round(v.lockedMarginUSDT),unrealizedPnlUSDT:round(v.unrealizedPnlUSDT),realizedPnlUSDT:round(s.realizedPnlUSDT),totalPnlUSDT:round(v.totalPnlUSDT),feesUSDT:round(s.feesUSDT),fundingUSDT:round(s.fundingUSDT),closedTrades:s.closedTrades,openPositions:v.positions,recentFills:s.fills.slice(-30).reverse(),recentRejections:s.rejections.slice(-12).reverse(),policy:s.policy,adapter:s.adapter,execution:s.mode==='PAPER'?'PAPER_ACCOUNTING':s.mode==='TESTNET'?'FAIL_CLOSED_ADAPTER_REQUIRED':'FAIL_CLOSED_LIVE_ADAPTER_REQUIRED'};}
module.exports={SCHEMA,EXCHANGE,QUOTE_ASSET,initialState,normalize,valuation,open,close,accrueFunding,liquidationHit,liquidationPrice,publicState,takerFeePct,makerFeePct};
